cryostatio/cryostat-legacy

- build.gradle
Allow transitive dependency from container-jfr-core to fulfill
requirement
> Remove dependency on eclipse runtime

- build.gradle
- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/AbstractConnectedCommand.java
- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/ConnectCommand.java
- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/EventOptionsBuilder.java
- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/IsConnectedCommand.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/ConnectionListener.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/NetworkModule.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/RecordingExporter.java
- src/main/java/com/redhat/rhjmc/containerjfr/tui/tty/InteractiveShellExecutor.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/AbstractConnectedCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/AbstractRecordingCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/ConnectCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/DeleteCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/DisconnectCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/DumpCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/EventOptionsBuilderTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/IsConnectedCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/ListCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/ListEventTypesCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/ListRecordingOptionsCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/SaveRecordingCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/SearchEventsCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/SnapshotCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/StartRecordingCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/StopRecordingCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/WaitForCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/WaitForDownloadCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/net/RecordingExporterTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/tui/tty/InteractiveShellExecutorTest.java
> Bump container-jfr-core version to 0.2.0

- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/AbstractConnectedCommand.java
- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/SaveRecordingCommand.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/AbstractConnectedCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/SaveRecordingCommandTest.java
> Allow optional .jfr extension on recording names

- build.gradle
- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/SaveRecordingCommand.java
Report filenames in serialized response upon save
Fixes #53
> Indicate target JVM hostname in archived recording filenames

- src/main/java/com/redhat/rhjmc/containerjfr/ContainerJfr.java
- src/main/java/com/redhat/rhjmc/containerjfr/MainModule.java
- src/main/java/com/redhat/rhjmc/containerjfr/commands/SerializableCommand.java
- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/DeleteCommand.java
- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/ExitCommand.java
- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/HelpCommand.java
- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/StopRecordingCommand.java
- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/UploadRecordingCommand.java
- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/WaitForCommand.java
- src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/PlatformDetectionStrategy.java
- src/main/java/com/redhat/rhjmc/containerjfr/tui/tty/TtyClientReader.java
A trivial pull request to fix small bad practices I saw over time. For a list of changes please refer to tabjy/container-jfr#3.
Closes tabjy/container-jfr#3.
> Various small fixes. 

- build.gradle
- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/SaveRecordingCommand.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/SaveRecordingCommandTest.java
> File autorename

- README.md
> Remove reference to trello board

- README.md
- build.gradle
- src/main/java/com/redhat/rhjmc/containerjfr/net/AbstractAuthManager.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/AuthManager.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/BasicAuthManager.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/NetworkModule.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/NoopAuthManager.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/WebServer.java
- src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/OpenShiftPlatformClient.java
- src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/MessagingServer.java
- src/test/java/com/redhat/rhjmc/containerjfr/net/BasicAuthManagerTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/net/web/WebServerTest.java
Fixes #103
Based on top of currently open PR #105
> Basic authmanager

- src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/MalformedMessageResponseMessage.java
- src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/ResponseMessage.java
- src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/WsCommandExecutor.java
- src/test/java/com/redhat/rhjmc/containerjfr/tui/ws/WsCommandExecutorTest.java
> Malformed WebSocket message handling

- pom.xml
- src/test/java/itest/IntegrationTestUtils.java
- src/test/java/itest/SanityIT.java
This adds configuration for integration testing of the produced container image, as well as a handful of very basic tests.
(Based on top of #130)
> Add container integration tests

- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/HealthGetHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RequestHandlersModule.java
- src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/HealthGetHandlerTest.java
> Add health check

- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/ListSavedRecordingsCommand.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/ListSavedRecordingsCommandTest.java
For each saved file it now lists the URLs as well as the name (using the same format as list).
> list-saved enhancements

- pom.xml
- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/UploadRecordingCommand.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/HttpServer.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/NetworkModule.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/WebServer.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/HealthGetHandler.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/UploadRecordingCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/HealthGetHandlerTest.java
See #189. Reopening after default branch rename.
> Replace Apache HttpClient with Vertx WebClient

- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RecordingGetHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingGetHandler.java
> Remove duplicate "low memory pressure" log message

- pom.xml
#207 
Not sure if we need to specify the exact version (1.3-3.1593114401) or if just 1.3 is enough. Both would work.
> specify version for base image

- COMMANDS.md
- pom.xml
- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/UploadRecordingCommand.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/UploadRecordingCommandTest.java
See #193. Reopening after default branch rename.
> Change `upload-url` Command to Assume Datasource URL from Environment Variable

- src/main/java/com/redhat/rhjmc/containerjfr/platform/PlatformModule.java
- src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/PlatformDetectionStrategy.java
> #226: Avoid Spotbugs warning

- src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/ReportGetHandlerTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingGetHandlerTest.java
> Remove Debug Messages Left by Accident

- pom.xml
- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/UploadRecordingCommand.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/UploadRecordingCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/CorsEnablingHandlerTest.java
- src/test/java/itest/GrafanaDatasourceIT.java
- src/test/java/itest/UploadRecordingIT.java
> Update Vert.x Version to Fix `upload-recording` Hangs

- src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/CommandsInternalModule.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/NetworkModule.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/TargetConnectionManager.java
- src/main/java/com/redhat/rhjmc/containerjfr/platform/ServiceRef.java
- src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/KubeApiPlatformClient.java
- src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/KubeApiPlatformStrategy.java
- src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/KubeEnvPlatformClient.java
- src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/KubeEnvPlatformStrategy.java
- src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/PlatformStrategyModule.java
- src/main/java/com/redhat/rhjmc/containerjfr/platform/openshift/OpenShiftPlatformClient.java
- src/main/java/com/redhat/rhjmc/containerjfr/platform/openshift/OpenShiftPlatformStrategy.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/RecordingOptionsCustomizerCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/ScanTargetsCommandTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/net/TargetConnectionManagerTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetsGetHandlerTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/platform/internal/KubeApiPlatformClientTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/platform/internal/KubeEnvPlatformClientTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/platform/openshift/OpenShiftPlatformClientTest.java
Use JFRConnectionToolkit utility method (which simply delegates to JMC implementation) rather than manually constructing JMXServiceURLs
> Use JFRConnectionToolkit.createServiceURL

- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RecordingUploadPostHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingUploadPostHandler.java
- src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RecordingUploadPostHandlerTest.java
- src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingUploadPostHandlerTest.java
> Use `UrlValidator` in Recording Upload Handlers

- HTTP_API.md
- README.md
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RecordingsPostHandler.java
> Add HTTP API Documentation

- HTTP_API.md
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingOptionsGetHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingOptionsPatchHandler.java
- src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingOptionsGetHandlerTest.java
> Use Object instead of String for TargetRecordingOptionsGetHandler

- src/main/java/com/redhat/rhjmc/containerjfr/net/NetworkModule.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/HealthGetHandler.java
- src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/HealthGetHandlerTest.java
> Grafana health/configuration bugfixes

- HTTP_API.md
- src/main/java/com/redhat/rhjmc/containerjfr/jmc/serialization/HyperlinkedSerializableRecordingDescriptor.java
- src/main/java/com/redhat/rhjmc/containerjfr/jmc/serialization/SerializableRecordingDescriptor.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/ApiVersion.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/HttpApiV2Module.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/TargetSnapshotPostHandler.java
- src/test/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/TargetSnapshotPostHandlerTest.java
Fixes #267
Encodes response as JSON with the same properties as customized recording creation
> Add Snapshot API V2 handler

- pom.xml
v1.0.0 (Beta 1) has been branched and tagged, so this sets up the main development branch for v2
> Update version to v2.0.0-SNAPSHOT

- pom.xml
> Update base image

- src/main/java/com/redhat/rhjmc/containerjfr/net/web/WebServer.java
Fixes #320
See also https://github.com/rh-jmc-team/container-jfr-web/pull/160
> Do not set exception payload as response status message

- repeated-unit-tests.sh
Intended to help test for intermittent test failures
Related to #132
> Add script for repeated unit testing

- HTTP_API.md
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/HttpApiV2Module.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/TargetEventsSearchGetHandler.java
- src/test/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/TargetEventsSearchGetHandlerTest.java
> Add `TargetEventsSearchGetHandler`

- pom.xml
Update jib plugin version
Fixes #327
> Update jib plugin version

- pom.xml
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RequestHandlersModule.java
See #371 - backport of same commits
> Remove guice

- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/AuthPostHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/ClientUrlGetHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/GrafanaDashboardUrlGetHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/GrafanaDatasourceUrlGetHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RecordingDeleteHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RecordingGetHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RecordingsGetHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetEventsGetHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingDeleteHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingOptionsPatchHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingsGetHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingsPostHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetSnapshotPostHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetTemplateGetHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetTemplatesGetHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetsGetHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TemplateDeleteHandler.java
- src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TemplatesPostHandler.java
> Add isAsync() to All Handlers (Backport)

- pom.xml
- src/assembly/dist.xml
This is a backport of #381. The change is identical.
> [v1] Optionally create distribution archive

- smoketest.sh
This is a backport of #379 . The patch applied cleanly.
> [V1] Explicitly bind container ports to host ports (#379)

- pom.xml
> [v1] Add separate property for Dagger compiler version

- pom.xml
> [v1] Update kubernetes/openshift-client to 4.12.0

- pom.xml
Backport of #409. No changes necessary.
> [v1] Update vulnerable dependencies, add dep-check profile

- src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/KubeApiPlatformClient.java
> Correct method signature for fabric8-client update

- pom.xml
- src/test/java/itest/ConnectToExternalTargetsIT.java
Backport of #514 with very minor adjustments to the setup/teardown.
> [v1] Correct InterleavedExternalTargetRequestsIT teardown

- .github/workflows/ci.yaml
> Run integration tests in CI builds

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Configuration for Release Drafter GitHub Action
> ci(release-drafter): config for Release Drafter

- .mergify.yml
post_check action is apparently a premium/paid feature, Remove it from the config
> ci(mergify): remove post_check action

- .github/workflows/semantic-pr.yml
* ci(semantic-pr): add config for semantic-pr
Configure Action to check that PR titles follow Conventional Commits format
* ci(release-drafter): format YAML array as list
> ci(semantic-pr): add config for semantic-pr action (#553)

- .github/workflows/dependent-issues.yml
https://github.com/marketplace/actions/dependent-issues
> ci(dependent-issues): add config for dependent-issues

- src/main/java/io/cryostat/platform/internal/KubeApiPlatformStrategy.java
- src/main/java/io/cryostat/platform/internal/OpenShiftPlatformStrategy.java
> fix(platform): lower log level for k8s namespace read failure

- HTTP_API.md
- src/main/java/io/cryostat/net/web/http/api/v2/RuleDeleteHandler.java
- src/main/java/io/cryostat/recordings/RecordingTargetHelper.java
- src/main/java/io/cryostat/rules/RuleProcessor.java
- src/test/java/io/cryostat/net/web/http/api/v2/RuleDeleteHandlerTest.java
- src/test/java/io/cryostat/rules/RuleProcessorTest.java
- src/test/java/itest/AutoRulesIT.java
> feat(rules): add cleanup query parameter

- pom.xml
> build(deps): update cryostat-core to 2.3.1

- pom.xml
> chore(version): bump project version to 2.1.0-SNAPSHOT

- src/main/java/io/cryostat/messaging/MessagingServer.java
Fixes #620 
Depends on https://github.com/cryostatio/cryostat-web/pull/277
> chore(notifications): convert notification categories to CamelCase

- run.sh
Fixes #751
This runs the container using the uid 0. In rootless podman, this results in the container's processes running under the uid of the original user on the host system, though within the container the processes believe themselves to be root. For development purposes and binding subdirectories to the container for development testing this is easy and convenient.
> fix(runsh): run container as original uid

- README.md
> docs(readme): document xpath requirement for run.sh/smoketest.sh

- devserver.sh
> fix(devserver): set probe template directory

- devserver.sh
- pom.xml
> fix(devserver): include assets in classpath

- pom.xml
- src/main/java/io/cryostat/net/web/http/api/v1/TemplateDeleteHandler.java
- src/main/java/io/cryostat/net/web/http/api/v1/TemplatesPostHandler.java
- src/test/java/io/cryostat/net/web/http/api/v1/TemplateDeleteHandlerTest.java
- src/test/java/io/cryostat/net/web/http/api/v1/TemplatesPostHandlerTest.java
- src/test/java/itest/TemplatePostDeleteIT.java
Fixes #829
Depends on cryostatio/cryostat-core#124
Depends on https://github.com/cryostatio/cryostat-web/pull/371
Depends on https://github.com/cryostatio/cryostat-web/issues/373
> fix(notifications): emit detailed template info

- src/main/java/io/cryostat/net/web/http/api/v2/RuleDeleteHandler.java
- src/main/java/io/cryostat/net/web/http/api/v2/RulesPostHandler.java
- src/test/java/io/cryostat/net/web/http/api/v2/RuleDeleteHandlerTest.java
- src/test/java/io/cryostat/net/web/http/api/v2/RulesPostHandlerTest.java
> feat(rules): emit notifications on create/delete

- HTTP_API.md
Fixes #840 
Adds docs for `TargetsPostHandler` and `TargetDeleteHandler`
> docs(targets): Add custom target docs

- src/main/java/io/cryostat/net/web/http/generic/CorsEnablingHandler.java
- src/test/java/io/cryostat/net/web/http/generic/CorsEnablingHandlerTest.java
> fix(cors): allow Content-Type headers

- src/main/java/io/cryostat/net/web/http/generic/HealthGetHandler.java
- src/test/java/io/cryostat/net/web/http/generic/HealthGetHandlerTest.java
Fixes #844
Depends on https://github.com/cryostatio/cryostat-web/pull/385
> fix(health): report service configured/available separately

- pom.xml
> build(deps): bump nimbus-jose-jwt to 9.16.1

- HTTP_API.md
> docs(http_api): update docs for GET /health

- graphql/environment-nodes-query-1.graphql
- graphql/environment-nodes-query-2.graphql
- graphql/environment-nodes-query-3.graphql
- graphql/environment-nodes-query-4.graphql
- graphql/environment-nodes-query-5.graphql
- graphql/environment-nodes-query-6.graphql
- graphql/environment-nodes-query-7.graphql
- src/main/java/io/cryostat/net/web/http/api/beta/graph/EnvironmentNodesFetcher.java
- src/main/java/io/cryostat/net/web/http/api/beta/graph/FilterInput.java
- src/main/java/io/cryostat/net/web/http/api/beta/graph/GraphModule.java
- src/main/resources/types.graphqls
Related to #820
Related to #846
> feat(graphql): apply conjunction of filters

- src/main/resources/queries.graphqls
- src/main/resources/types.graphqls
Fix botched force-push/rebase
See #857
> fix(graphql): name-based filtering on more queries

- devserver.sh
> chore(devserver): enable Basic auth by default

- src/main/java/io/cryostat/net/web/http/api/beta/graph/GraphQLGetHandler.java
- src/main/java/io/cryostat/net/web/http/api/beta/graph/GraphQLPostHandler.java
> fix(graphql): reduce required resourceaction permissions

- pom.xml
> chore(core): update core to 2.9.1

- src/test/java/itest/TemplatePostDeleteIT.java
- src/test/resources/TemplateToSanitize.jfc
> test(template): add itest for event template name sanitization

- pom.xml
> build(base): update base image to 2.1.0

- pom.xml
> build(version): bump version to 2.2.0-SNAPSHOT

- pom.xml
> build(version): set version for 2.1.0 release

- pom.xml
> build(version): bump version to 2.1.1-SNAPSHOT

- .github/workflows/ci.yaml
- pom.xml
> build(oci): transform image tag to lower case

- pom.xml
- smoketest.sh
> chore(smoketest): always pull peripheral images

- README.md
- build-images.sh
- devserver.sh
- pom.xml
- repeated-unit-tests.bash
- src/test/java/itest/ClientAssetsIT.java
> build(minimal): rename to 'headless'

- pom.xml
> build(version): set version to 2.1.1 for release

- pom.xml
> build(version): bump version to 2.1.2-SNAPSHOT

- .github/workflows/ci.yaml
- pom.xml
> ci(jdk): build-deps with JDK17

- .github/workflows/ci.yaml
- .gitmodules
> ci(submodule): submodule tracks branch

- repeated-integration-tests.bash
- src/main/java/io/cryostat/rules/Rule.java
- src/main/java/io/cryostat/rules/RuleProcessor.java
- src/test/java/io/cryostat/MockVertx.java
- src/test/java/io/cryostat/rules/RuleProcessorTest.java
- src/test/java/io/cryostat/rules/RuleTest.java
- src/test/java/itest/AutoRulesIT.java
Fixes #1014
Depends on https://github.com/cryostatio/cryostat-web/pull/476
See issue and `-web` PR for more description.
> feat(rules): implement initialDelay

- src/main/java/io/cryostat/Cryostat.java
> feat(version): log application version at startup

- README.md
Related #667 
I found some integration test tips in my personal notes and thought it might be helpful for new contributors.
> docs(test): explain how to run one itest

- HTTP_API.md
- src/main/java/io/cryostat/net/web/http/api/v2/CredentialDeleteHandler.java
- src/main/java/io/cryostat/net/web/http/api/v2/CredentialsGetHandler.java
- src/main/java/io/cryostat/net/web/http/api/v2/CredentialsPostHandler.java
- src/test/java/io/cryostat/net/web/http/api/v2/CredentialDeleteHandlerTest.java
- src/test/java/io/cryostat/net/web/http/api/v2/CredentialsGetHandlerTest.java
- src/test/java/io/cryostat/net/web/http/api/v2/CredentialsPostHandlerTest.java
- src/test/java/itest/CredentialsV2_2IT.java
Related https://github.com/cryostatio/cryostat-web/issues/466
Depends on https://github.com/cryostatio/cryostat-web/pull/495
> feat(credentials): add a count of the matched targets to the CredentialsGetHandler response

- src/main/java/io/cryostat/net/web/http/api/v2/TargetsPostHandler.java
- src/main/java/io/cryostat/platform/ServiceRef.java
- src/main/java/io/cryostat/platform/internal/CustomTargetPlatformClient.java
- src/main/java/io/cryostat/platform/internal/DefaultPlatformClient.java
- src/main/java/io/cryostat/platform/internal/KubeApiPlatformClient.java
- src/main/java/io/cryostat/platform/internal/KubeEnvPlatformClient.java
- src/main/java/io/cryostat/platform/internal/KubeEnvPlatformStrategy.java
- src/main/java/io/cryostat/platform/internal/PlatformStrategyModule.java
- src/test/java/io/cryostat/net/web/http/api/v2/TargetsPostHandlerTest.java
- src/test/java/io/cryostat/platform/internal/DefaultPlatformClientTest.java
- src/test/java/io/cryostat/platform/internal/KubeApiPlatformClientTest.java
- src/test/java/io/cryostat/platform/internal/KubeEnvPlatformClientTest.java
- src/test/java/itest/CredentialsIT.java
- src/test/java/itest/CredentialsV2_2IT.java
- src/test/java/itest/DiscoveryIT.java
- src/test/java/itest/GraphQLIT.java
- src/test/java/itest/InterleavedExternalTargetRequestsIT.java
> feat(discovery): annotate targets with Realm belonged to

- src/test/java/io/cryostat/net/openshift/OpenShiftAuthManagerTest.java
- src/test/java/io/cryostat/platform/internal/KubeApiPlatformClientTest.java
> test(k8s): remove TRYKUBECONFIG system property

- docs/DISCOVERY_PLUGINS.md
- docs/GRAPHQL.md
- docs/HTTP_API.md
> docs(discovery): add DISCOVERY_PLUGINS.md

- docs/HTTP_API.md
- docs(HTTP_API): update GraphQL Authorization description
- docs(HTTP_API): document JWT asset download handlers
Fixes #995
> docs(HTTP_API): document JWT asset download endpoints

- smoketest.sh
> test(smoketest): publish different HTTP ports for each fib demo app

- CONTRIBUTING.md
- README.md
Related to #580 
Added some simple steps on how to contribute to Cryostat projects.
> docs(contributing): add guides on how to contribute

- pom.xml
> build(pom): update version to next iteration snapshot

- pom.xml
> build(pom): set version to 2.2.0

- .mergify.yml
- pom.xml
> build(base): update base image

- src/main/java/io/cryostat/recordings/JvmIdHelper.java
- src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
- src/main/java/io/cryostat/recordings/RecordingMetadataManager.java
Fixes #1121 
Depends on #1120
Not sure if this warrants a backport or not.
> fix(archives): fix various archives and metadata related issues

- .mergify.yml
> ci(mergify): dismiss reviews when PRs update

- .github/workflows/ci.yaml
> fix(ci): fix broken ci job for pushing to quay

- pom.xml
> build(postgres): bump postgres to 42.5, exclude checker-qual

- src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
- src/main/java/io/cryostat/recordings/RecordingMetadataManager.java
> fix(metadata): handle metadata correctly when archives are lost

- pom.xml
> build(base-image): use ubi latest tag

- .github/workflows/pr-ci.yml
> ci(ghcr): update secret name

- .github/workflows/pr-ci.yml
Related to #1133
Related to #1173
> ci(checkout): fix fork name checkout

- .github/workflows/image-cleanup.yml
> ci(image): use pull_request_target event for cleanup for access to secrets

- README.md
- docs/DISCOVERY_PLUGINS.md
- docs/HTTP_API.md
> docs(md): link docs to each other

- src/main/java/io/cryostat/recordings/RecordingTargetHelper.java
- src/test/java/itest/GraphQLIT.java
> fix(metadata): fix incorrect labels sent to notification web-socket after target recording creation

- .github/CODEOWNERS
- .github/dependabot.yml
- .mergify.yml
- pom.xml
- src/container/Dockerfile
> ci(dependabot): create dependabot update config

- pom.xml
Related to #1225
Replaces #1232
> build(deps): upgrade bcprov from jdk15on to jdk18on

- smoketest.sh
> test(smoketest): update sample app versions

- pom.xml
> chore(pom): set version to 2.2.0 (final)

- pom.xml
> chore(pom): set version to 2.2.1-SNAPSHOT

- .github/dependabot.yml
> chore(dependabot): increase PR limit to 10

- src/main/java/io/cryostat/net/web/http/api/v2/ProbeTemplateUploadHandler.java
- src/test/java/io/cryostat/net/web/http/api/v2/ProbeTemplateUploadHandlerTest.java
Fixes #1272 
Related https://github.com/cryostatio/cryostat-web/issues/586
> fix(probes): fix notification handling of probe template uploads

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/labeler.yml
- .github/pull_request_template.md
- .github/workflows/check-labels.yml
- .github/workflows/labeler.yml
- .github/workflows/pr-ci.yml
Fixes #1268 
**From my fork:**
Test PR: https://github.com/maxcao13/cryostat/compare/main...maxcao13:cryostat:ci-testing
Test Issues: https://github.com/maxcao13/cryostat-web/issues/new/choose
> feat(github): add pr and issue templates

- pom.xml
Related to https://github.com/cryostatio/cryostat-web/pull/715
> build(deps): update frontend build node and yarn versions

- src/test/java/itest/InterleavedExternalTargetRequestsIT.java
Fixes: #1262 
This change allows the InterleavedExternalTargetRequsestsIT itest containers to need JMX auth and mark the itest as a known failure.
This fix is needed so that we later use it to test whether requests that require JMX_AUTH and make the use of jvmIds are properly are correctly handled.
1. Checkout pr
2. Run `bash repeated-integration-tests.bash InterleavedExternalTargetRequestsIT`
3. Notice tests pass, but comment note there is a FIXME comment in the testInterleavedRequests annotated test case
> chore(itest): fix InterleavedExternalTargetRequsestsIT itest containers to need JMX auth and mark it as known failure

- src/main/java/io/cryostat/net/web/http/api/v2/RuleDeleteHandler.java
- src/main/java/io/cryostat/rules/RuleProcessor.java
- src/test/java/io/cryostat/net/web/http/api/v2/RuleDeleteHandlerTest.java
- src/test/java/itest/AutoRulesCleanupIT.java
- src/test/java/itest/AutoRulesIT.java
> fix(rules): handling for initialDelay==0 and cleanup

- src/main/java/io/cryostat/net/web/http/api/v2/RulePatchHandler.java
- src/test/java/io/cryostat/net/web/http/api/v2/RulePatchHandlerTest.java
- src/test/java/itest/AutoRulesCleanupIT.java
Fixes: #1283 
Allowed `PATCH /api/v2/rules` to have `clean` query parameter that specifies whether to clean up resources, similar to deleting a rule.
Note that `clean` query param would only considered if rule is disabled on patch.
When a rule is enabled it triggers the creation of a new active recording. When the user disables the rule, they should have the choice to leave those recordings running or to automatically stop them all.
1. Start smoketest
```bash
$ CRYOSTAT_IMAGE=ghcr.io/cryostatio/cryostat:pr-1289-<some-hash> sh smoketest.sh
```
2. Create an enabled rule.
```bash
echo '{"name":"myrule","description":"","matchExpression":"target.alias == 'a_target'","eventSpecifier":"template=Profiling,type=TARGET","archivalPeriodSeconds":0,"init …
```
> feat(rules): allow cleanup on disabling rules

- pom.xml
> build(version): set version to 2.2.1

- pom.xml
Related to: https://github.com/cryostatio/cryostat/issues/1302
> build(version): bump version to 2.2.2-SNAPSHOT

- smoketest.sh
Related to https://github.com/cryostatio/cryostat-agent/issues/49
Related to https://github.com/cryostatio/cryostat-agent/issues/27
> test(smoketest): update agents config

- .mergify.yml
- pom.xml
> build(config): update pom and mergify for 2.3 release

- .gitmodules
> ci(submodule): update submodule track branch

- src/main/java/io/cryostat/net/web/http/api/beta/RecordingsFromIdPostHandler.java
- src/main/java/io/cryostat/net/web/http/api/v1/RecordingsPostHandler.java
- src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
- src/main/java/io/cryostat/recordings/RecordingNotFoundException.java
- src/main/java/io/cryostat/recordings/RecordingTargetHelper.java
- src/test/java/io/cryostat/net/reports/SubprocessReportGeneratorTest.java
- src/test/java/io/cryostat/net/web/http/api/beta/RecordingsFromIdPostHandlerTest.java
- src/test/java/io/cryostat/net/web/http/api/v1/RecordingsPostHandlerTest.java
- src/test/java/io/cryostat/recordings/RecordingTargetHelperTest.java
Fixes: #1484 
Fixes some error/warning/exceptions strings in the -main repo.
> chore(strings): cryostat 2.3  user-facing string fixes 

- .github/workflows/ci-jobs.yml
- pom.xml
> ci(multiarch): check for container startup and make qemu available for itests

- .github/workflows/push-ci.yml
Related to #1557
See https://github.com/cryostatio/cryostat/actions/runs/5283355518/jobs/9559772377#step:3:28
> ci(tags): set env vars for container tags

- pom.xml
- src/main/java/io/cryostat/net/web/http/api/v2/ProbeTemplateUploadHandler.java
- src/main/java/io/cryostat/net/web/http/api/v2/TargetProbePostHandler.java
- src/test/java/io/cryostat/net/web/http/api/v2/ProbeTemplateUploadHandlerTest.java
- src/test/java/io/cryostat/net/web/http/api/v2/TargetProbePostHandlerTest.java
Depends on https://github.com/cryostatio/cryostat-core/pull/241
Related to https://github.com/cryostatio/cryostat-core/issues/239
- Update to use the latest core utilities.
- Remove unused field in notifications (i.e. previously it holds the temporary uploaded filepath).
> chore(agent): update agent template utilities

- .github/workflows/ci-build-image.yml
- repeated-integration-tests.bash
- run.sh
Related to #1569
Related to #1572
> test(itest): ensure required mvn plugin is downloaded

- .github/workflows/ci-build-image.yml
- pom.xml
- repeated-integration-tests.bash
> test(itest): allow explicit override of itest image tag

- README.md
- src/main/java/io/cryostat/platform/internal/DockerPlatformClient.java
> docs(README): update README to manually download mvn help plugin

- .github/workflows/push-ci.yml
> ci(push): fix env var typo

- run.sh
- smoketest.sh
Fixes: #1629
See also https://github.com/cryostatio/cryostat-reports/pull/136 https://github.com/cryostatio/jfr-datasource/pull/213
1. Ask me for a sample 10MB JFR file, or collect your own
2. Run `smoketest.sh` with test image
3. Upload 10MB JFR file into Archives
4. Check that `View Report` and `View in Grafana` both work
5. Click around UI and ensure other functionalities generally work as expected
6. Bonus: repeat this with a larger sample JFR file. The next larger file I have is 50MB and that's too large for the resource limits applied here.
> test(smoketest): tinker with resource limits

- smoketest.sh
Depends on https://github.com/cryostatio/cryostat-agent/pull/203
Related to https://github.com/cryostatio/cryostat-agent/issues/166
> chore(smoketest): remove Agent prefer-jmx env var

- .gitmodules
Related to #1695
See https://github.com/cryostatio/cryostat-web/pull/1133
> chore(release): point web-client submodule to 2.4 release branch

- .mergify.yml
- pom.xml
> chore(release): bump versions for 2.4 release branch point

- .github/workflows/push-ci.yml
> chore(ci): push-ci updates

- .github/workflows/ci-build-image.yml
- .github/workflows/ci-code-analysis.yml
- .github/workflows/integrated-test.yml
- .github/workflows/pr-ci.yml
> fix(CI): fix workflow bug

- pom.xml
> chore(release): set version to 2.4.0

- .github/workflows/push-ci.yml
Fixes: https://github.com/cryostatio/cryostat/issues/1818
> ci(release): match all tags for push-ci workflow

- .gitmodules
Fixes: #<issue number>
2. *...*
> chore(web-client): use cryostat-web-2.x

- pom.xml
- src/main/java/io/cryostat/recordings/RecordingsModule.java
> chore(core): update -core version, correct constructor invocation

- repeated-integration-tests.bash
See https://github.com/cryostatio/cryostat-core/pull/332
> chore(itest): remove mvn -o flag

- pom.xml
See https://github.com/cryostatio/cryostat/pull/1905
2. *...*
> build(deps): bump bouncycastle to 1.76

- README.md
> docs(readme): update to point visitors to new repo
