src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/CommandsInternalModule.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/PortScanCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/ScanTargetsCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/sys/Environment.java

Kubernetes/OpenShift automatically populates certain environment variables in containers to help detect local services those containers may want to communicate with [1]. This PR uses those environment variables to find services that are listening on TCP port 9091. If no such environment variables are found, it will fall back to using the port scanning approach.
Example from robotcontroller pod [2]:
```bash
$ env | grep ROBOTMAKER | sort
ROBOTMAKER_PORT=tcp://172.30.95.111:9091
ROBOTMAKER_PORT_8080_TCP=tcp://172.30.95.111:8080
ROBOTMAKER_PORT_8080_TCP_ADDR=172.30.95.111
ROBOTMAKER_PORT_8080_TCP_PORT=8080
ROBOTMAKER_PORT_8080_TCP_PROTO=tcp
ROBOTMAKER_PORT_8778_TCP=tcp://172.30.95.111:8778
ROBOTMAKER_PORT_8778_TCP_ADDR=172.30.95.111
ROBOTMAKER_PORT_8778_TCP_PORT=8778 …
```

Use Kubernetes environment variables to find IP addresses

---

src/main/java/com/redhat/rhjmc/containerjfr/tui/tcp/SocketClientReaderWriter.java
src/test/java/com/redhat/rhjmc/containerjfr/net/NetworkResolverTest.java
src/test/java/com/redhat/rhjmc/containerjfr/tui/tcp/SocketClientReaderWriterTest.java

This PR improves #6.
For `NetworkResolver::testConnection`, I'm unsure how to mock the internal Socket and InetSocketAddress. The function is therefore untested.
As for the WebServer, it's better to refactor it, making it easier to adapts arbitrary HTTP server implementations. I'm currently working on this.

Improve tests for SocketClientReaderWriter and NetworkResolver

---

README.md
build.gradle

Reduce the JVM flag set to the minimal

---

build.gradle
src/main/java/com/redhat/rhjmc/containerjfr/net/WebServer.java

CORS headers are no longer necessary since container-jfr is also the
webserver for container-jfr-web

Remove CORS headers from WebServer responses

---

src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/ConnectCommandTest.java

Strings printed by ConnectCommand on invalid input were changed but the
tests not modified to match.
Fixes #45

Correct unit test assertions

---

build.gradle
src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/KubeApiPlatformClient.java

While testing with OpenShift 4 and CodeReady Containers, I ran into a situation where a Kubernetes service was detected using the KubeApi discovery strategy, and this service had a null list of service ports. This caused an NPE on target discovery, since the streaming used to transform the API listing results into a list of ServiceRefs assumed non-null service port lists. For easier debugging of such potential issues in the future I've also added the trace-level logging of discovered services before any processing is performed.

Avoid NPE on nullable ServicePorts list

---

src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/SaveRecordingCommandTest.java

Correct unit tests for save command updated filenames

---

src/main/java/com/redhat/rhjmc/containerjfr/net/web/WebServer.java

When SSL is enabled, use HTTPS protocol for recording download and
reports links. Fallback to plain HTTP if SSL is not enabled.
Fixes #75

Report download and reports links with appropriate protocol

---

src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/UploadRecordingCommand.java

HttpClient already correctly closes the stream, however this adds
explicit closure of the stream for more readily apparent correct
handling of the stream

Explicitly close recording stream after upload

---

src/main/java/com/redhat/rhjmc/containerjfr/net/web/WebModule.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/WebServer.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/WebServerTest.java

This patch allows JFR recordings to be (re-)uploaded to container-jfr from clients. The implement expects a recording with its name in form of *`<target-name>_<recording_name>_<timestamp>[.\d+].jfr`* and rejects otherwise.
**RFC**: Looking at the JMC API, I was unable to find a way which just simply validates a recording. Therefore, I called `JfrLoaderToolkit.loadEvents()` to verify the file uploaded is a valid JFR recording. This could lead to degraded performance.  
Closes rh-jmc-team#55. Blocked by rh-jmc-team/container-jfr-web#24 (needs sub-module commit hash).

Allow re-uploading recordings from clients

---

src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/StartRecordingCommand.java

Adjusts the comment to be accurate. Another possibility is to remove these kinds of comments and make the variable names more verbose, but they can be useful, e.g. the events list sample. I don't have a strong opinion either way.

Fix code comment in StartRecordingCommand

---

README.md
build-images.sh
build.gradle
run.sh
src/main/java/com/redhat/rhjmc/containerjfr/ContainerJfr.java

Remove build-time CONTAINER_JFR_DEBUG env var so that only standard and
minimal images are built. -debug images previously were mostly
distinguished simply by the logging level intrinsically set at startup
by checking a static system property. This is replaced with a runtime
checked configurable CONTAINER_JFR_LOG_LEVEL environment variable,
allowing standard and minimal images to be used for debugging purposes
by simply restarting the container with the LOG_LEVEL set appropriately.
Fixes #88

Remove -debug images in favour of configurable logging

---

src/main/java/com/redhat/rhjmc/containerjfr/net/HttpServer.java
src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/MessagingServer.java
src/test/java/com/redhat/rhjmc/containerjfr/tui/ws/MessagingServerTest.java

Expect tokens via websocket subprotocol

---

src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/UploadRecordingCommand.java
src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/UploadRecordingCommandTest.java

These commits add tests for the upload-recording command, fix a bug where in-memory recordings were closed after upload, fix a validation failure output message format bug, and add buffering to disk reads for better upload speeds when uploading archived recordings.

upload-recording command enhancements and fixes

---

README.md
src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/MessagingServer.java
src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/WsClientReaderWriter.java
src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/WsModule.java
src/test/java/com/redhat/rhjmc/containerjfr/tui/ws/MessagingServerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/tui/ws/WsClientReaderWriterTest.java

Rewrite MessagingServer handling of concurrent WebSocket connections to
reduce latency, avoid polling, and fix a concurrent modification
exception bug. This also adds logic for limiting the maximum number of
WebSocket connections that can be simultaneously open, which is
configurable.
Fixes #114

Better WebSocket concurrency handling

---

build.gradle
src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/CommandRegistryImplTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/BasicAuthManagerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/tui/ws/WsCommandExecutorTest.java

This upgrades test-only library versions to the latest, and makes use of a JUnit 5 feature I stumbled across which cleans up a couple of tests I wrote recently. This should be pretty safe since it's testing only, and all tests continue passing on my machine.

Test libs upgrade

---

build.gradle

Based on top of #120 , this just configures the jib plugin to use podman for building images, rather than docker.

Podman build

---

src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/CommandExceptionResponseMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/CommandMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/CommandUnavailableMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/FailureResponseMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/InvalidCommandArgumentsResponseMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/InvalidCommandResponseMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/MalformedMessageResponseMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/ResponseMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/SuccessResponseMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/tui/ws/WsCommandExecutor.java
src/test/java/com/redhat/rhjmc/containerjfr/tui/ws/MessagingServerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/tui/ws/WsCommandExecutorTest.java

id is copied from command request messages into the corresponding
response (assuming that the command message was well-formed and
understood) so that clients can provide some unique ID on request, and
identify the correct associated response in the interleaved broadcasts
from the server
Fixes #116

Add "id" field to command and response messages

---

README.md

Addresses https://github.com/rh-jmc-team/container-jfr/issues/108
It's a tiny bit weird since node bundles a specific version of npm.

Update build requirements in README.md

---

README.md
src/main/java/com/redhat/rhjmc/containerjfr/net/NetworkModule.java
src/main/java/com/redhat/rhjmc/containerjfr/platform/PlatformModule.java

This PR:
- makes container-jfr exit early if the user has specified a non-existent AuthManager, rather than falling back to automatic detection
- adds similar environment variable-based configurability to PlatformDetectionStrategy , which will also exit early if a non-existent strategy is configured
PlatformDetectionStrategies provide the PlatformClients, which are what provide the default AuthManager implementations for their respective platforms, so if a user specifies a Platform without specifying an AuthManager, then (assuming the Platform is successfully configured) they will still get the default AuthManager for that platform. Both variables can also be set and to normally unrelated values, ex. KubeEnv platform with Basic auth.

Configurable platform

---

.gitignore
README.md
pom.xml

The "frontend" plugin is a nice improvement over directly using the exec plugin
to invoke "npm" for building the web-client. For one thing, the intent is more
clear. But the real advantage is that the frontend plugin will automatically
download and install Node and npm binaries into the bin directory, removing
the need for developers (or CI servers) to install Node and npm in order to
build container-jfr. This also keeps versions consistent and makes builds more
reproducible. These additional binaries will be removed on `mvn clean`, and
are also cached in `.m2`, so the build time impact is very minimal after the first
run.

Use frontend plugin to build web-client

---

pom.xml

Exclude Dagger module classes, which don't contain any useful testable
code, as well as Dagger generated classes for dependency injection

Add JaCoCo configuration to exclude Dagger classes

---

pom.xml

Depends on: https://github.com/rh-jmc-team/container-jfr-core/pull/34

Use container-jfr-core 0.11.0

---

pom.xml

Replaces the gcr.io distroless base image with the new UBI8 OpenJDK base image.
https://access.redhat.com/errata/RHEA-2020:2018
0.18.0 is a pair of images built from current `master`, and 0.19.0 is from this PR:
```
quay.io/rh-jmc-team/container-jfr            0.19.0           7dcb84b88ca5   6 minutes ago    614 MB
quay.io/rh-jmc-team/container-jfr            latest           7dcb84b88ca5   6 minutes ago    614 MB
quay.io/rh-jmc-team/container-jfr            0.19.0-minimal   268b254e9d1f   8 minutes ago    600 MB
quay.io/rh-jmc-team/container-jfr            0.18.0           db729e3bdc57   10 minutes ago   286 MB
quay.io/rh-jmc-team/container-jfr            0.18.0-minimal   533720d7fe38   11 minutes ago   272 MB
```
There's obviously quite a significant image size increase from this …

Use Red Hat UBI8 OpenJDK container base image

---

src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/ListCommand.java
src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/ListCommandTest.java

Fixes #160 
The code for the test has a lot duplicated with the test for the serializable list command, `shouldReturnListOutput()`, but I'm not sure if there's a good way to put it all into a method or if this would even be worth it, since it's just two tests.

Add download URL and report URL to `list` command in interactive mode

---

src/main/java/com/redhat/rhjmc/containerjfr/MainModule.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/DeleteSavedRecordingCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/ListSavedRecordingsCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/SaveRecordingCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/UploadRecordingCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RecordingGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RecordingsPostHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/ReportGetHandler.java

Using previous gcr.io base image, a relative path to the archived
recordings directory happened to work. Since switching base images to
UBI8 this assumption no longer holds, so the path is explicitly made
absolute.
No new tests are included, but it's worth noting that the integration tests in #164 do actually catch this regression. However, that PR is still outstanding and was not tested against the base image change.
Fixes #171

Set expected archived recordings filepath to absolute path

---

README.md
src/main/java/com/redhat/rhjmc/containerjfr/MainModule.java

Adds environment variable `ARCHIVE_PATH` which specifies path when saving flight recordings locally. If not set, the default path remains `/flightrecordings`.

Archive path should be configurable

---

src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/AbstractRecordingCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/ListCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/ListEventTemplatesCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/ListEventTypesCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/ListSavedRecordingsCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/ScanTargetsCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/UploadRecordingCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RecordingsGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RequestHandlersModule.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetEventsGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingsGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetTemplatesGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetsGetHandler.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RecordingsGetHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetEventsGetHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingsGetHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetTemplatesGetHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetsGetHandlerTest.java

This adds HTTP API handlers for various paths with a GET verb, mirroring current WebSocket APIs (`scan-targets`, `list`, `list-saved`, `list-templates`, `list-event-types`). Those WebSocket APIs should be deprecated, although there is currently no defined way to mark them as such in the API responses. This helps bring the API closer to a typical HTTP REST design, moving further away from the original interactive execution mode that was initially implemented and is currently mirrored in the WebSocket command channel API.

Add HTTP API handlers for various "lists"

---

src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/ListCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/ListSavedRecordingsCommand.java
src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/ListCommandTest.java
src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/ListSavedRecordingsCommandTest.java

By strictly enforcing the order in which they print it seems to not fail the tests anymore.

Fix intermittent print URL bug

---

src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/UploadRecordingCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/HealthGetHandler.java
src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/UploadRecordingCommandTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/HealthGetHandlerTest.java

WebClient /health request handler hang fix

---

README.md
pom.xml
run.sh
src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/AbstractRecordingCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/ListEventTemplatesCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/net/NetworkModule.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/HttpMimeType.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/WebServer.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/CorsEnablingHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RequestHandlersModule.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetTemplateGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TemplateDeleteHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TemplatesBodyHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TemplatesPostHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/templates/TemplatesModule.java
src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/AbstractRecordingCommandTest.java
src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/ListEventTemplatesCommandTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/CorsEnablingHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetTemplateGetHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetTemplatesGetHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TemplateDeleteHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TemplatesPostHandlerTest.java

Fixes #143
See also https://github.com/rh-jmc-team/container-jfr-core/pull/40 - -core dependency changes
This adds HTTP API endpoints to list available event templates, retrieve XML definitions of specific templates, and to add new templates (by XML file POST upload) to container-jfr's local filesystem storage. These templates can then be used when creating new flight recordings using the pre-existing `template=Foo` syntax.

Custom Templates

---

README.md
demos/print_help

Fixes #211.
In the README, I also removed a mention of `connect localhost`.
Also I removed the, "all three execution modes described above" part, since it looks like [the description](https://github.com/rh-jmc-team/container-jfr/commit/9719664f51ce49d9d080dee943b46c7e9d0c1529#diff-04c6e90faac2675aa89e2176d2eec7d8R39) it's referring to doesn't exist in our current README anymore.
Also I added a backslash to a `1.` at the end of a sentence, so it isn't interpreted as the start of a numbered list.

Remove `demos/`

---

src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/UploadRecordingCommand.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/WebServer.java
src/main/java/com/redhat/rhjmc/containerjfr/util/HttpStatusCodeIdentifier.java
src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/UploadRecordingCommandTest.java
src/test/java/com/redhat/rhjmc/containerjfr/util/HttpStatusCodeIdentifierTest.java

Fixes #218.
This PR adds a check to make sure that the HTTP response's status code is `200` and that its status message and body are not `null`. If the `200` requirement is too strict, we could also change it to `200 <= x < 300`.
In addition to fixing the NPE issue, because of the status code check, `upload-recording` now also correctly identifies many invalid uploads to existing but non-jfr-datasource servers, such as `http://google.com`, which previously would have just returned a standard `MapResponse`.
With the datasource URL pointing to the running CJFR instance, the response from an `upload-recording` call now looks like this:
`{"id":null,"commandName":"upload-recording","status":-2,"payload":"Invalid response from server; datasource URL may be incorrect, or server may not be …

Add Checks for `upload-recording` ResponseMessage

---

README.md

Podman version 2.0+ seems to be needed for `run.sh` to work with its separate container creation and container run steps, which is useful for testing and development as it allows a nice and simple way to run other containers within the same pod, so that the container-jfr instance has other targets to connect to than itself (ex. andrewazores/vertx-fib-demo). For general image creation purposes (`mvn package`), older Podman versions should suffice, but I'm not sure it's worth explaining this distinction.

Specify required podman version

---

src/main/java/com/redhat/rhjmc/containerjfr/net/HttpServer.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/AbstractAuthenticatedRequestHandler.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/AbstractAuthenticatedRequestHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetEventsGetHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingDeleteHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingGetHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingPatchHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingUploadPostHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingsGetHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingsPostHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetReportGetHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetSnapshotPostHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetTemplateGetHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetTemplatesGetHandlerTest.java

This adds a bit of logic to the `AbstractAuthenticatedRequestHandler` to fill in the implementation of retrieving target RJMX credentials from HTTP headers. This was previously added as a stub which always used null credentials in an earlier PR. Now, if credentials are provided using the `Proxy-Authorization` header (maybe this isn't the most appropriate header to use), they are checked for validity and passed along down the line when establishing the connection to the target JVM.

RJMX authorization via HTTP header

---

src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/AbstractAuthenticatedRequestHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/CorsEnablingHandler.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/AbstractAuthenticatedRequestHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/CorsEnablingHandlerTest.java

Browsers do not send Proxy-Authorization header as expected, so rename
the header to X-JMX-Authorization to allow browser clients to provide
JMX auth credentials

Change JMX auth header name

---

pom.xml
src/main/extras/app/entrypoint.sh
src/main/extras/app/resources/jmxremote.access

Fixes #221 
Remove jmxremote.access, and generate it with the correct username in entrypoint.sh

Fix username problem for RJMX credentials

---

src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/AbstractAuthenticatedRequestHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/CorsEnablingHandler.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/AbstractAuthenticatedRequestHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/CorsEnablingHandlerTest.java

Related to #5
Server's "call" is changed to X-JMX-Authenticate, while corresponding
client response is left as "X-JMX-Authorization". This matches the HTTP
WWW-Authenticate/Authorization headers.
This header will be used by clients to discover the authentication scheme expected by the ContainerJFR instance. The only supported scheme at this time is `Basic`.

Change call/response JMX auth header

---

pom.xml
smoketest.sh

This fixes integration tests, which recently (in #243) broke. The cause of the failure is that the SSL portions of `entrypoint.sh` cause the real container start-up time to be increased, and without this PR, the integration test suite attempts to run tests immediately after starting the container. The container is in fact running, but the JVM has not yet started and begun listening for incoming connections, and so the integration test requests fail. The solution presented here is to simply add an exec-plugin configuration that does a slow loop waiting for the JVM to be ready before allowing the integration tests to proceed.
There are still rare instances where I observe the tests failing with `Connection Refused` errors, and in these cases I can see that the JVM is running and apparently …

Fix itests

---

src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RecordingUploadPostHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingUploadPostHandler.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/RecordingUploadPostHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/TargetRecordingUploadPostHandlerTest.java

Fixes #237.
Mostly just the same implementation as #224. I had to remove the response body from the exception message though, since it could contain newlines or other characters not allowed in a status message.
Tests are again just the `shouldDoPost()` test with a modification to the `Answer` and verifications at the end.

Add Check for Upload Handler POST Response

---

run.sh
smoketest.sh

Set port mapping at pod creation time

---

src/test/java/itest/BasicCommandChannelIT.java
src/test/java/itest/ITestBase.java
src/test/java/itest/RecordingWorkflowIT.java
src/test/java/itest/UploadRecordingIT.java

- Replace Command Channel calls with HTTP equivalents
- Refactor to extract utility method
Avoids use of deprecated WebSocket/Command Channel APIs, replacing with HTTP API equivalents wherever applicable

ITests use HTTP API where applicable

---

src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/AbstractAuthenticatedRequestHandler.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/handlers/AbstractAuthenticatedRequestHandlerTest.java

Fixes #270
See also rh-jmc-team/container-jfr-web#129

Use status code 427 instead of 407

---

pom.xml

See https://github.com/rh-jmc-team/container-jfr-web/pull/148 . With both patches applied, `mvn package` and `mvn clean package` should be notably faster and still result in a functional image due to a shorter time spent cleaning, checking, and rebuilding the frontend dependencies.

Update frontend-plugin for yarn

---

src/main/extras/app/entrypoint.sh
src/main/java/com/redhat/rhjmc/containerjfr/net/security/CertificateValidator.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/CertificatePostBodyHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/CertificatePostHandler.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/CertificatePostHandlerTest.java

Fixes #273 
A few things that may need attention:
* The status code 409 for certificate already exists (not sure if that is the most appropriate)
* I am not sure if the fact that a restart of the JVM is needed should be communicated anywhere (I guess it would be added to the docs and in the future web UI)
* When uploading the certificate, it is in a form with the name cert (it checks for this). This might not be the best name or even the most appropriate way to send it. (current curl command is `curl -X POST -F cert=@PATH/vertx-fib-demo.cer -vk https://localhost:8181/api/v2/certificates`)

Upload certificate

---

src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/generic/CorsEnablingHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/generic/TimeoutHandler.java

Wraps around Vert.x TimeoutHandler implementation to write a 500 response if a request is not completed by another handler within 15 seconds
Fixes #288
Easy ways to test: modify the `15_000` constant in the patch to a shorter period, like `500`, and then do some operation like generating a report. Or, build a minimal image and try to request a web-client asset.

Add timeouthandler

---

HTTP_API.md
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/AbstractAuthenticatedRequestHandler.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/http/AbstractAuthenticatedRequestHandlerTest.java

Respond with status code 502 and message "Target SSL Untrusted" when attempting a target connection fails for what appears to be an SSL trust issue
Fixes #307
This can be tested by running `smoketest.sh`. Normally, the `truststore` directory should contain the `vertx-fib-demo.cer` copied from that project's repo, and this allows ContainerJFR to connect to the demo application when running in the smoketest. By removing the `.cer` from the truststore (ex. simply `mv truststore/vertx-fib-demo.cer .`) and re-running `sh smoketest.sh` an SSL trust failure can be easily triggered. Before this patch the response is a standard HTTP 404. After this patch the response is a 502 with the custom message "Target SSL Untrusted". This can be seen in the web-client notifications as well as with standard …

Respond 502 when target SSL untrusted

---

HTTP_API.md

Remove 427 Status Code from Handlers that don't Connect to JVM

---

src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/KubeApiPlatformClient.java
src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/KubeApiPlatformStrategy.java
src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/PlatformStrategyModule.java
src/main/java/com/redhat/rhjmc/containerjfr/platform/openshift/OpenShiftPlatformClient.java
src/test/java/com/redhat/rhjmc/containerjfr/platform/internal/KubeApiPlatformClientTest.java
src/test/java/com/redhat/rhjmc/containerjfr/platform/openshift/OpenShiftPlatformClientTest.java

Fixes #282
This basically duplicates the existing `OpenShiftPlatformClient` implementation for reuse as the `KubeApiPlatformClient`. These use two different client libraries for the internal API clients, which also means different library implementations for the various Kubernetes types (Endpoints, Subsets, Ports, etc.). So although these types model the same Kubernetes datatypes, the types themselves are distinct hierarchies, and so the final concrete `PlatformClient` implementations are also distinct and do not inherit from each other (unfortunately).
This can be tested by setting the `CONTAINER_JFR_PLATFORM` env var to force the `KubeApiPlatformClient` into use and then running as usual in CRC. This should result in essentially no noticeable difference from running with the standard …

Discover Kube targets by Endpoints, not Services

---

HTTP_API.md

Add certificateUpload to api documentation

---

HTTP_API.md
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/CertificatePostHandler.java

Not sure when it was changed, but the name of the env var for the ssl truststore was changed in entrypoint, and was not updated in the certificatePostHandler.

fix difference in truststore env var name

---

src/test/java/itest/ClientAssetsIT.java

See https://github.com/rh-jmc-team/container-jfr-web/pull/161

Adjust tests for split client bundles

---

HTTP_API.md
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/HttpApiV2Module.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/TargetRecordingOptionsListGetHandler.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/TargetRecordingOptionsListGetHandlerTest.java

Add `TargetRecordingOptionsListGetHandler`

---

src/main/java/com/redhat/rhjmc/containerjfr/ContainerJfr.java
src/main/java/com/redhat/rhjmc/containerjfr/MainModule.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/CommandExecutor.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/CommandsModule.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/CommandExceptionResponseMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/CommandMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/CommandUnavailableMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/FailedValidationResponseMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/FailureResponseMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/InvalidCommandResponseMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/MalformedMessageResponseMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/MessagingModule.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/MessagingServer.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/ResponseMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/SuccessResponseMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/WsClient.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/WsCommandExecutor.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/WsMessage.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/notifications/Notification.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/notifications/NotificationFactory.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/notifications/NotificationsModule.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/HttpMimeType.java
src/test/java/com/redhat/rhjmc/containerjfr/commands/CommandExecutorTest.java
src/test/java/com/redhat/rhjmc/containerjfr/messaging/MessagingServerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/messaging/WsClientTest.java
src/test/java/com/redhat/rhjmc/containerjfr/messaging/WsCommandExecutorTest.java
src/test/java/itest/BasicCommandChannelIT.java

This lays the foundation for #158 . The WebSocket connection used for the Command Channel is expanded to also serve as the Notification Channel. When the Command Channel is dropped, the Notification Channel will remain and become the only use of the WebSocket client connections. In the backend, callsites consume the Notification API by injecting the `NotificationFactory`, building a `Notification`, and calling `send()` on it. This writes the `Notification` as JSON on the WebSocket connection for clients to receive and do with as they will.
Currently the only `Notification`s implemented are in the `MessagingServer` itself, and provide notifications to clients for when a client is connected/disconnected/dropped (connection refused). Clients receive a notification about themselves being …

Push notifications

---

README.md
base-image/Containerfile
base-image/build.sh
build-images.sh
pom.xml

Create a custom base image Containerfile and build script (currently just extends the previous ubi8 base image with no changes) and set pom.xml to use this new image for container builds
Fixes #333

Use custom base image

---

base-image/Containerfile
base-image/build.sh
base-image/include/truststore-setup.sh
pom.xml
src/main/extras/app/entrypoint.sh

Based on top of #336
Fixes #334

Create SSL truststore and import system certs at build time

---

smoketest.sh

See rh-jmc-team/container-jfr-operator#130

Use customized Grafana dashboard image

---

run.sh
src/main/java/com/redhat/rhjmc/containerjfr/platform/PlatformModule.java

Use single method exit point to ensure post-selection logic (currently, client starting) is performed for both automatic and manual platform selection
Fixes #344

Do not exit early from platform detection

---

src/test/java/com/redhat/rhjmc/containerjfr/commands/CommandExecutorTest.java
src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/AbstractRecordingCommandTest.java
src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/HelpCommandTest.java
src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/HostnameCommandTest.java
src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/IpCommandTest.java
src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/PrintUrlCommandTest.java
src/test/java/com/redhat/rhjmc/containerjfr/commands/internal/RecordingOptionsCustomizerCommandTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/BasicAuthManagerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/WebServerTest.java

Fix Dreprecated `Mockito.verifyZeroInteractions()`

---

src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/HttpApiV1Module.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/TargetRecordingPatchSave.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/TargetRecordingPatchSaveTest.java

Use Alias in Archived Recording Names if Possible

---

HTTP_API.md
src/main/java/com/redhat/rhjmc/containerjfr/MainModule.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/WebServer.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/ApiData.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/ApiMeta.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/ApiResponse.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/ApiResultData.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/AbstractV2RequestHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/ApiException.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/CertificatePostHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/IntermediateResponse.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/RequestParameters.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/RequestParams.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/TargetEventsSearchGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/TargetRecordingOptionsListGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/TargetSnapshotPostHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/util/HttpMimeTypeAdapter.java
src/main/java/com/redhat/rhjmc/containerjfr/util/PathTypeAdapter.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/AbstractV2RequestHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/CertificatePostHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/TargetEventsSearchGetHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/TargetRecordingOptionsListGetHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/TargetSnapshotPostHandlerTest.java

Fixes #317
This PR introduces a new `AbstractV2RequestHandler` class, similar to the existing `AbstractAuthenticatedRequestHandler`, for all V2 API handlers to extend. Rather than passing in a Vertx `RoutingContext` directly to the handler and having it directly write to the context response, subclasses of this new abstract handler receive a `RequestParams` object which abstracts out the read-only request properties that the handler may require (such as path parameters, headers, query parameters). Rather than writing to the response directly (which is no longer available through the `RequestParams`), subclasses return an instance of `IntermediateResponse`, which encapsulates the response result body as well as an optional status code (default `200`), additional headers, and optional …

V2 Response API Format

---

HTTP_API.md
src/main/java/com/redhat/rhjmc/containerjfr/net/reports/SubprocessReportGenerator.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/AbstractAuthenticatedRequestHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/TargetReportGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/AbstractV2RequestHandler.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/http/AbstractAuthenticatedRequestHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/TargetReportGetHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/AbstractV2RequestHandlerTest.java

Fixes #353 
For most handlers, adding a check for target-not-found exceptions in the abstract handler class (V1 and V2) was enough.
For `TargetReportGetHandler`, since the exception thrown is different, I made a change in the handler itself. I had to change some of the subprocess classes to public to do this, though I'm not sure if there's a way to avoid that.
Some unrelated small fixes to HTTP API docs.

Use 404 when Target Not Found

---

src/main/java/com/redhat/rhjmc/containerjfr/net/reports/ArchivedRecordingReportCache.java
src/main/java/com/redhat/rhjmc/containerjfr/net/reports/ReportsModule.java
src/main/java/com/redhat/rhjmc/containerjfr/net/reports/SubprocessReportGenerator.java
src/test/java/com/redhat/rhjmc/containerjfr/net/reports/ActiveRecordingReportCacheTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/reports/ArchivedRecordingReportCacheTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/reports/SubprocessReportGeneratorTest.java

Previously, subprocessed report generation was triggered by either the `ActiveRecordingReportCache` or `ArchivedRecordingReportCache`. The `ActiveRecordingReportCache` would provide a description of the target (connection URL and any credentials) and the recording name, and the `ArchivedRecordingReportCache` would provide a local filesystem URI to a recording file already on-disk. The subprocess would then determine which it was provided at run time and either directly process the archived recording into a report, or set up its own connection toolkit and connection manager, then connect to the target application directly, copy the recording stream to a file, and then proceed to process it and generate a report. Then the report is written to a file and the subprocess shuts down.
This was …

Simplify SubprocessReportGenerator

---

src/main/java/com/redhat/rhjmc/containerjfr/ContainerJfr.java
src/main/java/com/redhat/rhjmc/containerjfr/MainModule.java
src/main/java/com/redhat/rhjmc/containerjfr/commands/internal/CommandRegistryImpl.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/MessagingModule.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/MessagingServer.java
src/main/java/com/redhat/rhjmc/containerjfr/messaging/WsClient.java
src/main/java/com/redhat/rhjmc/containerjfr/net/BasicAuthManager.java
src/main/java/com/redhat/rhjmc/containerjfr/net/HttpServer.java
src/main/java/com/redhat/rhjmc/containerjfr/net/SslConfiguration.java
src/main/java/com/redhat/rhjmc/containerjfr/net/TargetConnectionManager.java
src/main/java/com/redhat/rhjmc/containerjfr/net/reports/ActiveRecordingReportCache.java
src/main/java/com/redhat/rhjmc/containerjfr/net/reports/ArchivedRecordingReportCache.java
src/main/java/com/redhat/rhjmc/containerjfr/net/reports/SubprocessReportGenerator.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/WebServer.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/RecordingsPostHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/TemplatesPostHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/generic/HealthGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/platform/PlatformModule.java
src/test/java/com/redhat/rhjmc/containerjfr/net/BasicAuthManagerTest.java

Fixes #358 
There are two or three statements where I left the String.format call because they had several arguments, and it probably doesn't make sense to create functions for that exact number of objects in cjfr-core.

Remove String.format from logger calls to improve performance

---

pom.xml

These dependencies are currently brought in with JMC/Eclipse and need to specified explicitly after https://github.com/rh-jmc-team/container-jfr-core/pull/56.

Add guice and plexus-utils dependencies

---

pom.xml

This is a backport of #367. It also updates the core version.

[v1] Add guice and plexus-utils dependencies

---

pom.xml

We shouldn't need this included as a runtime dependency.

Use provided scope for spotbugs-annotations

---

pom.xml

[v1] Use provided scope for spotbugs-annotations

---

src/main/java/com/redhat/rhjmc/containerjfr/net/reports/ActiveRecordingReportCache.java
src/main/java/com/redhat/rhjmc/containerjfr/net/reports/SubprocessReportGenerator.java
src/test/java/com/redhat/rhjmc/containerjfr/net/reports/ActiveRecordingReportCacheTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/reports/SubprocessReportGeneratorTest.java

Fixes #364
The file cleanup after an active recording has a report generated erroneously attempts to delete the file which was just written with the report contents. This is done asynchronously, so there may be a race between the cleanup thread and the thread handling the report request (and going through the cache).
This PR simply corrects the cleanup hook to delete the correct file - the temporarily copied flight recording - and does it synchronously since this should be a relatively fast operation anyway, and report generation is expected to be slow.

Delete correct file on post-generation cleanup

---

smoketest.sh

Since yesterday I had been unable to run the `smoketest.sh` successfully - the script would get stuck at configuring the jfr-datasource, as the `curl` request to check the Grafana dashboard's `/api/health` would always get a `Connection Refused` response. I determined that the problem was that while the containers were running as expected, the ports they were bound to on the host machine did not match the port numbers expected and used in the script.
This patch simply explicitly binds the inside-the-pod-port-numbers to the same port numbers on the host. This sets the behaviour back in-line with what was intended previously, and which I assume was broken in some recent `podman` (or `libpod` etc.) update.
The alternative would be to allow the host port numbers to be assigned randomly, and …

Explicitly bind container ports to host ports

---

src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/AuthPostHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/ClientUrlGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/GrafanaDashboardUrlGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/GrafanaDatasourceUrlGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/RecordingDeleteHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/RecordingGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/RecordingsGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/TargetEventsGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/TargetRecordingDeleteHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/TargetRecordingOptionsPatchHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/TargetRecordingsGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/TargetRecordingsPostHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/TargetSnapshotPostHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/TargetTemplateGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/TargetTemplatesGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/TargetsGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/TemplateDeleteHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v1/TemplatesPostHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/TargetSnapshotPostHandler.java

Fixes #312 
Handler | Async? | Notes
-- | -- | --
`AuthPostHandler` | No | 
`ClientUrlGetHandler` | No | A unit test expects it to be async.
`GrafanaDashboardUrlGetHandler` | No | 
`GrafanaDatasourceUrlGetHandler` | No | 
`RecordingDeleteHandler` | No | 
`RecordingGetHandler` | Yes | `ctx.vertx().filesystem().exists()` is async.
`RecordingsGetHandler` | No | 
`RecordingsPostHandler` | Yes | `validateRecording()` and `saveRecording()` are async, but this handler already has `isAsync()` set to `false`.
`RecordingUploadPostHandler` | No | Already has `isAsync()` set to `false`.
`ReportGetHandler` | No | Already has `isAsync()` set to `false`.
`TargetEventsGetHandler` | No | 
`TargetRecordingDeleteHandler` | No | 
`TargetRecordingGetHandler` | No | Already has `isAsync()` set to `false`. …

Add isAsync() for All Handlers

---

pom.xml
src/assembly/dist.xml

This adds an assembly descriptor that creates a tar.gz archive of all artifacts needed for the container image. The motivation behind this is for use cases where we can't or don't want to use Jib to create a container image. The structure of the archive is similar to where Jib places things, except for placing the jar of Container JFR itself in the `libs` directory instead of a separate `classes` directory for its class files. This assembly step is only done when its profile is manually enabled (e.g. `mvn -Pdist package`).

Optionally create distributable image archive

---

pom.xml
src/assembly/dist.xml

When building on a system with generated UID/GIDs that can be quite large, you'll may see a build failure due to a limitation on GNU tar:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single (assemble-dist) on project container-jfr: Execution assemble-dist of goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single failed: user id '1060820000' is too big ( > 2097151 ). -> [Help 1]`
The fix is configuring maven-assembly-plugin to use the POSIX tar format instead. [1]
This PR also fixes the following warning, by providing an empty `<outputDirectory>` tag instead of `/`:
`[WARNING] The assembly descriptor contains a filesystem-root relative reference, which is not cross platform compatible /`
This is interpreted as the archive root, so there is …

Fix assembly for large uid/gid

---

pom.xml
src/assembly/dist.xml

This is a clean backport of #384 for v1.

[v1] Fix assembly for large uid/gid

---

README.md
pom.xml
src/test/java/itest/BasicCommandChannelIT.java
src/test/java/itest/ClientAssetsIT.java
src/test/java/itest/ClientUrlIT.java
src/test/java/itest/ConnectToExternalTargetsIT.java
src/test/java/itest/GrafanaDashboardIT.java
src/test/java/itest/GrafanaDatasourceIT.java
src/test/java/itest/NoopAuthIT.java
src/test/java/itest/RecordingWorkflowIT.java
src/test/java/itest/TestBase.java
src/test/java/itest/UploadRecordingIT.java
src/test/java/itest/util/Podman.java
src/test/java/itest/util/Utils.java

This is a backport of #376 . There was an adjustment to `BasicCommandChannelIT` required, which is included as a separate commit. `main` has this test disabled, so the correction was never made. Otherwise, the patch applied with only one minor merge conflict, also to `BasicCommandChannelIT`.

[V1] external container itests

---

pom.xml

While it makes sense to keep the Dagger and Dagger compiler versions in sync. Having a separate property will help with downstream builds where we add a suffix to the Dagger (core) version, but don't want to do this for the compiler.

Add separate property for Dagger compiler version

---

src/main/java/com/redhat/rhjmc/containerjfr/platform/PlatformClient.java
src/main/java/com/redhat/rhjmc/containerjfr/platform/PlatformModule.java
src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/AbstractPlatformClient.java
src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/DefaultPlatformClient.java
src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/KubeApiPlatformClient.java
src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/KubeEnvPlatformClient.java
src/main/java/com/redhat/rhjmc/containerjfr/platform/internal/PlatformStrategyModule.java
src/main/java/com/redhat/rhjmc/containerjfr/platform/openshift/OpenShiftPlatformClient.java
src/main/java/com/redhat/rhjmc/containerjfr/platform/openshift/OpenShiftPlatformStrategy.java
src/test/java/com/redhat/rhjmc/containerjfr/platform/internal/AbstractPlatformClientTest.java
src/test/java/com/redhat/rhjmc/containerjfr/platform/openshift/OpenShiftPlatformClientTest.java

Fixes #346
This uses an Endpoints resource watch in the OpenShiftPlatformClient to enable async target discovery, similar to how the DefaultPlatformClient implements async target discovery using JDP.
For ease of testing in OpenShift/CRC, I have published an image built from this PR as `quay.io/andrewazores/container-jfr:2.0.0-SNAPSHOT-endpoint-watch`.
During my testing in CRC I found that the `MODIFIED` event is emitted in many more scenarios than I expected - for example, using our Operator's Makefile, doing `make sample_app` and then `make undeploy_sample_app` produces an `ADDED` event and a `DELETED` event. But re-running `make sample_app` resulted in a `MODIFIED` event, and subsequent deploy/undeploy continues to generate `DELETED`/`MODIFIED` events, without any `FOUND`. But also, …

Use Endpoints watch for async target discovery

---

pom.xml

See rh-jmc-team/container-jfr-web#169
To test: `mvn package` repeatedly. On subsequent (re)builds, the frontend assets should not be rebuilt - instead, the existing assets in `web-client/dist` should simply be reused from the previous build.

web-client build caching

---

pom.xml

This PR updates the version of the Fabric8 Kubernetes and OpenShift clients to the 4.12.0 release. Aside from better compatibility with newer versions of Kubernetes/OpenShift [1], this solves some headaches in our downstream builds.
[1] https://github.com/fabric8io/kubernetes-client/tree/v4.12.0#compatibility-matrix

Update kubernetes/openshift-client to 4.12.0

---

pom.xml

Caffeine has a couple of dependencies that aren't required at runtime and cause some trouble for our downstream builds. We can exclude these transitive dependencies to prevent pulling them into our build. Other projects use the same approach, such as Wildfly.
Related discussion: https://github.com/ben-manes/caffeine/issues/300

Exclude unneeded Caffeine deps

---

pom.xml

[v1] Exclude unneeded Caffeine deps

---

pom.xml

This PR adds a `dep-check` profile to run OWASP Dependency Check, which scans our dependencies for vulnerabilities. I tried to accomplish this using Github's built-in Dependabot (sorry about the noise), but that just tried to update even non-vulnerable dependencies. Apparently Dependabot will alert us by default of vulnerabilities, but it's missing those found by this plugin:
```
[ERROR] One or more dependencies were identified with vulnerabilities: 
[ERROR] 
[ERROR] commons-beanutils-1.9.2.jar: CVE-2019-10086
[ERROR] httpclient-4.5.11.jar: CVE-2020-13956
[ERROR] plexus-utils-3.0.22.jar: Possible XML Injection, Directory traversal in org.codehaus.plexus.util.Expand
[ERROR] vertx-core-3.9.2.jar: CVE-2019-17640
```
I've updated those dependencies in this PR as well.

Update vulnerable dependencies, add dep-check profile

---

pom.xml

I have pushed this image to `quay.io/andrewazores/container-jfr:1.0.0-BETA5` for testing. This contains the fix for rh-jmc-team/container-jfr-web#170 .

Update web-client to v1.0.0-BETA5 and bump image version

---

README.md
pom.xml
src/main/java/com/redhat/rhjmc/containerjfr/ContainerJfr.java

Force WebSocket execution mode hardcoded at startup, while leaving other modes' code paths intact to reduce invasiveness of change

[v1] Disable non-websocket execution modes

---

src/main/java/com/redhat/rhjmc/containerjfr/net/BasicAuthManager.java
src/main/java/com/redhat/rhjmc/containerjfr/net/OpenShiftAuthManager.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/AbstractAuthenticatedRequestHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/AbstractV2RequestHandler.java
src/test/java/com/redhat/rhjmc/containerjfr/net/BasicAuthManagerTest.java
src/test/java/itest/InterleavedExternalTargetRequestsIT.java

Use encoder which produces, and decoder which expects, the URL-safe Base64 alphabet variant. The decoder is also tolerant of missing padding characters at the end, which the client will not send due to their illegality in the WebSocket Subprotocol header value. There is a corresponding web-client change: https://github.com/rh-jmc-team/container-jfr-web/pull/173 . A temporary commit is included in this PR to update the web-client to use that branch, which will be replaced before this is merged with a commit updating the web-client to a proper tagged release version containing the change.
To test, check out the #417 branch to get the token config file, then:
`CONTAINER_JFR_IMAGE=quay.io/andrewazores/container-jfr:2.0.0-base64url CONTAINER_JFR_AUTH_MANAGER=com.redhat.rhjmc.containerjfr.net.To …

Use URL-safe Base64 encoder/decoder

---

src/main/java/com/redhat/rhjmc/containerjfr/net/BasicAuthManager.java
src/main/java/com/redhat/rhjmc/containerjfr/net/OpenShiftAuthManager.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/handlers/AbstractAuthenticatedRequestHandler.java
src/test/java/com/redhat/rhjmc/containerjfr/net/BasicAuthManagerTest.java

[v1] Use URL-safe Base64 encoder/decoder (#419)

---

smoketest.sh

This simply adds another sample app to the `smoketest.sh`. This sample app is a very basic Hello World type application, but it is a Quarkus application (running in JVM mode). It's expected to be connectable with no credentials or certificate.

Quarkus sample app

---

smoketest.sh
src/main/java/com/redhat/rhjmc/containerjfr/net/BasicAuthManager.java
src/main/java/com/redhat/rhjmc/containerjfr/net/OpenShiftAuthManager.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/AbstractAuthenticatedRequestHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/AbstractV2RequestHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/ApiException.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/RuleDeleteHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/RuleGetHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/RulesPostHandler.java
src/main/java/com/redhat/rhjmc/containerjfr/rules/Rule.java
src/main/java/com/redhat/rhjmc/containerjfr/rules/RuleException.java
src/main/java/com/redhat/rhjmc/containerjfr/rules/RuleProcessor.java
src/main/java/com/redhat/rhjmc/containerjfr/rules/RuleRegistry.java
src/test/java/com/redhat/rhjmc/containerjfr/net/BasicAuthManagerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/net/web/http/api/v2/RulesPostHandlerTest.java
src/test/java/com/redhat/rhjmc/containerjfr/rules/RuleRegistryTest.java
src/test/java/com/redhat/rhjmc/containerjfr/rules/RuleTest.java
src/test/java/itest/InterleavedExternalTargetRequestsIT.java

This addresses previous review commentary for `POST /api/v2/rules` in #416.

[autorules] Rules POST handler enhancements

---

src/main/java/io/cryostat/net/web/http/api/v1/HttpApiV1Module.java
src/main/java/io/cryostat/net/web/http/api/v1/RecordingDeleteHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/RecordingsPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingDeleteHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingPatchSave.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TemplateDeleteHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TemplatesPostHandler.java
src/test/java/io/cryostat/net/web/http/api/v1/RecordingDeleteHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/RecordingsPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingDeleteHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingPatchSaveTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TemplateDeleteHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TemplatesPostHandlerTest.java

Hi,
This PR addresses https://github.com/cryostatio/cryostat/issues/354 , sending events on the Notification channel when recordings are created/deleted, archived, and templates are uploaded/deleted. I've adjusted the tests accordingly.

Backend state changes

---

smoketest.sh

This simply adds a Wildfly server as an additional demo app in the smoketest environment. It is configured with credentials (see upstream at https://github.com/andrewazores/wildfly-demo), but is not discoverable (not JDP enabled, see #468) and currently any connection attempts will fail due to #469 anyway.

Add Wildfly demo app

---

src/main/java/io/cryostat/MainModule.java
src/main/java/io/cryostat/net/web/http/api/v2/ApiException.java
src/main/java/io/cryostat/net/web/http/api/v2/RequestParameters.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetDeleteHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetsPostBodyHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetsPostHandler.java
src/main/java/io/cryostat/platform/PlatformModule.java
src/main/java/io/cryostat/platform/internal/CustomTargetPlatformClient.java
src/main/java/io/cryostat/platform/internal/MergingPlatformClient.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetDeleteHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetEventsSearchGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetsPostHandlerTest.java
src/test/java/io/cryostat/platform/internal/CustomTargetPlatformClientTest.java
src/test/java/io/cryostat/platform/internal/MergingPlatformClientTest.java

Initial backend support for #468.
Perhaps there should also be some metadata added to `ServiceRef`s to mark their source, ex. platform detection vs manually added, but that is currently not implemented.
Here we have two new V2 API handlers, for `POST /api/v2/targets` and `DELETE /api/v2/targets/:targetId`.
The `POST` request checks if there are any existing targets with an identical service URL and fails if so. If not, then a new `ServiceRef` is created using the service URL and alias provided (by `POST` form attributes) and tracked by the new `CustomTargetPlatformClient`.
The `DELETE` request simply removes any `ServiceRef` from the `CustomTargetPlatformClient` which matches the specified `targetId` path parameter.
The `CustomTargetPlatformClient` simply maintains an internal sorted set …

Implement user-specified target definitions

---

pom.xml

After the 1.0.0 release, we should bump the version on the v1 branch for any 1.1 development. I've branched a v1.0 branch prior to this for any bugfixes for potential 1.0.x releases.

Bump version to 1.1.0-SNAPSHOT

---

README.md

Fixes #481. The README now mentions the `git submodule init && git submodule update` command before mentioning `mvn compile`.

Update order of build steps in README

---

pom.xml

This updates the cryostat-base tag to (the digest of) 0.2.0.
https://quay.io/repository/cryostat/cryostat-base/manifest/sha256:233cb0897086bdb4ac74bd1d736c719ebebf660e2e7a6b5f25fc0b7e972d0a77

Update cryostat-base version

---

smoketest.sh

Fixes #483, where both the JFR datasource and the fibonacci demos attempted to bind to port 8080. Resolved by setting the fibonacci demos to listen at port 8081.
Question: I tried to update my branch with ```git pull upstream main``` and now the PR includes the changes made in commit ```43713a3``` as part of my PR. How do I fix that?

483 View in Grafana not working with smoketest.sh

---

.github/workflows/ci.yaml

This adds a CI job to query the cryostat-core version from the pom file, instead of relying on a hardcoded value.

Query POM for core version in CI

---

.github/workflows/ci.yaml

Podman is now available in the Linux-based Github runners: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md

Run integration tests in CI builds

---

src/main/java/io/cryostat/net/web/WebServer.java

Resolves #435. Exceptions that get re-thrown as a `new HttpStatusException(500, e)` by a handler get caught and handled by `WebServer`. The `new HttpStatusException` does not contain an error message itself, but the `WebServer` can append the underlying exception message to the API exception responses with `e.getCause().getMessage()`:
Slightly unrelated question: Why does JaCoCo show that the `WebServer` failure handler isn't covered by any unit tests? I found an integration test for `ClientUrl` that only tests for successful scenarios.

API exception responses should contain more detail

---

src/main/extras/app/Cryostat.xml
src/main/java/io/cryostat/net/web/WebServer.java

Related (#461)
@hareetd and I recreated this WebServerRequestEvent together by following @andrewazores' example.
(From now on, I'll be creating a separate PR for each event)

461 add custom jfr events to self

---

src/main/extras/app/Cryostat.xml
src/main/java/io/cryostat/messaging/MessagingServer.java
src/main/java/io/cryostat/messaging/WsClient.java

Related #461 
What do you think about the level of detail needed for recording WebSocket events? I decided to include the outgoing json to record more information rather than less:
Also, when is it generally appropriate to add a threshold setting for events? I added a threshold setting in this case because WebSocket messages that take a long time to send may indicate a problem.

Add WebSocket Message Emitted Event

---

rulestest.sh
src/main/java/io/cryostat/net/web/http/api/v2/RuleDeleteHandler.java
src/main/java/io/cryostat/rules/PeriodicArchiver.java
src/main/java/io/cryostat/rules/PeriodicArchiverFactory.java
src/main/java/io/cryostat/rules/RuleProcessor.java
src/main/java/io/cryostat/rules/RuleRegistry.java
src/main/java/io/cryostat/rules/RulesModule.java
src/main/java/io/cryostat/util/events/AbstractEventEmitter.java
src/main/java/io/cryostat/util/events/Event.java
src/main/java/io/cryostat/util/events/EventListener.java
src/main/java/io/cryostat/util/events/EventType.java
src/test/java/io/cryostat/net/web/http/api/v2/RuleDeleteHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/RuleGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/RulesGetHandlerTest.java
src/test/java/io/cryostat/rules/PeriodicArchiverTest.java
src/test/java/io/cryostat/rules/RuleProcessorTest.java
src/test/java/io/cryostat/rules/RuleRegistryTest.java

This addresses the following two items in the ongoing autorules PR #416:
> Deleting a non-existent rule, as well as an existing one, gives a 200. It would be helpful if non-existent-rule deletions gave a 404 instead, to indicate to the user that the given rule was not found and that no deletion has occurred. Or they could make a note of it in the result, if a 404 is inappropriate here.
`DELETE` on a rule now responds with either `200` or `404`.
> If a rule is already running, and the user would like to stop that rule (delete the active recording and stop the PeriodicArchiver), is there any way for them to do this besides killing the target container? Should deleting a rule maybe be able to do this? Or maybe this could be the job of a new PATCH STOP handler?
`DELETE`ing a rule definition …

[autorules] Rules deletion enhancements

---

src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingOptionsPatchHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandler.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingOptionsPatchHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandlerTest.java

Resolve failures in invalid recording options testing that were previously hidden due to errors in Surefire/Failsafe test runner plugins. These errors have already been resolved by @andrewazores in #503.  
Fixes #502

Fix previously hidden unit test failures

---

pom.xml

3.x  preview releases are not correctly running JUnit 5 parameterized tests in all scenarios
This PR is expected to fail CI checks, since it exposes two manually-discovered unit test failures which are currently silently lost with the Surefire/JUnit configuration in use. @hareetd has a correction for those two test cases.
Fixes #502

Use older 2.x Surefire/Failsafe test runner plugins

---

pom.xml
src/test/java/itest/InterleavedExternalTargetRequestsIT.java

Correct InterleavedExternalTargetRequestsIT teardown

---

src/main/java/io/cryostat/net/web/http/api/v2/TargetCredentialsPostHandler.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetCredentialsPostHandlerTest.java

This addresses the following deficiency in the auto-rules draft PR #416:
`POST /api/v2/targets/:targetId/credentials`
> When both the username and password are missing, the error message only says that the username is missing. It would be better if both missing parameters were mentioned.

[autorules] Mention all missing form fields on credentials POST

---

src/main/java/io/cryostat/rules/PeriodicArchiver.java
src/main/java/io/cryostat/rules/PeriodicArchiverFactory.java
src/main/java/io/cryostat/rules/RuleProcessor.java
src/test/java/io/cryostat/rules/PeriodicArchiverTest.java
src/test/java/io/cryostat/rules/RuleProcessorTest.java

Addresses the following deficiency from the original #416 review:
`General`
> Deleting the recording created by an automatic rule causes an exception whenever the archiver tries to archive the recording (expectedly). I imagine there's no good way to protect that recording from being deleting, but maybe there is a way to stop the archiver if the recording does get deleted? It does seem unlikely that a user would accidentally delete the automatic recording, though.
This PR adds a callback failure handler function from the archivers back "up" to the RuleProcessor, which the archivers use to notify the processor if archival attempts fail. This can be due to IOExceptions on writing the archives, or because the source `auto_foo` recording has been deleted elsewhere, or any other reason. This …

[autorules] Cancel periodic archivers on failure

---

rulestest.sh

See https://github.com/cryostatio/cryostat/pull/506#discussion_r652832141

[autorules] rulestest.sh touchup

---

rulestest.sh
src/main/java/io/cryostat/configuration/CredentialsManager.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetCredentialsDeleteHandler.java
src/main/java/io/cryostat/rules/PeriodicArchiver.java
src/main/java/io/cryostat/rules/PeriodicArchiverFactory.java
src/main/java/io/cryostat/rules/RuleProcessor.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetCredentialsDeleteHandlerTest.java
src/test/java/io/cryostat/rules/PeriodicArchiverTest.java
src/test/java/itest/AutoRulesIT.java

This addresses the following review deficiencies from #416 :
`DELETE /api/v2/targets/:targetId/credentials`
> Maybe the response could specify if credentials were found and deleted, or if there were no credentials to be deleted? Not super important, but might be helpful.
~~(TODO):~~
> When a rule for a target is running, and I delete the credentials for that target, the archiver is still able to archive recordings, despite the fact that JMX auth is required for this, and the saved JMX auth credentials have been deleted. I see that this is because in the code, the credentials are given to the PeriodicArchiver in the constructor and saved to the object, not retreived from the CredentialsManager each time it is used. This is more efficient, but I'm wondering if it makes sense from the user's …

[autorules] Credentials deletion enhancements

---

src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingPatchSave.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetDeleteHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetsPostHandler.java
src/main/java/io/cryostat/platform/ServiceRef.java
src/main/java/io/cryostat/platform/internal/CustomTargetPlatformClient.java
src/main/java/io/cryostat/platform/internal/DefaultPlatformClient.java
src/main/java/io/cryostat/platform/internal/KubeApiPlatformClient.java
src/main/java/io/cryostat/platform/internal/KubeEnvPlatformClient.java
src/main/java/io/cryostat/util/RelativeURIException.java
src/main/java/io/cryostat/util/URIUtil.java
src/test/java/io/cryostat/net/web/WebServerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingPatchSaveTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetsGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetDeleteHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetsPostHandlerTest.java
src/test/java/io/cryostat/platform/internal/AbstractPlatformClientTest.java
src/test/java/io/cryostat/platform/internal/CustomTargetPlatformClientTest.java
src/test/java/io/cryostat/platform/internal/DefaultPlatformClientTest.java
src/test/java/io/cryostat/platform/internal/KubeApiPlatformClientTest.java
src/test/java/io/cryostat/platform/internal/KubeEnvPlatformClientTest.java
src/test/java/io/cryostat/platform/internal/MergingPlatformClientTest.java

Related to #520 #495 #280 #281
Use (absolute) URIs in most ServiceRef API touch-points rather than JMXServiceURLs to reduce coupling and ease future explorations for non-JMX connections. JMXServiceURLs are still required in other places, namely the TargetConnectionManager only knows how to deal with JMXServiceURLs.

Loosen ServiceRef JMXServiceURL coupling

---

src/main/extras/app/Cryostat.xml
src/main/java/io/cryostat/net/TargetConnectionManager.java

Related #461 
Add custom JFR events for monitoring JMX connection status (opened, closed and failed). 
Example output:

Add JMX connection status events

---

pom.xml
src/test/java/itest/ClientAssetsIT.java

Disable web-client testing, specifically `ClientAssetsIT`, when running integration tests on minimal builds.
Fixes #525

Conditionally disable web-client testing on minimal builds

---

src/main/java/io/cryostat/net/web/http/api/v2/CertificatePostHandler.java
src/test/java/io/cryostat/net/web/http/api/v2/CertificatePostHandlerTest.java
src/test/java/itest/UploadCertificateIT.java

Fixes #494 
I'd appreciate some feedback to make the code more readable. 
After the `certValidator` tries to parse the cert and throws an exception,`filePath.toFile().delete()` returns false if it failed. I'm not sure what's the cleanest way to handle this error since it's already in a `try/catch` block?

Remove empty ssl file upload

---

pom.xml
src/main/java/io/cryostat/net/web/handlers/TargetRecordingOptionsPatchHandler.java
src/main/java/io/cryostat/net/web/handlers/TargetRecordingsPostHandler.java
src/test/java/io/cryostat/net/web/handlers/TargetRecordingOptionsPatchHandlerTest.java
src/test/java/io/cryostat/net/web/handlers/TargetRecordingsPostHandlerTest.java

[v1] Backport fixes for hidden unit test failures

---

pom.xml
src/test/java/itest/ClientAssetsIT.java

Backport of #526
* Conditionally disable web-client testing in minimal build
* Accomplish the same using system properties

[v1] Conditionally disable web-client testing on minimal builds

---

COMMANDS.md
HTTP_API.md
src/main/java/io/cryostat/commands/internal/AbstractRecordingCommand.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandler.java
src/test/java/io/cryostat/commands/internal/AbstractRecordingCommandTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandlerTest.java

Remove all event specifier string syntax. Eliminates user confusion and encourages use of event templates which are a better alternative because of the reasons stated in #480.

Remove event specifier string syntax 

---

src/main/extras/app/Cryostat.xml
src/main/java/io/cryostat/net/OpenShiftAuthManager.java

Related #461 
Not tested yet.
How can I trigger the `OpenShiftAuthManager` to emit an event?

Add auth request event

---

src/main/java/io/cryostat/MainModule.java
src/main/java/io/cryostat/net/web/http/api/v2/RulesPostHandler.java
src/main/java/io/cryostat/rules/Rule.java
src/main/java/io/cryostat/util/GsonRuleAdapter.java
src/main/java/io/cryostat/util/RuleDeserializer.java
src/test/java/io/cryostat/net/web/http/api/v2/RulesPostHandlerTest.java
src/test/java/itest/AutoRulesIT.java

Fixes #530 
@andrewazores I found a `JsonDeserializer` that can reuse `requireNonNegative()` and I have some questions about how to implement it. 
`private final Gson gson` needs to be modified in order to register the `Type Adapter` for `IntegerDeserializer`. Why is `gson` `final`?
`IntegerDeserializer` gets passed JSON values without their keys, which means I'm not sure how to pass the correct `Attribute` to `requireNonNegative()`.
`IntegerDeserializer` only works if our numeric values are of type `Integer`, not `int`. How will this affect performance?
Here's the output as of now:
```
$ vi testRule.json
{
"name": "test",
"description": "AutoRulesIT automated rule",
"eventSpecifier": "template=Continuous,type=TARGET",
"targetAlias": "es.andrewazor.demo.Main",
"archivalPeriodSeconds": 60, …
```

Validate JSON document during auto-rules creation

---

src/main/java/io/cryostat/MainModule.java
src/main/java/io/cryostat/net/ConnectionDescriptor.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandler.java
src/main/java/io/cryostat/recordings/RecordingCreationHelper.java
src/main/java/io/cryostat/recordings/RecordingsModule.java
src/main/java/io/cryostat/rules/RuleProcessor.java
src/main/java/io/cryostat/rules/RuleRegistry.java
src/main/java/io/cryostat/rules/RulesModule.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandlerTest.java
src/test/java/io/cryostat/rules/RuleProcessorTest.java

With this change, adding a new rule definition causes that rule to become immediately activated for any matching targets that are already known. Prior to this change adding a new rule definition would only affect targets that (re)appear after the rule was added.
Example:
1. Run smoketest.sh
2.
```
$ http --verify=false -f https://0.0.0.0:8181/api/v2/rules name=foorule description="Rule for testing" targetAlias=es.andrewazor.demo.Main eventSpecifier="template=Continuous"
HTTP/1.1 201 Created
content-encoding: gzip
content-length: 94
location: /api/v2/rules/foorule
{"meta":{"type":"text/plain","status":"Created"},"data":{"result":"foorule"}}
```
3. Check that the vertx sample app listening on 9093 has a new recording named auto_foorule. The other vertx apps on 9094 and 9095 require …

New rule definitions trigger on existing targets

---

src/main/java/io/cryostat/net/web/http/api/v2/TargetsPostHandler.java
src/main/java/io/cryostat/platform/ServiceRef.java
src/main/java/io/cryostat/platform/internal/DefaultPlatformClient.java
src/main/java/io/cryostat/platform/internal/KubeApiPlatformClient.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetsPostHandlerTest.java
src/test/java/io/cryostat/platform/internal/DefaultPlatformClientTest.java
src/test/java/io/cryostat/platform/internal/KubeApiPlatformClientTest.java
src/test/java/io/cryostat/util/URIUtilTest.java
src/test/java/itest/InterleavedExternalTargetRequestsIT.java

Rebased on top of #538
Fixes #280
Related to #495
Sample output from `http :8181/api/v1/targets | jq`:
```json
[
{
"connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9096/jmxrmi",
"alias": "/deployments/quarkus-run.jar",
"labels": {},
"annotations": {
"platform": {},
"cryostat": {
"HOST": "cryostat",
"PORT": "9096",
"JAVA_MAIN": "/deployments/quarkus-run.jar"
}
}
},
{
"connectUrl": "service:jmx:rmi:///jndi/rmi://cryostat:9095/jmxrmi",
"alias": "es.andrewazor.demo.Main",
"labels": {},
"annotations": {
"platform": {},
"cryostat": {
"HOST": "cryostat",
"PORT": "9095",
"JAVA_MAIN": "es.andrewazor.demo.Main"
}
}
}
]
```

Additional fields for ServiceRefs

---

.github/workflows/ci.yaml

This PR adds steps to our CI workflow that push the build image to Quay. This uses the `redhat-actions/push-to-registry` action. The step only runs on push, excluding forks. The image tags pushed to Quay are the image version defined in the POM (currently `2.0.0-SNAPSHOT`), `latest`, and the commit SHA. The latter creates a new tag upon each commit. I'm not sure if we want this. It's nice for traceability, but will end up creating a lot of tags.
The push is done by a robot account in Quay, whose credentials will be stored in a Github secret [1]. To test, I temporarily substituted the Cryostat account for my own. The results can be seen below:
CI on PR, not pushed to Quay: https://github.com/ebaron/cryostat/runs/2975581732
CI on push, pushed to Quay: …

ci(ci): Push built CI images to Quay

---

.github/workflows/ci.yaml

This removes the Git SHA from image tags pushed to Quay from CI. We decided this would clutter up the list of tags too much.

ci(quay): remove Git SHA from image tags

---

.github/workflows/ci.yaml
pom.xml

If there are itest failures, the log output of the cryostat container itself will be printed out in the workflow action run to aid troubleshooting. As it is now, only the itest runner's side of the output is seen, but not the cryostat backend's internal logging, which would likely contain additional details.

ci(log): print podman logs on CI failure

---

pom.xml
src/main/extras/app/entrypoint.sh

Resolves #529
Upgrades maven jib plugin to version 3.1.1 and uses the new JVM argument files `/app/jib-classpath-file` and `/app/jib-main-class-file` to set the custom container entrypoint.

build(jib): Update-maven-jib-plugin

---

.github/workflows/ci.yaml

Backport of #545 and #558 
This backport does not push to the `latest` tag, only the image version tag. As a result, the step for tagging images is no longer needed.
This PR also removes the `main` branch from the event triggers.

ci(quay): push built CI images to Quay

---

HTTP_API.md
src/main/java/io/cryostat/net/web/http/api/v2/RulesPostHandler.java
src/main/java/io/cryostat/rules/RuleException.java

docs(auto-rules): update HTTP_API.md

---

src/main/java/io/cryostat/net/web/http/api/v2/RulesPostHandler.java
src/test/java/io/cryostat/net/web/http/api/v2/RulesPostHandlerTest.java

Fixes #570
Cause of the error is from `RulesPostHandler line 130`:
- `gson.fromJson` returns `null` without throwing an exception
- `null` is passed to `addRule()` which throws an `IOException`/`500`
```
public <T> T fromJson(String json, Type typeOfT) throws JsonSyntaxException {
if (json == null) {
return null;
}
StringReader reader = new StringReader(json);
T target = (T) fromJson(reader, typeOfT);
return target;
}

fix(auto-rules): Check for null json before creating rule

---

pom.xml
run.sh
src/test/java/itest/ApiListingIT.java
src/test/java/itest/AutoRulesIT.java
src/test/java/itest/BasicCommandChannelIT.java
src/test/java/itest/NotificationsUrlIT.java
src/test/java/itest/util/Utils.java

test(itest): make test host configurable

---

src/test/java/itest/AutoRulesIT.java
src/test/java/itest/RulesPostFormIT.java
src/test/java/itest/RulesPostJsonIT.java

Related #474 
Adds integration tests to cover `4xx` status codes defined by `RulesPostHandler.java`.

test(auto-rules): Add POST rule itests

---

src/main/java/io/cryostat/net/web/http/api/ApiVersion.java
src/main/java/io/cryostat/net/web/http/api/beta/HttpApiBetaModule.java

chore(api): add empty /api/beta group

---

src/test/java/itest/RulesPostFormIT.java
src/test/java/itest/RulesPostJsonIT.java
src/test/java/itest/bases/StandardSelfTest.java

Related #474 
When a `CompleteableFuture` is completed exceptionally, `assertRequestStatus()` will also send the HTTP status code along with the exception. Integration tests can now verify that the correct error code was returned along with the exception message.
e.g
```
webClient
.post("/api/v2/rules")
.sendForm(
testRule,
ar -> {
assertRequestStatus(ar, response);
});
ExecutionException ex =
Assertions.assertThrows(ExecutionException.class, () -> response.get());
MatcherAssert.assertThat(
((HttpStatusException) ex.getCause()).getStatusCode(), Matchers.equalTo(400));
MatcherAssert.assertThat(ex.getCause().getMessage(), Matchers.equalTo("Bad Request"));
```
Edit: I have also added status code checks to `RulesPostJsonIT.java` and `RulesPostFormIT.java`.

test(itest): Send status code during exceptional future completion

---

src/test/java/itest/CredentialsIT.java

Related #474 
While `AutoRulesIT.java` already tests successful creation and deletion of credentials, this PR tests `4xx` error handling when posting or deleting credentials.

test(auto-rules): Add itests for credentials POST and DELETE

---

src/test/java/itest/AutoRulesIT.java

Related #474
Added itests to confirm that the `RuleGetHandler` and `RuleDeleteHandler` throw `404` when a non-existent rule is requested.

test(auto-rules): Test GET or DELETE rule not found

---

src/main/java/io/cryostat/net/web/WebServer.java

fix(webserver): avoid NPE if client sets no Accept header

---

src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingDeleteHandler.java
src/main/java/io/cryostat/recordings/RecordingNotFoundException.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingDeleteHandlerTest.java

Fixes #596 
When attempting to delete a non-existent recording, the `TargetRecordingDeleteHandler` will throw an HTTP `404` status code instead of an HTTP `500` error. The error message is the same as before.
```
> DELETE /api/v1/targets/localhost:0/recordings/nonExistentRecording HTTP/1.1
> Host: 0.0.0.0:8181
> User-Agent: curl/7.71.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< content-type: text/plain
< content-length: 99
< 
* Connection #0 to host 0.0.0.0 left intact
Not Found caused by RecordingNotFoundException: No recording with name "nonExistentRecording" found
```

fix(recordings): Throw 404 when deleting non-existent recording

---

src/test/java/itest/RecordingsPostIT.java
src/test/java/itest/TargetRecordingsPostIT.java

Related #474 
Tests the `4xx` errors handled by the `TargetRecordingsPostHandler`.

test(recordings): Add itests for target recordings POST handler

---

src/test/java/itest/TargetRecordingsClientErrorIT.java

Related #474 
I decided to rename `TargetRecordingsPostIT` to `TargetRecordingsClientErrorIT` and put all the `4xx` tests related to the target recording handlers into one file.
These tests should cover all the `4xx` scenarios caused by the `TargetRecordings` `GET`, `DELETE`, `PATCH`, `PATCH options`, and `upload POST` handlers.

test(recordings): Add more target recording handler 4xx itests

---

src/main/java/io/cryostat/net/web/http/AbstractAuthenticatedRequestHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/RecordingGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/RecordingsGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/ReportGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetEventsGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingOptionsGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingOptionsPatchHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingsGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetTemplatesGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetsGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/AbstractV2RequestHandler.java
src/test/java/io/cryostat/net/web/http/AbstractAuthenticatedRequestHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/RecordingDeleteHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/RecordingUploadPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/ReportGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingOptionsGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingPatchHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingUploadPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetsGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/AbstractV2RequestHandlerTest.java

fix(api): set Content-Type header on all responses

---

.github/workflows/ci.yaml

This PR adds a check that the branch name is `main` before applying the `latest` tag. This allows us to be sure that when we branch for v2, the existing Github workflow won't tag v2 builds as `latest`.
Example run: https://github.com/ebaron/cryostat/actions/runs/1057516228
Relates to: #595

ci(quay): apply latest tag only in main

---

src/main/java/io/cryostat/net/web/http/api/v1/TemplatesPostHandler.java
src/test/java/io/cryostat/net/web/http/api/v1/TemplatesPostHandlerTest.java
src/test/java/itest/TemplatePostIT.java
src/test/resources/invalidTemplate.xml

Fixes #601 
When posting a file upload with a form attribute that doesn't match the name `template`, the `TemplatesPostHandler` will return an HTTP `400`.

fix(templates): Throw 400 when posting unexpected file upload name

---

src/main/java/io/cryostat/net/web/http/api/v2/CertificatePostHandler.java
src/test/java/itest/UploadCertificateIT.java

Fixes #603
Source of bug: Inside the `try-with-resources` block, the handler throws an `ApiException(500, "No certificates found")` when it finds an empty file. If I replace the `500` with `400`, I still receive a `500` because the `try-with-resources` block catches all `Exception`s and re-throws them as `500`.
This fix throws a `FileNotFoundException` instead of an `ApiException`, which gets caught and rethrown as an `ApiException` with status code `400`.

fix(certificates): Empty cert uploads throw 400 instead of 500

---

src/test/java/itest/TargetPostDeleteIT.java

Related #474 
Tests the `TargetsPostHandler` and `TargetDeleteHandler`.

test(targets): Add itest for targets POST and DELETE

---

.github/workflows/linked-issue.yml
.github/workflows/pr-labeled.yml

ci(actions): require referenced issue and PR labels

---

src/main/java/io/cryostat/net/web/http/api/v1/TargetReportGetHandler.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetReportGetHandlerTest.java
src/test/java/itest/TargetReportIT.java

fix(report): Throw 404 when recording not found

---

src/test/java/itest/ReportIT.java
src/test/java/itest/TargetReportIT.java

Related #474 
Tests the HTTP `200` and `404` scenarios for the `TargetReportGetHandler` and `ReportGetHandler`. 
`TargetReportIT` downloads the report directly from the JVM whereas `ReportIT` also makes one more call to save the recording to archive before getting the report from the archive.
Update: All tests are passing
~~Summary of test failures:~~
~~1) `TargetReportGetHandler` throws `500` instead of `404` when getting a non-existent recording (should pass after #614 is merged)~~
~~2) When the Jsoup HTML parser parses the report, it returns a list of `Unexpected Token` errors. See review below~~

test(report): Add report itests

---

src/test/java/itest/RecordingWorkflowIT.java

Related #474 
Addresses the `TODO`s in `RecordingWorkflowIT`:
```
// verify that reports can be downloaded successfully and yield non-empty HTML documents
// (TODO: verify response body is a valid HTML document)
```
```
// verify in-memory and saved recordings can be downloaded successfully and yield
// non-empty recording binaries (TODO: better verification of file content), and that
// the fully completed in-memory recording is larger than the saved partial copy
```

test(recordings): Verify file contents from RecordingWorkflowIT

---

src/test/java/itest/TargetEventsGetIT.java

Related #474 
Adds integration tests for the v1 `TargetEventsGetHandler` and the v2 `TargetEventsSearchGetHandler`

test(targets): Add target events GET search tests

---

src/test/java/itest/SnapshotIT.java

Related #474 
Tests a successful snapshot `POST` and a `404` scenario for both `v1` and `v2` versions of `TargetSnapshotPostHandler`.

test(snapshot): Add POST snapshot itests

---

HTTP_API.md
src/main/java/io/cryostat/net/web/http/api/v2/HttpApiV2Module.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetEventsGetHandler.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetEventsGetHandlerTest.java
src/test/java/itest/TargetEventsGetIT.java

feat(eventssearch): implement search as query param

---

src/main/java/io/cryostat/net/web/http/generic/WebClientAssetsGetHandler.java

fix(webclientassets): produce 404 instead of 500 when minimal

---

src/test/java/itest/TargetRecordingOptionsIT.java

Related #474 
Tests successful scenarios for the `TargetRecordingOptionsGetHandler`, `TargetRecordingOptionsPatchHandler`, and the `TargetRecordingOptionsListGetHandler`.

test(recordings): Add recording options itests

---

src/test/java/itest/ReportIT.java

Fixes #630 
Initializes the file at the start of the test instead of in the middle. Both `File` and `Document` are now local variables.

test(report): Fix file initialization

---

HTTP_API.md
pom.xml
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingOptionsPatchHandler.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingOptionsPatchHandlerTest.java
src/test/java/itest/TargetRecordingOptionsIT.java

fix(recordingoptions): client may explicitly unset options

---

HTTP_API.md
src/main/java/io/cryostat/rules/MatchExpressionValidator.java
src/main/java/io/cryostat/rules/Rule.java
src/main/java/io/cryostat/rules/RuleProcessor.java
src/main/java/io/cryostat/rules/RuleRegistry.java
src/test/java/io/cryostat/rules/RuleProcessorTest.java
src/test/java/io/cryostat/rules/RuleRegistryTest.java
src/test/java/io/cryostat/rules/RuleTest.java

Closes #645
Fixes #643
This implements an alternative and simplified version of the "one-shot" rules.
If a Rule definition is given where `"eventSpecifier":"archive"`, the rule definition will not be persisted, does not require a unique name, may not have `archivalPeriodSeconds/preservedArchives/maxAge/maxSize`, and rather than starting a new recording will cause a snapshot to be taken, copied to archives, and the snapshot immediately removed.
The motivation is to allow a user to have a workflow such as the following:
```
POST /api/v2/rules
```
```json
{
"name": "monitor",
"description": "Monitor application, all the time",
"eventSpecifier": "template=Continuous",
"matchExpression": "target.labels.app=='MyApp'",
"archivalPeriodSeconds": 3600,
"maxAgeSeconds": 300,
"preservedArchives": 6
} …
```

feat(rules): implement "archive" rules

---

pom.xml
src/main/java/io/cryostat/ApplicationVersion.java
src/main/java/io/cryostat/MainModule.java
src/main/java/io/cryostat/net/web/http/generic/HealthGetHandler.java
src/test/java/io/cryostat/net/web/http/generic/HealthGetHandlerTest.java
src/test/java/itest/HealthIT.java

Fixes #649
Depends on https://github.com/cryostatio/cryostat-web/pull/241
```
$ https :8181/health
HTTP/1.1 200 OK
content-encoding: gzip
content-length: 117
content-type: application/json
{
"cryostatVersion": "v2.0.0-SNAPSHOT-188-ga975bef7",
"dashboardAvailable": false,
"datasourceAvailable": false
}
```

feat(health): add cryostatVersion

---

src/assembly/dist.xml

This adds `cryostat.jfc` to the root of the assembly. The consumer of the assembly can move it to the appropriate JRE directory.
Fixes #652

fix(assembly): add cryostat.jfc to assembly

---

src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
src/test/java/io/cryostat/recordings/RecordingArchiveHelperTest.java

Fixes #665
The target alias is currently included as-is in the destination filename when writing a JFR file to disk. This can be problematic since the target alias can contain characters like '/', for example `/deployments/quarkus-run.jar` in the quarkus-test sample application.  The solution presented here is to URL encode the alias before including it in the destination filename, so the alias is transformed into ex. `%2Fdeployments%2Fquarkus-run.jar`.
To test:
Check the current behaviour upstream with `sh smoketest.sh`. Create a new recording on the quarkus-test application, then attempt to archive this recording. The request will fail with an AccessDeniedException.
Then retry this procedure but starting from `CRYOSTAT_IMAGE=quay.io/andrewazores/cryostat:sanitize-archive-alias sh …

fix(archive): sanitize target alias when writing file

---

pom.xml

build(maven): skip podman execs when skipITs is true

---

src/main/java/io/cryostat/net/OpenShiftAuthManager.java
src/test/java/io/cryostat/net/OpenShiftAuthManagerTest.java

fix(permissions): use proper group for pods/deployments

---

src/main/java/io/cryostat/net/web/http/AbstractAuthenticatedRequestHandler.java
src/test/java/io/cryostat/net/web/http/AbstractAuthenticatedRequestHandlerTest.java

This updates the Exception cause check to account for Exceptions that may be nested within two ExecutionExceptions. I didn't use ExceptionUtils.getRootCause because KubernetesClientException may have a cause of its own.
Fixes: #691

fix(permissions): respond with 401 when authz check fails

---

pom.xml
src/test/java/itest/ClientAssetsIT.java

Updates the web-client to latest from cryostatio/cryostat-web#308 , and updates pom.xml with newer node/yarn versions to match.

chore(web-client): update to latest

---

src/main/java/io/cryostat/platform/ServiceRef.java
src/test/java/io/cryostat/platform/ServiceRefTest.java
src/test/java/io/cryostat/rules/RuleRegistryTest.java

Fixes #699
From various readings, it seems that the obj.metadata field is always present, but the labels and annotations properties may not always be (but "should"). Here I add guards within the ServiceRef methods to treat null labels/annotations as if they are empty Maps to avoid NPEs in cases where platform implementations may return nulls to us.
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/
https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata

fix(serviceref): guard against nulls

---

src/main/java/io/cryostat/net/reports/SubprocessReportGenerator.java

fix(reports): ensure target connection remains open while copying active data

---

pom.xml

Fixes #761
Remove unused listenPort property from pom, which also removes the declared port number 9090 from the OCI metadata

fix(pom): remove unused "listen" port

---

pom.xml
repeated-integration-tests.bash

Based on top of #769
Fixes #770

fix(itest): wait for all containers to be ready

---

pom.xml
run.sh
smoketest.sh

Fixes #772
This updates the `pom.xml` versions for jfr-datasource and cryostat-grafana-dashboard used in integration testing from `1.0.0` to `latest`. Once the backport PR is opened I will change these versions from `latest` in `main` to `2.0.0` in the `v2` backport release version. Later, when `2.1.0` release is approaching and we create the upstream branch for it, then that branch should also have `latest` replaced by `2.1.0` for these two itest container versions as well.
Additionally, this PR uses `xpath` in `run.sh` and `smoketest.sh` to read `pom.xml` to determine things like the JMX and HTTP API port numbers to use by default. This is just a cleanup so that the values aren't hardcoded in multiple places, which is what leads to some places lagging behind as was the problem with the …

fix(pom): use latest jfr-datasource and grafana-dashboard

---

README.md
pom.xml
src/main/java/io/cryostat/net/NetworkModule.java
src/main/java/io/cryostat/net/TargetConnectionManager.java
src/main/java/io/cryostat/net/web/http/api/beta/TargetReportGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetReportGetHandler.java
src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
src/main/java/io/cryostat/recordings/RecordingTargetHelper.java
src/main/java/io/cryostat/rules/RuleProcessor.java
src/test/java/io/cryostat/net/TargetConnectionManagerTest.java
src/test/java/io/cryostat/recordings/RecordingArchiveHelperTest.java
src/test/java/io/cryostat/rules/RuleProcessorTest.java
src/test/java/itest/ReportJwtDownloadIT.java

fix(rules): signal connections opened by rules may be immediately closed
Related to #756
fix(pom): remove itest connection cache size config
Remove connection cache size/TTL config, which used an incorrect/outdated
cache max size env var name, to better reflect a standard Cryostat
deployment using default cache settings (unlimited size, 10s TTL)
Fixes #762
fix(rules): do not create cached connections for automated rules
Related to #756
Automated rules processing will reuse existing cached connections if
available. If none are available then a new connection will be created and
NOT cached, in order to avoid automated rules causing evictions of cached
connections for other interactive clients

fix(rules): do not create cached connections for automated rules

---

HTTP_API.md
src/main/java/io/cryostat/net/web/http/AbstractAuthenticatedRequestHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingDeleteHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetSnapshotPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/AbstractV2RequestHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetSnapshotPostHandler.java
src/main/java/io/cryostat/recordings/RecordingNotFoundException.java
src/main/java/io/cryostat/recordings/RecordingTargetHelper.java
src/main/java/io/cryostat/recordings/RecordingsModule.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingDeleteHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetSnapshotPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetSnapshotPostHandlerTest.java
src/test/java/io/cryostat/recordings/RecordingTargetHelperTest.java
src/test/java/itest/SnapshotIT.java

Fixes #715 
Depends on https://github.com/cryostatio/cryostat-web/pull/346

fix(snapshot): Cleanly handle empty snapshots

---

src/main/java/io/cryostat/net/web/http/api/v1/RecordingsPostHandler.java
src/test/java/io/cryostat/net/web/http/api/v1/RecordingsPostHandlerTest.java

fix(archiveupload): Delete improperly-named file uploads

---

README.md

docs(readme): Add cgroups v2 configuration instructions to README 

---

src/main/java/io/cryostat/messaging/MessagingModule.java
src/main/java/io/cryostat/messaging/MessagingServer.java
src/main/java/io/cryostat/messaging/WsClient.java
src/test/java/io/cryostat/messaging/MessagingServerTest.java

Related #757 
The server will ping accepted WebSocket clients every 5 seconds to prevent an idle timeout disconnection. The client will automatically respond with a pong as per [WebSocketBase docs](https://vertx.io/docs/apidocs/io/vertx/core/http/WebSocketBase.html#writePing-io.vertx.core.buffer.Buffer-io.vertx.core.Handler-)
> Once we have an upstream release that includes application-level keepalive then the downstream configuration for increasing the timeout can be removed.
After this PR is merged, I'll add another PR to remove the extended timeout annotations in [config.md](https://github.com/cryostatio/cryostat-operator/blob/main/docs/config.md#network-options) which will close #757.

feat(websocket): Add keepalive server ping

---

src/main/java/io/cryostat/messaging/MessagingModule.java
src/main/java/io/cryostat/messaging/MessagingServer.java
src/main/java/io/cryostat/rules/RulesModule.java

Fixes #793
There are also some other small fixes and improvements included, all relating to thread pools/scheduled executor services. Details in each commit message.

chore(workerthreads): use daemon threads

---

src/main/java/io/cryostat/net/web/http/api/v1/HttpApiV1Module.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingPatchStop.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingPatchStopTest.java

fix(notifications): Send notification on explicit recording stop

---

src/main/java/io/cryostat/net/AuthManager.java
src/main/java/io/cryostat/net/BasicAuthManager.java
src/main/java/io/cryostat/net/NoopAuthManager.java
src/main/java/io/cryostat/net/OpenShiftAuthManager.java
src/main/java/io/cryostat/net/TokenNotFoundException.java
src/main/java/io/cryostat/net/web/http/api/v2/HttpApiV2Module.java
src/main/java/io/cryostat/net/web/http/api/v2/LogoutPostHandler.java
src/test/java/io/cryostat/net/OpenShiftAuthManagerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/LogoutPostHandlerTest.java

Fixes #717 
Depends on https://github.com/cryostatio/cryostat-web/pull/355
Depends on https://github.com/cryostatio/cryostat-operator/pull/319
Depends on https://github.com/cryostatio/cryostat-operator/issues/320
Please see the -web PR for more information about the OAuth server logout behaviour.
This PR also updates the web client and caches the logout redirect url.

feat(auth): Add OAuth logout

---

pom.xml
src/main/java/io/cryostat/configuration/Variables.java
src/main/java/io/cryostat/net/reports/AbstractReportGeneratorService.java
src/main/java/io/cryostat/net/reports/RemoteReportGenerator.java
src/main/java/io/cryostat/net/reports/ReportGenerationException.java
src/main/java/io/cryostat/net/reports/ReportsModule.java
src/main/java/io/cryostat/net/reports/SubprocessReportGenerator.java
src/main/java/io/cryostat/net/web/WebModule.java
src/main/java/io/cryostat/net/web/http/HttpModule.java
src/main/java/io/cryostat/net/web/http/api/v1/RecordingUploadPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/ReportGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingUploadPostHandler.java
src/test/java/io/cryostat/net/reports/ActiveRecordingReportCacheTest.java
src/test/java/io/cryostat/net/reports/SubprocessReportGeneratorTest.java
src/test/java/io/cryostat/net/web/http/api/v1/RecordingUploadPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingUploadPostHandlerTest.java

Fixes #795
Fixes #567
Depends on https://github.com/cryostatio/cryostat-core/issues/113
Easy way to test: modify `smoketest.sh` similarly to the `-reports` `run.sh` (https://github.com/cryostatio/cryostat-reports/blob/3237998ca88710a5537b13d0bd4f742caf8b32d4/run.sh#L33). Add `-Dio.cryostat.reports.memory-factor=${MEMORY_FACTOR}` or `-Dio.cryostat.reports.timeout=${TIMEOUT}` to the `smoketest.sh` `JAVA_OPTIONS` for the report generator container with `${MEMORY_FACTOR}`/`${TIMEOUT}` replaced with some reduced value to induce a 413/504 response from the report sidecar. Then make a report request through the Cryostat HTTP API as usual (`GET /api/v1/recordings/foo` or `GET /api/v1/targets/foo/reports/bar`).

fix(reports): convey remote report generation status codes to client

---

README.md

docs(websocket): Fix typo

---

README.md
pom.xml
run.sh
src/main/extras/app/entrypoint.sh

feat(jdp): add env vars to enable/configure JDP

---

pom.xml
src/main/extras/cryostat.jfc
src/main/java/io/cryostat/configuration/Variables.java
src/main/java/io/cryostat/net/reports/ReportsModule.java
src/main/java/io/cryostat/net/reports/SubprocessReportGenerator.java
src/test/java/io/cryostat/net/reports/SubprocessReportGeneratorTest.java

Related #461 
Depends on https://github.com/cryostatio/cryostat-core/pull/118
Depends on https://github.com/cryostatio/cryostat-core/pull/121
Adds the custom JFR event from `InterruptibleReportGenerator` to the Cryostat template

feat(reports): Add custom JFR event for report rules

---

src/main/java/io/cryostat/net/TargetConnectionManager.java
src/main/java/io/cryostat/net/web/http/api/v1/HttpApiV1Module.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingPatchStop.java
src/main/java/io/cryostat/recordings/RecordingTargetHelper.java
src/main/java/io/cryostat/recordings/RecordingsModule.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingPatchStopTest.java
src/test/java/io/cryostat/recordings/RecordingTargetHelperTest.java

feat(notifications): Add "Recording Stopped" notification on implied stop

---

src/main/java/io/cryostat/net/web/http/api/v1/RecordingsPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingDeleteHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingPatchSave.java
src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
src/main/java/io/cryostat/recordings/RecordingTargetHelper.java
src/main/java/io/cryostat/rules/ArchivedRecordingInfo.java
src/main/java/io/cryostat/rules/PeriodicArchiver.java
src/test/java/io/cryostat/net/web/http/api/v1/RecordingDeleteHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/RecordingsGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/RecordingsPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingDeleteHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingPatchSaveTest.java
src/test/java/io/cryostat/recordings/RecordingArchiveHelperTest.java
src/test/java/io/cryostat/recordings/RecordingTargetHelperTest.java
src/test/java/io/cryostat/rules/PeriodicArchiverTest.java
src/test/java/io/cryostat/rules/RuleProcessorTest.java

When an recording is archived, an archived recording is deleted, or a recording is re-uploaded into the archive, emit a notification containing an `ArchivedRecordingInfo` object (name, downloadUrl, reportUrl) instead of only the archived recording name.
Related to https://github.com/cryostatio/cryostat-web/issues/344
Depends on https://github.com/cryostatio/cryostat-web/pull/366

fix(notifications): emit detailed recording info

---

devserver.sh

feat(devserver): add jfr-datasource+grafana container setup

---

src/main/java/io/cryostat/net/web/http/api/beta/HttpApiBetaModule.java
src/main/java/io/cryostat/net/web/http/api/v2/AbstractJwtConsumingHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/AuthTokenPostBodyHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/AuthTokenPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/DiscoveryGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/HttpApiV2Module.java
src/main/java/io/cryostat/net/web/http/api/v2/RecordingGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/ReportGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetRecordingGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetReportGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetTemplateGetHandler.java
src/test/java/io/cryostat/net/web/http/api/v2/AbstractJwtConsumingHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/AuthTokenPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/DiscoveryGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/RecordingGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/ReportGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetRecordingGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetReportGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetTemplateGetHandlerTest.java
src/test/java/itest/ArchivedRecordingJwtDownloadIT.java
src/test/java/itest/ArchivedReportJwtDownloadIT.java
src/test/java/itest/DiscoveryIT.java
src/test/java/itest/RecordingJwtDownloadIT.java
src/test/java/itest/ReportJwtDownloadIT.java
src/test/java/itest/TemplateJwtDownloadIT.java
src/test/java/itest/bases/JwtAssetsSelfTest.java

Fixes #826 #827 #828
Depends on cryostatio/cryostat-web#374

chore(beta-api): promote handlers to v2.1 API

---

GRAPHQL.md
graphql/environment-nodes-query-1.graphql
graphql/environment-nodes-query-2.graphql
graphql/environment-nodes-query-4.graphql
graphql/environment-nodes-query-5.graphql
graphql/environment-nodes-query-6.graphql
graphql/environment-nodes-query-7.graphql
graphql/root-node-query.graphql
src/main/java/io/cryostat/net/web/http/api/beta/graph/EnvironmentNodesFetcher.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/GraphModule.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/NodeFetcher.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/RootNodeFetcher.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/TargetNodesFetcher.java
src/main/resources/queries.graphqls
src/main/resources/types.graphqls

Rename query "discovery" to "rootNode"
Rename mutations with a "do" prefix
Fixes #824
Fixes #818

chore(graphql): rename mutations and a query

---

devserver.sh
src/main/java/io/cryostat/configuration/Variables.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/GraphiQLGetHandler.java

Fixes #819 
The GraphiQL web page is only available at `https://localhost:8181/api/beta/graphiql/` when running cryostat with `CRYOSTAT_DEV_MODE=true`.

fix(graphQL): Restrict GraphiQL availability to dev mode

---

src/main/java/io/cryostat/configuration/Variables.java
src/main/java/io/cryostat/net/web/http/api/v1/GrafanaDashboardUrlGetHandler.java
src/test/java/io/cryostat/net/web/http/api/v1/GrafanaDashboardUrlGetHandlerTest.java

Adds a new `GRAFANA_DASHBOARD_EXT_URL` to override `GRAFANA_DASHBOARD_URL` for the GrafanaDashboardUrlGetHandler.
Fixes: #842

fix(grafana): add GRAFANA_DASHBOARD_EXT_URL variable

---

pom.xml
src/main/java/io/cryostat/configuration/CredentialsManager.java

Depends on https://github.com/cryostatio/cryostat-core/pull/126
Depends on https://github.com/cryostatio/cryostat-core/pull/127
Fixes #566 
> // TODO do we need to secure these file contents further than simply applying owner-only
// permissions? Is it possible for other containers or processes to read target
// credentials
// in the mounted volume?
I'm not sure if it's possible for a process to read a credentials file from a different process. 
Here's what I could find related to this TODO:
This Kubernetes doc talks about `fsGroup`, but it seems related to accessing all the contents of a volume instead of specific files.
[Security Contexts for Pods and Containers - OpenShift Docs](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
> The OpenShift Container …

chore(fs): Set Posix file permissions

---

src/main/java/io/cryostat/platform/discovery/AbstractNode.java
src/main/java/io/cryostat/platform/discovery/BaseNodeType.java
src/main/java/io/cryostat/platform/internal/CustomTargetPlatformClient.java
src/main/java/io/cryostat/platform/internal/DefaultPlatformClient.java
src/main/java/io/cryostat/platform/internal/KubeApiPlatformClient.java
src/main/java/io/cryostat/platform/internal/KubeEnvPlatformClient.java
src/test/java/io/cryostat/platform/internal/KubeEnvPlatformClientTest.java
src/test/java/itest/DiscoveryIT.java

Fixes #853
I found this simple workaround for the way that GraphQL treats enum values. Rather than creating some duplication within our internal GraphQL module that re-encodes all of the NodeType enums to their Kind strings, I simply add an override on the `toString()` method for all of the NodeType implementations that simply returns the `Kind`. GraphQL uses `toString()` to serialize the `nodeType` enum field, which displays the enum member's name by default, so this override is simple and effective and doesn't duplicate definitions.
To test:
Query `http :8181/api/beta/graphql query=@graphql/root-node-query.graphql`
Query `http :8181/api/v2.1/discovery`
Compare the results of the `kind`/`nodeType` fields of nodes, before and after this patch. Before you should see ex. `REALM`/`Realm`, …

fix(graphql): override nodetype tostrings for display

---

graphql/environment-nodes-query-3.graphql
src/main/java/io/cryostat/net/web/http/api/beta/RecordingMetadataLabelsPostHandler.java
src/main/java/io/cryostat/net/web/http/api/beta/TargetRecordingMetadataLabelsPostHandler.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/GraphModule.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/GraphRecordingDescriptor.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/RecordingsFetcher.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/StopRecordingMutator.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingsGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandler.java
src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
src/main/java/io/cryostat/recordings/RecordingMetadataManager.java
src/main/java/io/cryostat/recordings/RecordingTargetHelper.java
src/main/java/io/cryostat/rules/ArchivedRecordingInfo.java
src/main/java/io/cryostat/rules/RuleProcessor.java
src/main/resources/types.graphqls
src/test/java/io/cryostat/net/web/http/api/beta/RecordingMetadataLabelsPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/beta/TargetRecordingMetadataLabelsPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingsGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandlerTest.java
src/test/java/io/cryostat/recordings/RecordingArchiveHelperTest.java
src/test/java/io/cryostat/recordings/RecordingMetadataManagerTest.java
src/test/java/io/cryostat/recordings/RecordingTargetHelperTest.java
src/test/java/itest/RecordingMetadataIT.java

Fixes #860
The main feature work is a tiny change in the `feat(recordings): set recording template in label` commit. The commit before that is some simple refactoring (affecting a lot of call sites, but a minor change in itself) to generalize the `RecordingMetadataManager` to deal with the `Metadata` type rather than just the labels map, so that we can more easily extend the `Metadata` to contain other fields in the future. And the first commit in the series fixes an oversight where GraphQL responses did not include the metadata/labels properties, so there was a discrepancy there vs the standard HTTP API.

feat(recordings): set recording template in label

---

pom.xml
src/main/java/io/cryostat/MainModule.java
src/main/java/io/cryostat/configuration/ConfigurationModule.java
src/main/java/io/cryostat/jmc/serialization/SerializableEventTypeInfo.java
src/main/java/io/cryostat/messaging/notifications/Notification.java
src/main/java/io/cryostat/net/HttpServer.java
src/main/java/io/cryostat/net/OpenShiftAuthManager.java
src/main/java/io/cryostat/net/UnauthorizedException.java
src/main/java/io/cryostat/net/reports/AbstractReportGeneratorService.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingUploadPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/ApiGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/IntermediateResponse.java
src/main/java/io/cryostat/net/web/http/api/v2/RequestParameters.java
src/main/java/io/cryostat/platform/ServiceRef.java
src/main/java/io/cryostat/platform/TargetDiscoveryEvent.java
src/main/java/io/cryostat/platform/discovery/TargetNode.java
src/main/java/io/cryostat/platform/internal/CustomTargetPlatformClient.java
src/main/java/io/cryostat/platform/internal/MergingPlatformClient.java
src/main/java/io/cryostat/platform/internal/OpenShiftPlatformStrategy.java
src/main/java/io/cryostat/recordings/EventOptionsBuilder.java
src/main/java/io/cryostat/recordings/RecordingMetadataManager.java
src/main/java/io/cryostat/rules/IllegalMatchExpressionException.java
src/main/java/io/cryostat/rules/MatchExpressionValidationException.java
src/main/java/io/cryostat/rules/RuleException.java
src/main/java/io/cryostat/util/JavaProcess.java
src/main/java/io/cryostat/util/RelativeURIException.java

Fixes #813 
Most of the new bugs were related to the `ServiceRef` object constructors and getters. Spotbugs outputs an [EI_EXPOSE_REP](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#ei-may-expose-internal-representation-by-returning-reference-to-mutable-object-ei-expose-rep) bug for these, where "returning a reference to a mutable object value stored in one of the object's fields exposes the internal representation of the object". I've added a copy constructor to return new copies of the ServiceRef objects. Let me know what you think.

chore(build): Update SpotBugs

---

src/main/java/io/cryostat/recordings/RecordingTargetHelper.java
src/test/java/io/cryostat/recordings/RecordingTargetHelperTest.java
src/test/java/itest/RecordingMetadataIT.java

fix(labels): split event template name/type into separate labels

---

HTTP_API.md

Fixes #569 
Removes all `500` response codes from `HTTP_API.md`

docs(api): omit 500 responses

---

src/main/java/io/cryostat/net/NetworkModule.java
src/main/java/io/cryostat/net/OpenShiftAuthManager.java
src/test/java/io/cryostat/net/OpenShiftAuthManagerTest.java

This PR uses the underlying HTTP client of the Fabric8 Kubernetes Client to make the GET request to query OAuth server metadata from the API server. The HTTP client is already configured to trust the cluster's root CA in order to talk to the API server as we do elsewhere in Cryostat [1].
We could instead add the CA cert bundle to our trust store at startup, but I'm concerned there may be edge cases where the CA bundle isn't mounted in the expected place. Leaving this to the Fabric8 client should give us less to think about. There's also some documentation that sounds like we should avoid trusting the CA bundle for anything other than talking to Kubernetes endpoints [2].
OkHttp and Jackson Databind are already dependencies of the Fabric8 Kubernetes Client, so we're not adding anything new. …

fix(oauth): use Kubernetes client to query OAuth server

---

src/main/java/io/cryostat/net/NetworkModule.java
src/main/java/io/cryostat/net/PermissionDeniedException.java
src/main/java/io/cryostat/net/openshift/OpenShiftAuthManager.java
src/main/java/io/cryostat/net/openshift/OpenShiftNetworkModule.java
src/main/java/io/cryostat/net/web/http/AbstractAuthenticatedRequestHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/AbstractV2RequestHandler.java
src/main/java/io/cryostat/platform/internal/OpenShiftPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/PlatformStrategyModule.java
src/test/java/io/cryostat/net/TargetConnectionManagerTest.java
src/test/java/io/cryostat/net/openshift/OpenShiftAuthManagerTest.java
src/test/java/io/cryostat/net/web/http/AbstractAuthenticatedRequestHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/AbstractJwtConsumingHandlerTest.java

Fixes #883 
Refactors the `OpenShiftAuthManager`, moving it into its own subpackage with its own DI module for encapsulation. The mounted namespace and account token files are only read from filesystem once, and the `OpenShiftClient` instance using the service account token is created once with lazy initialization and then that instance reused for the lifetime of the Cryostat container. `OpenShiftClient` instances using a user's token are stored in a cache, expiring (closing the client instance) after 5 minutes of inactivity on the client instance, so that we can reuse the client and its HTTP connection(s) while a user is actively making API requests through Cryostat. This reduces the number of memory allocations we're doing and should allow for some HTTP connection reuse, too. The …

chore(openshift): use cached, lazy init client instances

---

src/main/java/io/cryostat/net/web/http/api/beta/graph/ActiveRecordingsFetcher.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/ArchivedRecordingsFetcher.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/EnvironmentNodesFetcher.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/FilterInput.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/TargetNodeRecurseFetcher.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/TargetNodesFetcher.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/labels/EqualityMatcher.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/labels/LabelMatcher.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/labels/LabelSelectorMatcher.java
src/main/java/io/cryostat/net/web/http/api/beta/graph/labels/SetMatcher.java
src/main/resources/types.graphqls
src/test/java/io/cryostat/net/web/http/api/beta/graph/labels/LabelSelectorMatcherTest.java

Closes #846
Closes #825
Closes #822
Closes #821
Closes #820
This adds `labels` to GraphQL query filters for nodes in the deployment tree and for recordings, as well as `annotations` to query filters on target nodes. For `annotations` the Cryostat-generated annotations and the platform-provided annotations are merged together into one map. Both the `labels` and `annotations` query fields are optional, and can be given a Kubernetes label selector expression to match against the labels or annotations maps on the objects being queried.

feat(graphql): implement k8s-style label selectors

---

pom.xml

build(web-client): split build and test tasks

---

src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingDeleteHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetSnapshotPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetSnapshotPostHandler.java
src/main/java/io/cryostat/recordings/RecordingTargetHelper.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetSnapshotPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetSnapshotPostHandlerTest.java
src/test/java/io/cryostat/recordings/RecordingTargetHelperTest.java

Fixes #916 
Depends on https://github.com/cryostatio/cryostat-web/pull/427

fix(snapshot): Cleanup notification handling for snapshots

---

src/main/java/io/cryostat/Cryostat.java
src/main/java/io/cryostat/net/HttpServer.java
src/main/java/io/cryostat/net/web/WebModule.java
src/main/java/io/cryostat/net/web/WebServer.java

Fixes #929
- tmp: add intentionally blocking API handler for testing
- fix(vertx): deploy verticles with async decorated blocking handlers
The first commit in this series is just for testing purposes. It adds an API handler at "/api/beta/block" that sleeps the current thread for 5 seconds, then returns a "hello" string response.
This can be used to test by doing:
```bash
https :8181/api/beta/block
```
in one terminal. In a second terminal, before that first request completes,
```bash
https :8181/health
```
In current `main`, the `/health` request will not return until after the `/block` request returns. After the fix in this PR is applied these requests are properly handled concurrently again.

fix(vertx): deploy verticles with async decorated blocking handlers

---

src/test/java/itest/NonExistentTargetIT.java
src/test/java/itest/WrongServiceListeningOnPortIT.java

Related to #927
- test(itest): add test for nonexistent targets
- test(itest): add test for connecting to wrong target port
Adds two tests.
1. Test what happens when querying active recordings on a targetId where the service URL has a nonexistent (not reachable) host
2. Test what happens when querying active recordings on a targetId where the service URL points to a real reachable host and port, but the port is not listening for JMX connections, rather HTTP connections

test(itest): add tests for bad targetIds

---

HTTP_API.md

Fixes #935 
Rename discovery endpoint to /api/v2.1/discovery for 2.1.0 release.

docs(api): Rename /api/beta/discovery to /api/v2.1/discovery

---

src/main/java/io/cryostat/net/web/http/api/beta/HttpApiBetaModule.java
src/main/java/io/cryostat/net/web/http/api/v2/HttpApiV2Module.java
src/main/java/io/cryostat/net/web/http/api/v2/ProbeTemplateDeleteHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/ProbeTemplateUploadBodyHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/ProbeTemplateUploadHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetProbeDeleteHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetProbePostHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetProbesGetHandler.java
src/test/java/io/cryostat/net/web/http/api/v2/ProbeTemplateDeleteHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/ProbeTemplateUploadHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetProbeDeleteHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetProbeGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetProbePostHandlerTest.java

Fixes #928
Move Probe handlers from beta to v2 sub-package since they are available in v2 API. This includes moving source and test files.

chore(api): Move Probe handlers from beta to v2 package

---

src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
src/test/java/io/cryostat/recordings/RecordingArchiveHelperTest.java

Fixes #951 
There is a bug that is tracked with the spotbugs bug tracker 
`[ERROR] Medium: Nullcheck of entries at line 242 of value previously dereferenced in io.cryostat.recordings.RecordingArchiveHelper.pathIsEmpty(Path) [io.cryostat.recordings.RecordingArchiveHelper, io.cryostat.recordings.RecordingArchiveHelper] At RecordingArchiveHelper.java:[line 242]Redundant null check at RecordingArchiveHelper.java:[line 243] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE`
I'm not sure why because I don't see a clear null checking in the code I added.

fix(recordings): empty archive directories are now removed

---

HTTP_API.md

docs(api): health/liveness endpoint now is documented under the V2 API

---

src/test/java/itest/GraphQLIT.java

test(graphql): add integration tests

---

.github/workflows/ci.yaml

One more fix. In order for the `imageTagLower` property to be defined, run `validate` before `help:evaluate`.
Fixes: #973

ci(oci): run validate phase before evaluating tag

---

src/main/java/io/cryostat/net/openshift/OpenShiftAuthManager.java

Related to #635
Related to #979
Correction on #662

fix(openshift): include subresource in access check

---

src/main/java/io/cryostat/net/web/http/api/v1/RecordingsPostHandler.java
src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
src/test/java/io/cryostat/net/web/http/api/v1/RecordingsPostHandlerTest.java
src/test/java/io/cryostat/recordings/RecordingArchiveHelperTest.java

fix(notifications): added a target field to archivedRecording deletion notifications

---

.github/workflows/ci.yaml

Using `fetch-depth: 0` checks out history for all branches and tags: https://github.com/actions/checkout#Fetch-all-history-for-all-tags-and-branches
Related to: #1007

ci(submodule): use fetch-depth 0 to fetch all refs

---

src/main/java/io/cryostat/Cryostat.java
src/main/java/io/cryostat/MainModule.java
src/main/java/io/cryostat/configuration/ConfigurationModule.java
src/main/java/io/cryostat/configuration/CredentialsManager.java
src/main/java/io/cryostat/net/web/http/AbstractAuthenticatedRequestHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/CredentialsGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/HttpApiV2Module.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetCredentialsDeleteHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetCredentialsGetHandler.java
src/main/java/io/cryostat/rules/MatchExpressionEvaluator.java
src/main/java/io/cryostat/rules/RuleProcessor.java
src/main/java/io/cryostat/rules/RuleRegistry.java
src/main/java/io/cryostat/rules/RulesModule.java
src/test/java/io/cryostat/configuration/CredentialsManagerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetCredentialsDeleteHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetCredentialsGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetCredentialsPostHandlerTest.java
src/test/java/io/cryostat/rules/MatchExpressionEvaluatorTest.java
src/test/java/io/cryostat/rules/RuleProcessorTest.java
src/test/java/io/cryostat/rules/RuleRegistryTest.java
src/test/java/itest/CredentialsIT.java

Related to #895
Depends on https://github.com/cryostatio/cryostat-web/pull/475
This PR enhances the existing CredentialsManager by replacing the `targetId` field of stored credentials with a `matchExpression`. This uses the same expression evaluation internal infrastructure already in place for Automated Rules, so the syntax and behaviour is exactly the same. There is a migration function that checks all stored credentials already on disk and checks if they have the `targetId` field. If they do not then they are skipped over, since they are either invalid files or conform to the new format already.
```json
{
"targetId": "foo",
"credentials": {
"username": "user",
"password": "pass"
}
}
```
is migrated by applying a simple transformation to:
```json
{
"matchExpression": "target.connectUrl …
```

feat(credentials): implement matchExpression-based credentials

---

repeated-integration-tests.bash
repeated-unit-tests.bash

Fixes #1017
- feat(tests): allow MVN env var to override maven binary location
- fix(tests): ensure log file directories and files are created and truncated
- ensure tests are compiled before run
- implement second arg as test selector

feat(tests): repeat test script enhancements

---

src/main/java/io/cryostat/net/web/http/api/v2/AbstractJwtConsumingHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/RecordingGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/ReportGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetRecordingGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetReportGetHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetTemplateGetHandler.java
src/test/java/io/cryostat/net/web/http/api/v2/AbstractJwtConsumingHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/RecordingGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/ReportGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetRecordingGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetReportGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetTemplateGetHandlerTest.java

fix(jwt): use stored credentials when available

---

src/main/java/io/cryostat/net/web/http/api/v1/RecordingsPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/AllArchivedRecordingsFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/ArchivedRecordingsFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/FilterInput.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/GraphModule.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/RecordingsFetcher.java
src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
src/main/resources/queries.graphqls
src/main/resources/types.graphqls
src/test/java/io/cryostat/recordings/RecordingArchiveHelperTest.java
src/test/java/itest/GraphQLIT.java

Fixes #923 
Add a query for all archived recordings with the ability to filter on target source, name, and labels. Besides differentiating between JVM targets, the target source can also be used to retrieve only those recordings uploaded directly to archives (i.e. recordings not associated with a target).
Change the subdirectory name for uploaded recordings from "unlabelled" to "uploads" for clarity. 
Add a new field for archived recordings in the GraphQL Schema containing aggregate information such as the count of recordings. 
Depends on https://github.com/cryostatio/cryostat-web/pull/431

feat(graphql): Add query for all archived recordings

---

run.sh
smoketest.sh
src/main/java/io/cryostat/Cryostat.java
src/main/java/io/cryostat/MainModule.java
src/main/java/io/cryostat/discovery/BuiltInDiscovery.java
src/main/java/io/cryostat/discovery/DiscoveryModule.java
src/main/java/io/cryostat/discovery/DiscoveryStorage.java
src/main/java/io/cryostat/net/HttpServer.java
src/main/java/io/cryostat/net/web/http/api/v2/DiscoveryDeregistrationHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/DiscoveryPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/DiscoveryRegistrationHandler.java
src/main/java/io/cryostat/platform/AbstractPlatformClient.java
src/main/java/io/cryostat/platform/PlatformClient.java
src/main/java/io/cryostat/platform/discovery/NodeTypeDeserializer.java
src/main/java/io/cryostat/platform/internal/DefaultPlatformClient.java
src/main/java/io/cryostat/util/PluggableJsonDeserializer.java
src/test/java/io/cryostat/net/web/http/api/v2/DiscoveryDeregistrationHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/DiscoveryPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/DiscoveryRegistrationHandlerTest.java

Related to #1026
Related to #938
Related to #939
- feat(discovery): prepare to implement URL callback handling
- don't persist or restore plugins without callbacks
- POST plugin callback URLs on startup to check presence
- run discovery plugin with restart policy

feat(discovery): persistence and callback URL handling

---

src/main/java/io/cryostat/net/security/PermissionedAction.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/AbstractPermissionedDataFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/ActiveRecordingsFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/ArchiveRecordingMutator.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/ArchivedRecordingsFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/DeleteActiveRecordingMutator.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/DeleteArchivedRecordingMutator.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/EnvironmentNodeChildrenFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/EnvironmentNodeRecurseFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/EnvironmentNodesFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/GraphModule.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/GraphQLPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/NodeFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/RecordingsFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/RootNodeFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/SnapshotOnTargetMutator.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/StartRecordingOnTargetMutator.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/StopRecordingMutator.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/TargetNodeRecurseFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/TargetNodesFetcher.java

Fixes #1021
- chore(permissions): extract PermissionedAction interface
- chore(graphql): mark all fetchers/mutators with resource actions
- feat(graphql): implement permissions check for each graphql fetcher/mutator
- fix(graphql): ensure GraphQLContext is not null by copying DataFetchingEnvironment
- chore(graphql): apply spotless formatting
This implements granular permissions for each `fetcher`/`mutator` within the GraphQL endpoint implementation. This is achieved by removing the endpoint-level resource actions set union - by default, only a basic "token is valid" check will be performed - and delegating further permissions checks to each subsequent or nested `fetcher`/`mutator` that is executed afterward. In this implementation, each such subquery that is performed will result in a …

feat(graphql): granular permissions

---

pom.xml
src/main/java/io/cryostat/net/openshift/OpenShiftAuthManager.java
src/main/java/io/cryostat/platform/discovery/AbstractNode.java
src/main/java/io/cryostat/platform/discovery/EnvironmentNode.java
src/main/java/io/cryostat/platform/discovery/TargetNode.java
src/main/java/io/cryostat/platform/internal/CustomTargetPlatformClient.java
src/main/java/io/cryostat/platform/internal/DefaultPlatformClient.java
src/main/java/io/cryostat/platform/internal/KubeApiPlatformClient.java
src/main/java/io/cryostat/platform/internal/KubeEnvPlatformClient.java
src/main/java/io/cryostat/platform/internal/MergingPlatformClient.java
src/test/java/io/cryostat/net/openshift/OpenShiftAuthManagerTest.java
src/test/java/io/cryostat/net/web/http/api/beta/RecordingMetadataLabelsPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/beta/TargetRecordingMetadataLabelsPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/DiscoveryGetHandlerTest.java
src/test/java/io/cryostat/platform/internal/KubeApiPlatformClientTest.java
src/test/java/io/cryostat/platform/internal/MergingPlatformClientTest.java

Fixes #1036
update fabric8 kubernetes-client from 5.4.1 to 5.12.3 (latest 5.x) and replace direct Watch implementation with a fabric8 Informer. The Informer handles reconnecting the Watch on connection failures or when the API server responds with HTTP 410 (GONE), which can happen when too much time has elapsed between update notifications (such as during API server outages). The Informer also maintains an internal Store modelling the resource, in this case Endpoints, and resynchronizes this againt the API server periodically. This allows us to compute the list of ServiceRefs or the DiscoveryTree by constructing the result from the Informer's Store, rather than making an API call every time. Finally, the Informer's logic for added/updated/removed events is improved over the plain Watch …

fix(k8s): replace Watch with Informer

---

src/main/java/io/cryostat/discovery/DiscoveryStorage.java
src/main/java/io/cryostat/discovery/PluginInfo.java
src/main/java/io/cryostat/discovery/RegistrationException.java
src/main/java/io/cryostat/net/web/http/api/v2/DiscoveryPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/DiscoveryRegistrationHandler.java
src/test/java/io/cryostat/discovery/DiscoveryStorageTest.java
src/test/java/itest/DiscoveryPluginIT.java
src/test/java/itest/bases/StandardSelfTest.java

Fixes #1054
- test(discovery): add discovery plugin itest
- fix(discovery): respond 400 on duplicate registration attempt
- fix(discovery): respond 400 on update unregistered ID attempt
- chore(itest): remove unused command-response methods
Result from `bash repeated-integration-tests.bash 1 DiscoveryPluginIT` with only the first commit applied (test addition, no fixes):
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running itest.DiscoveryPluginIT
[ERROR] Tests run: 6, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.465 s <<< FAILURE! - in itest.DiscoveryPluginIT
[ERROR] shouldFailToReregister  Time elapsed: 0.016 s  <<< FAILURE!
java.lang.AssertionError:
Expected: <400>
but: …
```

fix(discovery): discovery plugin register/update errors respond 4xx

---

src/main/java/io/cryostat/net/openshift/OpenShiftAuthManager.java
src/main/resources/io/cryostat/net/openshift/OpenShiftAuthManager.properties
src/test/java/io/cryostat/net/openshift/OpenShiftAuthManagerTest.java

Fixes #979 
Related to https://github.com/cryostatio/cryostat-operator/pull/440
Use alternatives for mapping between k8s resource to cryostat since flightRecorder/Recordings are deprecated.

fix(k8s-rbac): update permission mapping between k8s and cryostat

---

pom.xml
smoketest.sh
src/main/java/io/cryostat/discovery/BuiltInDiscovery.java
src/main/java/io/cryostat/discovery/PluginInfo.java
src/main/java/io/cryostat/storage/StorageModule.java

Fixes #1053
Blocked - waiting for downstream builds of h2 2.0+ to be available.
* chore(db): upgrade dependencies
* chore(db): update h2 init and entity ID definitions
* chore(discovery): enforce field non-nullness
* chore(discovery): remove unused field

chore(db): upgrade h2 and postgres versions

---

src/main/java/io/cryostat/net/web/http/api/v1/RecordingsPostHandler.java
src/test/java/io/cryostat/net/web/http/api/v1/RecordingsPostHandlerTest.java

Fixes [#1045](https://github.com/cryostatio/cryostat/issues/1045)
The labels are set to the archived recording when "metadata" in JSON (e.g.: `{"reason":"test","reason1":"test1"}`) containing the labels is sent along to the uploaded file.

fix(archives): metadata labels may be set during upload

---

src/main/java/io/cryostat/configuration/CredentialsManager.java
src/main/java/io/cryostat/rules/RuleProcessor.java
src/test/java/io/cryostat/rules/RuleProcessorTest.java

Fixes [#1041](https://github.com/cryostatio/cryostat/issues/1041)
Created a new event listener in the `RuleProcessor` to activate the rules of the targets that matches the expression of the JMX auth credential.

fix(rules): automatically start rules on jmx credentials change

---

src/main/java/io/cryostat/rules/PeriodicArchiver.java
src/main/java/io/cryostat/rules/PeriodicArchiverFactory.java
src/main/java/io/cryostat/rules/RuleProcessor.java
src/main/java/io/cryostat/rules/RulesModule.java
src/test/java/io/cryostat/rules/PeriodicArchiverTest.java
src/test/java/io/cryostat/rules/RuleProcessorTest.java

Fixes #1087
I think this bug occurred in #1047 , looking at context like this: https://github.com/cryostatio/cryostat/pull/1047/files#diff-763906edf56f8525d84844f8e2b01a98e15bf4afe7cb959159b3a378e448fd17L275
but I haven't bisected the commit history to verify this. Just a hunch, but the fix seems simple enough anyway.

fix(rules): correct archive scanning on startup

---

src/main/java/io/cryostat/discovery/DiscoveryStorage.java
src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
src/main/java/io/cryostat/recordings/RecordingMetadataManager.java

fix(metadata): change RecordingMetadataManager startup process

---

README.md
src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
src/main/java/io/cryostat/rules/PeriodicArchiver.java
src/test/java/io/cryostat/rules/PeriodicArchiverTest.java

Fixes #1098 
Fixes #1023 
Fixes https://github.com/cryostatio/cryostat-web/issues/536
Just missed one more Periodic Archiver method change, oops.

fix(archives): fix recording deletion notifications do not update All-Archives view and fixed README typo

---

src/main/java/io/cryostat/net/web/http/api/v2/RuleDeleteHandler.java
src/test/java/io/cryostat/net/web/http/api/v2/RuleDeleteHandlerTest.java

Fixes #1093
- ignore cleanup failures, always respond 200
- do not include cleanup failures in response body
- handle deletion cleanup async
- use RecordingTargetHelper to clean up
This change makes Automated Rule deletion happen asynchronously, similar to how Automated Rule activation is also asynchronous.
Prior to this change, creating an enabled Rule definition was a fast request that simply defined the Rule and returned. Any
recordings created by that rule were processed asynchronously and separately from the original request. Deleting a rule, on
the other hand, was synchronous - all matching targets would be tested again for rule applicability, and recordings would be
stopped on any matching targets. When all of those tasks were completed the deletion response would finally be sent …

fix(rules): handle deletion async

---

src/main/java/io/cryostat/net/web/http/AbstractAuthenticatedRequestHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/AbstractAssetJwtConsumingHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/AbstractV2RequestHandler.java
src/test/java/itest/JmxAuthIT.java
src/test/java/itest/WrongServiceListeningOnPortIT.java

fix(auth): clean up auth exception handling

---

README.md
smoketest.sh
src/main/java/io/cryostat/discovery/BuiltInDiscovery.java
src/main/java/io/cryostat/discovery/DiscoveryModule.java
src/main/java/io/cryostat/storage/StorageModule.java

Fixes #1113
- use non-sa user by default for h2 setups
- fix(discovery): leave Custom Targets enabled when built-ins are disabled
- refactor to clean up instanceof check
`- use non-sa user by default for h2 setups` is not directly related to this PR but comes from discussions here:
https://github.com/cryostatio/cryostat-operator/pull/474#discussion_r994036680
In describing how things worked I realized I had left `sa` (system administrator) as the default JDBC user, which was not intentional and is not necessary. Even for the H2 database scenarios,
Cryostat should not require the use of a system administrator account.
To test, try `CRYOSTAT_DISABLE_BUILTIN_DISCOVERY=true sh smoketest.sh` before and after this PR. In either case, JDP targets should not be discovered, only the quarkus-test …

fix(discovery): leave Custom Targets enabled when builtins are disabled

---

repeated-integration-tests.bash
src/test/java/itest/bases/ExternalTargetsTest.java

Related to #1068
default values have been thoroughly tested over a long time and appear to be overly cautious. JDP "settling" doesn't seem to happen and is more likely to indicate a broken implementation than a natural effect.

test(itest): reduce JDP wait times

---

pom.xml

For downstream builds, we may end up with different versions of jasypt and jasypt-hibernate5. We need separate properties for them.
Related to: #1118

build(pom): use different property for jasypt-hibernate5

---

src/main/java/io/cryostat/recordings/JvmIdHelper.java
src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
src/main/java/io/cryostat/recordings/RecordingMetadataManager.java
src/main/java/io/cryostat/recordings/RecordingsModule.java
src/test/java/io/cryostat/recordings/RecordingArchiveHelperTest.java
src/test/java/io/cryostat/recordings/RecordingMetadataManagerTest.java

Fixes #1135
I think this needs documentation since users will wonder where their recordings went after migrating from 2.1.0 to 2.2.0.

fix(archives): fixed archive migration and metadata handling from all-archives view

---

src/test/java/itest/UploadRecordingIT.java

Related #474 
Addresses the `TODO` in `UploadRecordingIT`:
```
TODO, this test needs to be updated to actually trigger a file to be uploaded to
jfr-datasource/grafana-dashboard now that the integration tests have these additional
containers configured
```

test(recordings): itest for loading a recording to jfr-datasource

---

pom.xml

Fixes #1128 
Upgraded `jib` to latest version (i.e. `3.3.0`). There is a new [feature](https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/CHANGELOG.md#added-3) specified multi-platform build, which is pretty interesting but not sure we need it.

build(jib): upgrade jib plugin to 3.3.0

---

pom.xml

Related to #1126
Related to #1140
Bumps -core version up to 2.14.1 which includes the required JMC Agent fixes for the updated probe handlers and new UI. I already bumped -core in v2.2 to this same version in the #1140 backport.

build(pom): bump -core version for JMC agent underlying fixes

---

.github/workflows/ci.yaml

Fixes #1143 
The needs `get-pom-properties` change most likely fixes everything because I tested it with my own fork here: 
https://github.com/maxcao13/cryostat/tree/ci-testing
https://github.com/maxcao13/cryostat/blob/ci-testing/.github/workflows/ci.yaml
and heres the workflow:
https://github.com/maxcao13/cryostat/actions/runs/3308808673
and heres the pushed image:
https://quay.io/repository/macao/cryostat?tab=tags

fix(ci): push-to-quay needs get-pom-properties and fix spotbugs job to build headless

---

src/main/java/io/cryostat/net/web/http/api/v2/TargetProbeDeleteHandler.java

Hi,
Quick fix to the TargetProbeDeleteHandler which fixes an issue found in the frontend as well. It currently uses the wrong notification category, this PR gives it it's own.
Related to #1126

fix(jmc-agent): Fix notification category for TargetProbeDeleteHandler

---

.github/workflows/ci.yaml
repeated-integration-tests.bash

Fixes #1152 
Also, I didn't mention this before but there is a mismatch of the itest output filename logs between the bash script and the mvn build executions. 
That's why in the split-container-pr #1138, I had to change the `run: ls -1dt target/cryostat-itest-*.log | head -n1 | xargs cat` -> `cryostat-itests`. 
The pom.xml here on this line: 
https://github.com/cryostatio/cryostat/blob/132459fbefed742f00c26058b184b2889f790aa3/pom.xml#L633
outputs the file as `cryostat-itest-timestamp.log` while the script does `cryostat-itests-timestamp.log` since `cryostat.itest.containerName="cryostat-itest"`. 
Which should be changed here?

fix(ci): add ITEST_IMG_VERSION arg to repeated-tests bash script

---

.mergify.yml

Related to #1139
The current config prevents Mergify from dismissing others' change requests when PRs are updated, but it doesn't stop it from dismissing approvals. Our GitHub repo settings mostly enforce this idea anyway so it's redundant for Mergify to do it. However, the GitHub version is nicer because it allows approvals to remain if a reviewer uses the "Update branch" button on the PR to merge/rebase the PR.

ci(mergify): only dismiss own review approvals

---

pom.xml

The following should succeed to build the Java artifacts for Cryostat:
`mvn -DskipBaseImage=true -DskipITs=true -Djib.skip=true -DimageBuilder=false clean verify`
Fixes: #1159

build(pom): optionally skip building base image

---

.github/workflows/ci-jobs.yml
.github/workflows/ci.yaml
.github/workflows/pr-ci.yml
.github/workflows/push-ci.yml
.mergify.yml
README.md

ci(oci): push PR test images to ghcr

---

.github/workflows/ci-jobs.yml
.github/workflows/pr-ci.yml
.github/workflows/push-ci.yml

`push-to-quay` is currently broken since #1133: https://github.com/cryostatio/cryostat/actions/runs/3329598845/jobs/5507297247
The way to pass data using `outputs` from a reusable workflow into the caller is described here: https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow

fix(ci): correct image version pass between workflows

---

.github/workflows/ci-jobs.yml
.github/workflows/pr-ci.yml

Related to #1133
Previous PR to change the trigger event to `pull_request_target` changes the runner context to the base repo's. This means the `checkout` action in various CI steps is actually just checking out the upstream `main` branch, rather than the PR branch. This update corrects the `checkout` action to check out the PR branch for PRs, or leave it as the defaults after final push. This is what we talked about on an earlier call and is what we thought the new PR flow would actually be doing.

ci(checkout): check out correct fork/branch during PR CI run

---

src/main/java/io/cryostat/net/web/http/api/v2/graph/StartRecordingOnTargetMutator.java
src/main/resources/types.graphqls
src/test/java/itest/GraphQLIT.java

Fixes #1178
Manual testing steps:
```bash
$ http -v :8181/api/v2.2/graphql Authorization:"Basic $(echo user:pass | base64)" query="{ targetNodes(filter: { name: \"service:jmx:rmi:///jndi/rmi://cryostat:9091/jmxrmi\" }) { doStartRecording(recording: { name:\"foo\", template:\"Profiling\", templateType:\"TARGET\", duration: 10 }) { name } } }"
```
(will probably need to separately define JMX keyring credentials for the Cryostat target)
This query starts a recording without specifying or reading `archiveOnStop` and should work identically before and after the PR.
```bash
$ http -v :8181/api/v2.2/graphql Authorization:"Basic $(echo user:pass | base64)" query="{ targetNodes(filter: { name: \"service:jmx:rmi:///jndi/rmi://cryostat:9091/jmxrmi\" }) { doStartRecording(recording: { name:\"bar\", …
```

fix(graphql): expose archiveOnStop property in doStartRecording settings

---

devserver.sh
pom.xml

Related to #1160
Related to #1083
- don't compile tests if tests are skipped
- set JMX keyring password and skip building base image

fix(devserver): correct devserver setup for other changes

---

smoketest.sh

Related to https://github.com/cryostatio/cryostat-agent/pull/9
Related to https://github.com/cryostatio/cryostat/issues/520
Related to https://github.com/cryostatio/cryostat/issues/760
Just a basic example using https://github.com/andrewazores/quarkus-test with the `cryostat-agent` built into the image and configured with the handful of env vars needed. The `:0.0.9` image referenced is built with the `jwt-flow` agent PR branch. As we clear some of the backlog on the agent itself and get it into better shape as a discovery plugin then we can start configuring projects to pull in the agent as a dependency from GitHub Packages (the agent already [publishes Maven artifact JARs there](https://github.com/cryostatio/cryostat-agent/packages/1601815)) and use that for development iterations on the …

test(smoketest): replace quarkus-test container with agent-equipped

---

src/main/java/io/cryostat/discovery/DiscoveryStorage.java
src/main/java/io/cryostat/platform/ServiceRef.java
src/test/java/io/cryostat/discovery/DiscoveryStorageTest.java
src/test/java/io/cryostat/platform/internal/CustomTargetPlatformClientTest.java
src/test/java/io/cryostat/platform/internal/DefaultPlatformClientTest.java
src/test/java/io/cryostat/platform/internal/KubeApiPlatformClientTest.java
src/test/java/io/cryostat/platform/internal/KubeEnvPlatformClientTest.java

Fixes https://github.com/cryostatio/cryostat-web/issues/493
Before fixing tests, was there a reason that the notifications were in the previous order?
The only "issue" is that the LOST target will eventually notify Cryostat that it was lost but nothing will be done, (no notifications emitted since the subtree will be the same), but this is just unnecessary work. 
I will test this on my own through OpenShift to make sure that it doesn't break that functionality.

fix(discovery): allow targets restarting quickly using JDP to render correctly on the -web

---

src/container/include/cryostat.jfc
src/main/java/io/cryostat/Cryostat.java
src/main/java/io/cryostat/net/web/WebServer.java
src/main/java/io/cryostat/net/web/http/api/v2/ApiGetHandler.java
src/main/java/io/cryostat/net/web/http/generic/RequestLoggingHandler.java
src/main/resources/logging.properties
src/test/java/io/cryostat/net/web/http/generic/RequestLoggingHandlerTest.java

Fixes #1191
Fixes #1192
- fix(api): GET /api returns properly serialized endpoint verb
- chore(log): replace request logging with Vertx impl
- correct event name and move into logging handler

fix(api): fix GET /api serialization and webserver JFR event

---

pom.xml

build(deps): bump graphql-java-extended-scalars from 17.0 to 19.0

---

README.md
devserver.sh
pom.xml
repeated-integration-tests.bash
run.sh
smoketest.sh

Fixes #1247
Fixes #1248
- chore(devserver): replace xpath with 'mvn help:evaluate'
- chore(run.sh): replace xpath with 'mvn help:evaluate'
- chore(smoketest.sh): replace xpath with 'mvn help:evaluate'
- chore(run.sh): use project version from pom for version to run

chore(scripts): replace xpath with 'mvn help:evaluate' and default to running version tagged image

---

smoketest.sh

Fixes #1253
The previous setup had two different `quarkus-test` app instances configured to use their own built-in Discovery Plugin implementation in application code, plus another third instance configured to use an early build of the Cryostat Agent to act as the associated Discovery Plugin. These configs created conflicts where two plugins tried to register with the same information, and also resulted in the containers being unable to shut down cleanly because the Agent code does not yet properly handle being improperly initialized and missing some of the expected environment variables/system properties.
These things could be fixed by correcting the configs for the applications' plugin implementations and fixing the broken bad state handling in the agent, but it was quicker, easier, and …

chore(smoketest): correct conflicting discovery plugins

---

src/main/java/io/cryostat/configuration/CredentialsManager.java
src/main/java/io/cryostat/net/web/http/api/v2/TargetsPostHandler.java
src/main/java/io/cryostat/recordings/JvmIdHelper.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetsPostHandlerTest.java
src/test/java/itest/CustomTargetsIT.java
src/test/java/itest/util/http/StoredCredential.java

Related to https://github.com/cryostatio/cryostat-web/issues/592
This added the back-end support for test connection UI via `dryrun` query parameter. I chose another status code for JMX Auth Failure here is to avoid returning `427` that triggers openning up Auth Modal in the front-end. Another way is to re-use 427 but there must be a way for the front-end to know which requests are dryruns (i.e. maybe a custom header?)
**Manual Tests**
Using `localhost:9091` here to go around duplicate target error:
- With credentials
```bash
https --form POST https://localhost:8181/api/v2/targets?dryrun=true \
connectUrl='service:jmx:rmi:///jndi/rmi://localhost:9091/jmxrmi' \
alias="self" \
username="smoketest" \
password="smoketest" \
--verify=no \
--auth user:pass \
--auth-type basic
```
For non-dryrun …

feat(targets): dryrun query params for testing connectUrl and credentials

---

docs/HTTP_API.md

Signed-off-by: Thuan Vo <thvo@redhat.com>
Related to #1257 
Added api docs for the new "test connection" support for `POST api/v2/targets`.
See https://github.com/cryostatio/cryostat-web/issues/592

docs(api): add documentation on POST target dryrun

---

.github/workflows/ci-jobs.yml
pom.xml

Related to https://github.com/cryostatio/cryostat-core/issues/92
See also https://github.com/cryostatio/cryostat-reports/pull/63
This replaces the inlined `-core` build with simply retrieving the artifact from the GitHub Packages repository for the dependency.
This simplifies the CI setup and should also reduce the total CI run time since the artifact is built once (on release) and then each consuming project should cache it, or at worst redownload it rather than rebuild it.

build(core): use -core 2.16.2 from GH pkgs

---

.github/workflows/ci-jobs.yml
.github/workflows/pr-ci.yml
.github/workflows/push-ci.yml

Related to #1304
Secrets are not passed from the "real" GitHub Actions workflow into the composable reusable workflows by default, which I believe is causing the current CI failures (ex. https://github.com/cryostatio/cryostat/actions/runs/3761519894/jobs/6393388169).
According to https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow , it's as easy as setting the secrets to be inherited by the reusable workflow since they are both in our org.

ci(secret): pass secrets to reusable workflows

---

.github/workflows/ci-jobs.yml

ci(github): use maven batch mode and force updates

---

pom.xml
src/main/java/io/cryostat/discovery/DiscoveryStorage.java
src/main/java/io/cryostat/net/AgentConnection.java
src/main/java/io/cryostat/net/AgentConnectionFactory.java
src/main/java/io/cryostat/net/AgentJFRService.java
src/main/java/io/cryostat/net/NetworkModule.java
src/main/java/io/cryostat/net/TargetConnectionManager.java
src/main/java/io/cryostat/recordings/JvmIdHelper.java
src/test/java/io/cryostat/net/TargetConnectionManagerTest.java

Fixes: #1300
Fixes: #1310
See also https://github.com/cryostatio/cryostat-agent/pull/26
Depends on https://github.com/cryostatio/cryostat-core/pull/171
This change allows Discovery Plugins to include a computed JVM ID for the targets they are publishing about. This is intended primarily for Agents where the discovery plugin is also the target itself. This also implements a stubbed out `JFRConnection` implementation that represents an HTTP remote Cryostat Agent. Currently this stub does not actually talk to the Agent at all - see #1309.
Allowing plugins to publish their own JVM IDs must be done carefully - the plugin and Cryostat should always agree on the same ID for each target, so in effect both Cryostat and the plugin should use the same …

feat(agent): relax JMX connection requirements to support agent connection stubs

---

README.md
src/main/java/io/cryostat/configuration/Variables.java
src/main/java/io/cryostat/platform/internal/KubeApiPlatformClient.java
src/main/java/io/cryostat/platform/internal/KubeApiPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/OpenShiftPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/PlatformStrategyModule.java
src/test/java/io/cryostat/platform/internal/KubeApiPlatformClientTest.java

Related to #1188
Related to #760
Related to https://github.com/cryostatio/cryostat-operator/issues/501
~~The primary change is a one-liner: `k8sClient.endpoints().inNamespace(namespace) -> k8sClient.endpoints().inAnyNamespace()`. This also does a bit of refactoring.~~
This updates the `KubeApiPlatformClient` class, which is the internal implementation that handles the `Endpoints` querying discovery behaviour, to not be restricted to only querying for `Endpoints` objects within the same `Namespace` that the Cryostat container is running within. A new `CRYSOTAT_K8S_NAMESPACES` environment variable is added. The variable's value is expected to be a comma-separated list of namespace names. The `KubeApiPlatformClient` sets up an `Informer` for …

feat(discovery): enable OpenShift cross-namespace discovery

---

pom.xml
src/main/java/io/cryostat/discovery/DiscoveryStorage.java
src/main/java/io/cryostat/platform/ServiceRef.java
src/main/java/io/cryostat/platform/internal/KubeApiPlatformClient.java
src/main/java/io/cryostat/rules/RuleProcessor.java
src/test/java/io/cryostat/discovery/DiscoveryStorageTest.java
src/test/java/io/cryostat/platform/internal/KubeApiPlatformClientTest.java

Fixes:  https://github.com/cryostatio/cryostat-web/issues/805
Depends on https://github.com/cryostatio/cryostat-core/pull/172
Front-end should be able to display newly computed jvmIds.
1. `Run CRYOSTAT_IMAGE=quay.io... sh smoketest.sh...`
2.  Choose any target with authentication (and no backend-saved credentials). See jvmId is null.
3. Add credentials.
4. See the updated jvmIds.

fix(discovery): should send notifications on credential store update

---

.github/workflows/labeler.yml

Fixes: #1334 
Allows github-actions bot to only apply the `needs-triage` label when a pull request is opened or re-opened. Also see https://github.com/cryostatio/cryostat/issues/1194#issuecomment-1384723406
See #1334. This is annoying as every time someone added commits or force pushed, the label is applied and we need to remove it again in order for CI tests to run.
1. None

fix(ci): fix github label from being applied on every pull-request target action

---

src/main/java/io/cryostat/platform/internal/KubeApiPlatformClient.java
src/test/java/io/cryostat/platform/internal/KubeApiPlatformClientTest.java

Fixes: #1337
(nice)
This applies a simple transformation to the JMX service URLs published by the internal k8s discovery mechanism. Rather than constructing the URL simply by the Endpoints `$ip:$port`, it is transformed to `$ip-dashes.$namespace.pod:$port` according to https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods .
This will end up resolving to the same backing Pod, but it is a little more explicit about what is being connected to. In #1188 the namespace information embedded in the connection URL will be used to determine the security context to apply to data originating from that target, and all target definitions will be required to be defined with a connection URL conforming to such a platform-specific …

feat(k8s): publish discovered targets using k8s internal pod URL

---

src/main/java/io/cryostat/net/web/http/api/beta/ReportGetFromPathWithJwtHandler.java
src/main/java/io/cryostat/net/web/http/api/beta/ReportGetWithJwtHandler.java
src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
src/test/java/io/cryostat/net/web/http/api/beta/ReportGetFromPathWithJwtHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/beta/ReportGetWithJwtHandlerTest.java

Fixes: #1340 
This change makes some jwt report get handlers non-async. Having them as `async` was causing a timeout due to the vertx event loop being blocked while waiting for a report response from the reports sidecar.
See #1340 
It makes sense that we wouldn't want these handlers async since we are actively waiting on a http response ourselves and are planning to return it.
1. Run cryostat normally with smoketest
2. Create a recording and archive it after a few seconds. 
3. Press view report on the kebab  (this uses the jwt handler) (Do not view a report within the iframe as this caches the report).
4. Notice that the report is generated without a timeout as opposed to before.

fix(reports): fix "view report" failure timing out on jwt report get handlers

---

certs/generate-dev-certs.sh

Signed-off-by: Andrew Azores <aazores@redhat.com>
Fixes #1353
Replaces a hardcoded path (assumes JDK11 installed in a Fedora-like location) with `$JAVA_HOME`

chore(dev): use JAVA_HOME instead of hardcoded path

---

src/main/java/io/cryostat/net/web/WebServer.java
src/main/java/io/cryostat/net/web/http/HttpModule.java
src/main/java/io/cryostat/net/web/http/api/beta/RecordingUploadPostFromPathHandler.java
src/main/java/io/cryostat/net/web/http/api/beta/RecordingUploadPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/RecordingUploadPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingUploadPostHandler.java
src/test/java/io/cryostat/net/web/http/api/beta/RecordingUploadPostFromPathHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/beta/RecordingUploadPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/RecordingUploadPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingUploadPostHandlerTest.java
src/test/java/itest/UploadRecordingIT.java

Related to https://github.com/cryostatio/jfr-datasource/pull/153
Routes that post jfr file to datasource should now use query paramter `overwrite=true` and hardcoded name `cryostat-analysis.jfr`.
[See  https://github.com/cryostatio/jfr-datasource/issue/152](https://github.com/cryostatio/jfr-datasource/issues/152)

fix(datasource): enable overwrite and use hardcoded filename

---

devserver.sh
repeated-integration-tests.bash
run.sh
smoketest.sh

Fixes: #1355 
This allows cryostat dev setup to be faster with xpath if it is available vs. using `mvn:evaluate`.
1. Have optional xpath installed 
2. Run `sh smoketest.sh` with this pr changes, and without and see the difference.

chore(scripts): use `xpath` in cryostat dev scripts if available

---

src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/StartRecordingOnTargetMutator.java
src/main/java/io/cryostat/recordings/RecordingTargetHelper.java
src/main/resources/types.graphqls
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandlerTest.java

Related to https://github.com/cryostatio/cryostat-web/issues/847
This change adds parameters for the HTTP API and GraphQL API endpoint/fetcher for starting new recordings. The new parameter allows the client to specify that the recording should be "restarted" (closed/removed remotely and recreated) if a recording with the same name already exists on the target. This same logic is already implemented internally and used by Automated Rules, so this simply extends it to the explicit recording creation API entrypoints.
This is useful for the embedded charts dashboard views since those need to be backed by an active and running recording. If this recording has been previously created but some client stopped it without removing it, this parameter …

feat(activerecordings): add param for restarting existing recording definitions

---

src/main/java/io/cryostat/platform/internal/DefaultPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/KubeApiPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/KubeEnvPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/OpenShiftPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/PlatformStrategyModule.java

Fixes: #1365
This removes the own-namespace from being implicitly included in the list of watched namespaces in k8s environments.
The end user, or managing Cryostat Operator, should explicitly list any and all namespaces that they want the Cryostat instance to watch. The implicit inclusion of Cryostat's own namespace restricted users' choices since it was not previously possible to have Cryostat *not* watch that namespace and discover itself.
1. Deploy test image in k8s environment
2. Set `CRYOSTAT_K8S_NAMESPACES` environment variable to ex. `CRYOSTAT_K8S_NAMESPACES=myns1,myns2`.
3. Using the HTTP API or web-client, check if Cryostat discovers itself. Repeat steps 2 and 3 including (or not) the Cryostat deployment namespace in the list.

fix(k8s): no implicit own-namespace watching

---

src/main/java/io/cryostat/rules/MatchExpressionEvaluator.java
src/test/java/io/cryostat/rules/MatchExpressionEvaluatorTest.java
src/test/java/io/cryostat/rules/MatchExpressionValidatorTest.java

Related to #1377
Related to #1389
This copies the `jvmId` field from the `ServiceRef` object representing a target application into the object binding passed into the JS engine when evaluating a match expression.
Without this, the `jvmId` property tested in the `matchExpression` will always be an undefined value, leading to expressions that do not properly test and evaluate against the intended targets. In #1377 Cryostat is still able to use the credentials to authenticate to -agents because the lookup is direct by stored credential ID rather than evaluating the associated expression, but this bug does actually manifest in the web-client since it is visible on the `/security` view that the agents' stored credentials display as matching …

fix(matchexpr): include jvmId in js binding

---

src/main/java/io/cryostat/Cryostat.java
src/main/java/io/cryostat/net/security/ResourceAction.java
src/main/java/io/cryostat/net/web/http/api/beta/HttpApiBetaModule.java
src/main/java/io/cryostat/net/web/http/api/beta/MatchExpressionDeleteHandler.java
src/main/java/io/cryostat/net/web/http/api/beta/MatchExpressionGetHandler.java
src/main/java/io/cryostat/net/web/http/api/beta/MatchExpressionsGetHandler.java
src/main/java/io/cryostat/net/web/http/api/beta/MatchExpressionsPostBodyHandler.java
src/main/java/io/cryostat/net/web/http/api/beta/MatchExpressionsPostHandler.java
src/main/java/io/cryostat/rules/MatchExpression.java
src/main/java/io/cryostat/rules/MatchExpressionDao.java
src/main/java/io/cryostat/rules/MatchExpressionManager.java
src/main/java/io/cryostat/rules/RulesModule.java
src/main/resources/META-INF/persistence.xml
src/test/java/io/cryostat/net/web/http/api/beta/MatchExpressionDeleteHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/beta/MatchExpressionGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/beta/MatchExpressionsGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/beta/MatchExpressionsPostHandlerTest.java
src/test/java/io/cryostat/rules/MatchExpressionManagerTest.java

Fixes: https://github.com/cryostatio/cryostat/issues/1386
This change adds MatchExpressions as a top level resource to Cryostat. We can use these to query matched targets that are associated with a MatchExpression. This change adds handlers that help with associating targets with rules and targets with credentials and vice versa. 
The endpoints are 
GET /api/beta/matchExpressions (getAll stored MatchExpressions)
GET /""/matchExpression/:id (get stored MatchExpression using id)
POST /""/matchExpressions (add MatchExpression) (with form parameters `matchExpression` and `targets`)
DELETE /""/matchExpressons/:id (delete MatchExpression using id)
**the `matchExpression` is required**
**the `targets` is optional and if it is a valid array of …

feat(match-expr): add `MatchExpression` resource

---

src/main/java/io/cryostat/net/web/http/api/v2/graph/StartRecordingOnTargetMutator.java

Fixes: #1403 
Allows restart to be specified by a boolean parameter.
Try a query like:
```
// will fail
query($episode: String! = "ASD") { 
targetNodes(filter: { annotations: "PORT == 9093" }) {
doStartRecording(recording: { 
name: "graph-itest", 
duration: 30,
template: "Profiling", 
templateType: "TARGET", 
metadata: {
labels: {
cryostatiotopologygroup: $episode,
} 
},
restart: "true",
})
{ 
name state duration 
}
} 
}
```
vs
```
// correct
query($episode: String! = "ASD") { 
targetNodes(filter: { annotations: "PORT == 9093" }) {
doStartRecording(recording: { 
name: "graph-itest", 
duration: 30,
template: "Profiling", 
templateType: "TARGET", 
metadata: {
labels: {
cryostatiotopologygroup: $episode,
} 
},
restart: true,
})
{ 
name state …
```

fix(graphql): use boolean parameter for StartRecordingMutator `restart`

---

src/main/java/io/cryostat/net/web/http/api/v2/graph/StartRecordingOnTargetMutator.java
src/test/java/itest/GraphQLIT.java

Fixes: #1407 
Use array format for label input similar to metadata mutator.
See #1407 
Try this query:
```graphql
query StartRecordingForGroup() {
environmentNodes(filter: { name: "JDP" }) {
descendantTargets {
doStartRecording(recording: {
name: "foo",
template: "Continuous",
templateType: "TARGET",
duration: 0,
restart: true,
metadata: {
labels: [
{
key: "cryostat.io.topology-group",
value: "JDP"
}
]
},
}) {
name
state
}
}
}
}
```

fix(graphql): use array format as label input

---

src/main/java/io/cryostat/net/web/http/api/v2/TargetsPostHandler.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetsPostHandlerTest.java
src/test/java/itest/CustomTargetsIT.java

Fixes: #1404 
This change allows the Custom Target creation post handler to use credentials in the dao directly (also check session credentials if any). This is because before, the handler would query existing targets in the database and find and use any credentials that match a target using the credentials match expression. 
Tests not fixed yet just to confirm that this implementation is what is needed for the web-client to use. 
1. Run the pr.
2. Create a credential with a match expression that matches a custom target that you want to add (e.g. `target.connectUrl == "service:jmx:rmi:///jndi/rmi://localhost:9091/jmxrmi"`)
3. Go to topology view to add custom target.
4. Use the connectUrl (e.g. …

fix(custom-targets): fix adding jmx-auth custom targets 

---

src/main/java/io/cryostat/discovery/AbstractNodeTypeAdapter.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/EnvironmentNodesFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/FilterInput.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/TargetNodeRecurseFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/TargetNodesFetcher.java
src/main/java/io/cryostat/platform/discovery/AbstractNode.java
src/main/java/io/cryostat/platform/discovery/EnvironmentNode.java
src/main/java/io/cryostat/platform/discovery/TargetNode.java
src/main/resources/types.graphqls
src/test/java/itest/GraphQLIT.java

Fixes: #1410
This adds an `id` property to discovery nodes. At the moment this is just the object's `hashCode`, but in the future it should be a database ID that is truly unique and stable. That's a much deeper change since it means each individual node should be registered into the database, not just subtrees as published by discovery plugins. Since the `id` is currently "pseudo-unique" and also not stable for a given node (consider what would happen to a Deployment if it were scaled up), this `id` should right now only be used for a single request to ensure that the correct node is selected in cases where the client wants to perform an action against one specific node that may otherwise be ambiguous. Clients should not retain these `id`s …

feat(discovery): add int id property to nodes

---

src/main/resources/types.graphqls

Related to https://github.com/cryostatio/cryostat-web/pull/906
Remove non-null constraints for active recording actions. This allows data to be returned when an error occurs.
See https://github.com/cryostatio/cryostat-web/pull/906#discussion_r1137825159
Try on JDP group with some targets that cannot start/stop/delete recordings. Check the response for the `data` field.
```graphql
query StartRecordingForGroup() {
environmentNodes(filter: { name: "JDP" }) {
name
descendantTargets {
name
doStartRecording(recording: {
name: "foo",
template: "Continuous",
templateType: "TARGET",
duration: 0,
restart: true,
metadata: {
labels: [
{
key: "cryostat.io.topology-group",
value: "JDP"
}
]
},
}) {
name
state
}
}
}
}
```
```graphql
query …
```

fix(graphql): remove non-null constraints for active recs action

---

src/main/java/io/cryostat/net/AgentClient.java
src/main/java/io/cryostat/net/AgentConnection.java
src/main/java/io/cryostat/net/AgentJFRService.java
src/main/java/io/cryostat/net/NetworkModule.java

See #1415
Related to #1416
Related to #1309
Related to #520
Just like #1415, but for event types and event templates querying instead of MBean metrics.
Same as before
Needs https://github.com/cryostatio/cryostat-agent/pull/80
Testing procedure is the same as before, but this time go to the Events view. The event types and templates tables should populate.

feat(agent): implement HTTP-based event types and templates queries to -agents

---

src/main/java/io/cryostat/net/AgentClient.java
src/main/java/io/cryostat/net/AgentJFRService.java

See #1415 #1419
Related to #1416
Related to #1309
Related to #520
Like #1415 and #1419. This one queries information about active recordings.
Same as before
Needs https://github.com/cryostatio/cryostat-agent/pull/82
Apply the following patch:
```diff
diff --git a/smoketest.sh b/smoketest.sh
index 4aebf722..15dbd3f4 100755
--- a/smoketest.sh
+++ b/smoketest.sh
@@ -158,7 +158,7 @@ runDemoApps() {
--env CRYOSTAT_AGENT_BASEURI="${protocol}://localhost:${webPort}/" \
--env CRYOSTAT_AGENT_TRUST_ALL="true" \
--env CRYOSTAT_AGENT_AUTHORIZATION="Basic $(echo user:pass | base64)" \
-        --env CRYOSTAT_AGENT_REGISTRATION_PREFER_JMX="true" \
+        --env CRYOSTAT_AGENT_REGISTRATION_PREFER_JMX="false" \
--env …
```

feat(agent): implement HTTP-based recordings queries to -agents

---

src/main/java/io/cryostat/jmc/serialization/HyperlinkedSerializableRecordingDescriptor.java
src/main/java/io/cryostat/recordings/RecordingTargetHelper.java
src/test/java/io/cryostat/recordings/RecordingTargetHelperTest.java

Fixes #1428 
Correct the descriptor state before sending notifications.
See #1428 
1. `Run CRYOSTAT_IMAGE=quay.io... sh smoketest.sh...`
2. Create any recording then stop it. Observe the payload containing a recs that has STOPPED state.

fix(noti): set STOPPED state for ActiveRecordingStopped notifications

---

src/main/java/io/cryostat/net/AgentClient.java
src/main/java/io/cryostat/net/web/http/api/beta/CredentialTestPostBodyHandler.java
src/main/java/io/cryostat/net/web/http/api/beta/CredentialTestPostHandler.java
src/main/java/io/cryostat/net/web/http/api/beta/HttpApiBetaModule.java
src/test/java/io/cryostat/net/web/http/api/beta/CredentialTestPostHandlerTest.java

Fixes: #1431
Adds an endpoint to specifically test JMX connection  w/credentials to a target JVM at `/beta/credentials/:targetId`
The endpoint from the backend should query these targets themselves with the supplied credentials, and give a resulting output as the response body.
They should return status=`NA` for "this target does not need credentials, status=`SUCCESS`, this target is authenticated with these supplied credentials, and status=`FAILURE`, which means these credentials can not be authenticated with these credentials. 
See #1431
1. Run with smoketest setup.
2. Try these queries:
```bash
http --form --auth=user:pass POST localhost:8181/api/beta/credentials/service%3Ajmx%3Armi%3A%2F%2F%2Fjndi%2Frmi%3A%2F%2Flocalhost%3A9095%2Fjmxrmi/ …
```

feat(credentials): add credentials test endpoint

---

src/main/java/io/cryostat/net/web/http/api/v2/DiscoveryRegistrationCheckHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/HttpApiV2Module.java

Related to https://github.com/cryostatio/cryostat-agent/issues/85
This adds a `GET` endpoint that plugins can use with their existing registration ID and token to check their registration status. The API response is 200 if the plugin is registered and the token is still valid, 401 if the token is invalid, and 404 if the token is somehow valid but the plugin is not registered (this should be impossible - if the plugin is not registered then any token it still has should be invalid).
This is used by the `-agent` to perform its own periodic heartbeat checks on the Cryostat server at a slower cadence. If the plugin notices that it cannot reach Cryostat, or that Cryostat no longer recognizes it as a registered plugin, then the `-agent` re-enters …

feat(discovery): add endpoint for plugins to check their registration

---

pom.xml
src/main/java/io/cryostat/net/openshift/OpenShiftNetworkModule.java
src/main/java/io/cryostat/net/reports/SubprocessReportGenerator.java
src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
src/main/java/io/cryostat/recordings/RecordingMetadataManager.java
src/main/java/io/cryostat/rules/RuleRegistry.java

Fixes: #1444
Depends on https://github.com/cryostatio/cryostat-core/pull/207 (these changes are really separate, but I want to update `-core` and include that dependency update in this same PR for simplicity)
This simply closes some file descriptors that are currently leaked.
Don't leak resources over time.
See test procedure in https://github.com/cryostatio/cryostat-core/pull/207 . Same thing applies. `ls -l /proc/$pid/fd` is useful for checking which descriptors look like they've been leaked. I used the following to ease tracing where those descriptors got opened:
https://github.com/jenkinsci/lib-file-leak-detector downloaded and placed into my `cryostat/clientlib` project directory, named as `file-leak-detector.jar`.
```diff
diff --git …
```

fix(fd): close leaked file descriptors

---

src/main/java/io/cryostat/rules/RuleProcessor.java

Fixes: #1288 
The change fixes a bug where a listener which listened for the adding of new credentials, actually activated rules on matched targets even if they were already active.
Follow the steps outlined in #1288

fix(rules): credential-activated rules no longer activate on targets with the rule already active

---

docs/HTTP_API.md
src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
src/test/java/io/cryostat/discovery/DiscoveryStorageTest.java
src/test/java/io/cryostat/net/web/http/api/beta/ArchivedDirectoriesGetHandlerTest.java
src/test/java/io/cryostat/recordings/RecordingArchiveHelperTest.java
src/test/java/itest/FileSystemArchivedRequestsIT.java

Related https://github.com/cryostatio/cryostat/pull/1110
Prior to this bug fix, the web ui would render the wrong data. (It was rendering the base32 encoding of the jvmId hash in the tooltip instead of the hash itself.)
Fixed: 
This should change nothing else other than the http response from the associated get handler.

fix(archive-directories): fix incorrect data in archived directory get response

---

pom.xml
repeated-integration-tests.bash
smoketest.sh

chore(test): add config to skip pulling test images

---

smoketest.sh

chore(smoketest): update vertx-fib-demos to version with -agent

---

pom.xml
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingPatchHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/DiscoveryPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/RequestParameters.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/GraphQLPostHandler.java
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingPatchHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/AbstractV2RequestHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/CertificatePostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/DiscoveryPostHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetRecordingOptionsListGetHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/TargetSnapshotPostHandlerTest.java

Fixes: #1203
This clears deprecation warnings from the Vert.x 4.3.0 upgrade.
Deprecated code may be removed so we should no longer rely on it.
1. `mvn compile compile`
2. Verify output that no deprecation warnings appear for Vert.x Web methods.

chore(vertx): avoid deprecated methods

---

src/main/java/io/cryostat/discovery/BuiltInDiscovery.java
src/main/java/io/cryostat/discovery/DiscoveryModule.java
src/main/java/io/cryostat/net/NetworkModule.java
src/main/java/io/cryostat/platform/PlatformModule.java
src/main/java/io/cryostat/platform/internal/CustomTargetPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/DefaultPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/KubeApiPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/OpenShiftPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/PlatformDetectionStrategy.java
src/main/java/io/cryostat/platform/internal/PlatformStrategyModule.java
src/main/java/io/cryostat/platform/internal/PodmanPlatformClient.java
src/main/java/io/cryostat/platform/internal/PodmanPlatformStrategy.java

Fixes: #1505
This does some refactoring to ensure that the Custom Targets functionality is always available, even when the environment variable `CRYOSTAT_DISABLE_BUILTIN_DISCOVERY` is set, and so that setting that environment variable does not result in a startup-blocking exception.
It may be useful in some situations to disable the built-in discovery mechanisms entirely. A Cryostat instance locked down in this way can be sure to never discover any target applications other than ones registered manually using Custom Targets, or ones configured using the Cryostat Agent.
1. `CRYOSTAT_IMAGE=quay.io... CRYOSTAT_DISABLE_BUILTIN_DISCOVERY=true sh smoketest.sh`
2. Verify that the container started successfully
3. `https :8181/api/v2.1/discovery` to …

fix(discovery): fix broken DISABLE_BUILTIN_DISCOVERY env var

---

run.sh
smoketest.sh
src/main/java/io/cryostat/platform/internal/PlatformStrategyModule.java
src/main/java/io/cryostat/platform/internal/PodmanPlatformClient.java
src/main/java/io/cryostat/platform/internal/PodmanPlatformStrategy.java

Fixes: #1513
Depends on #1511
Related to #1503
Related to #1394
This updates the `PodmanPlatformClient` to discover target JMX URLs as follows:
1. Query for containers with the `io.cryostat.discovery` label, then:
2. Check for the `io.cryostat.jmxUrl` label. If it is present, use that. Else continue:
3. Check for the `io.cryostat.jmxPort` label. If it is present, use this to construct the JMX URL.
4. Check for the `io.cryostat.jmxHost` label. If it is not present, default to retrieving the container's hostname from the Podman API. Use this with the `jmxPort` above to construct the JMX URL.
Since there are now two main routes (`jmxUrl`, which replaces the previous `connectUrl`, or `jmxHost`+`jmxPort`), and the Podman HTTP API does not support …

feat(podman): use labels to specify JMX port and optionally host

---

smoketest.sh

Related to https://github.com/cryostatio/cryostat-agent/pull/135
Updates `vertx-fib-demo` container images to one that includes latest `cryostat-agent` version.
See linked issue
2. Check Security view and ensure that the agents' stored credentials refer to their own callback URLs / HTTP API URLs, not the target JVM ID

chore(smoketest): update container versions for latest cryostat-agent

---

src/main/java/io/cryostat/platform/internal/PodmanPlatformClient.java
src/main/java/io/cryostat/platform/internal/PodmanPlatformStrategy.java

Related to #1514
Executes the Podman API request for listing containers on the Vert.x context, and the subtask request for inspecting individual containers (if needed: no jmxHost label or jmxUrl label) on a worker thread.
This fixes a bug where the executor thread gets blocked when it needs to list containers and then further inspect them. This blockage results in failure of the platform client to discover containers.
1. Apply the patch below, then:
2. Run CRYOSTAT_IMAGE=quay.io... sh run.sh...
```patch
diff --git a/run.sh b/run.sh
index 9d322386..e58ca4f7 100755
--- a/run.sh
+++ b/run.sh
@@ -123,9 +123,7 @@ podman run \
--name cryostat \
--user 0 \
--label io.cryostat.discovery="true" \
-    --label io.cryostat.jmxHost="localhost" \
- …
```

fix(podman): fix blocked thread on container inspection request

---

pom.xml
smoketest.sh

Related to https://github.com/cryostatio/cryostat-core/issues/217
Adds a Quarkus native image sample application to the smoketest.sh.
This makes it visible and convenient to test Cryostat functionality against a native image target.
2. *...*

test(smoketest): add native image sample app

---

pom.xml

Fixes: #1533
This adds Podman health probes to the containers started for integration testing, and changes the `wait-for-X` executions to query podman's view of container health as a startup check.
Rather than running a `timeout` command that forks subprocess shells executing `curl` to try to check the container availability externally, this ends up using a process run within the container to check for the service availability, which is reported to podman. From outside the containers we ask podman what the status is. This is less prone to getting into a bad state with `curl` trying to open a connection to the services in the containers when they are not yet ready to accept connections and causing `curl` to time out and therefore fail the …

test(itest): improve container startup health detection

---

README.md
pom.xml

Related to #1329
This adds some configuration to the `pom.xml` so that the build architecture (and OS, though this only makes sense to use `linux` now) can be changed by setting `-Dbuild.arch=arm64`. This will cause the image build to pull the specified architecture for the UBI layer, and to build the application image for that specified architecture as well. `qemu-user-static` (on Fedora, or equivalent package elsewhere) must be installed for this step to work, since part of building the application base image involves pulling the cross-arch UBI and running commands within it (ex. `microdnf`), so this part must be emulated to prepare the image.
Once we can verify that these images work as expected on real ARM hardware, we can continue to …

build(oci): add config to allow building images for other archs

---

.github/workflows/ci-jobs.yml
.github/workflows/pr-ci.yml
.github/workflows/push-ci.yml

Related to #1352
Re-incorporates CI workflow updates that somehow got dropped from previous PR.
This should hopefully result in multiarch manifest images being pushed to the `quay.io` repository on merge to `main`, and single-arch AMD64 images being built for PR review as usual.

ci(multiarch): build multiarch manifest image

---

.github/workflows/ci-jobs.yml
pom.xml
repeated-integration-tests.bash
run.sh

- test(run.sh): add healthcheck for cryostat container
- test(itest): poll only for relevant container status, echo to stderr for visibility
- fix(itest): wait for container health in same order as startup
- chore(itest): ensure container logs are captured in location expected by CI
- chore(itest): refactor
- ci(logs): print container log file on run failure
Related to #1541

ci(multiarch): better status checks and logging

---

src/main/java/io/cryostat/Cryostat.java
src/main/java/io/cryostat/discovery/BuiltInDiscovery.java

Fixes: #1546
This fixes a class cast exception that can occur when startup fails, and changes behaviour from failing startup if any built-in discovery mechanism fails to start to simply logging the cause.
Since all built-in discovery mechanisms are now tested by default and then automatically started, it is surprising/annoying when one of these failing (such as JDP on aarch64 at the moment) causes the whole server to not start.
1. `dnf install qemu-user-static`
2. `mvn clean package -Dbuild.arch=arm64 ; podman image prune -f`
3. `CRYOSTAT_IMAGE=quay.io/cryostat/cryostat:2.4.0-snapshot-linux-arm64 sh run.sh # or other image tag as produced above`

fix(startup): be tolerant of built-in discovery mechanism failures

---

.github/workflows/ci-build-image.yml
.github/workflows/pr-ci.yml
.github/workflows/push-ci.yml
pom.xml

Related to #1543
How to test:
ex. `bash repeated-integration-tests.bash 1 HealthIT`

ci(itest): print container health and latest logs on each readiness check

---

.github/workflows/push-ci.yml

ci(manifest): correct 'podman manifest create' invocation

---

.github/workflows/push-ci.yml

ci(manifest): corrections for multiarch manifest load and create

---

src/main/java/io/cryostat/net/web/http/api/v2/graph/ActiveRecordingsFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/ArchivedRecordingsFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/EnvironmentNodesFetcher.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/FilterInput.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/TargetNodesFetcher.java
src/main/resources/types.graphqls
src/test/java/io/cryostat/net/web/http/api/v2/graph/ActiveRecordingsFetcherTest.java
src/test/java/io/cryostat/net/web/http/api/v2/graph/ArchivedRecordingsFetcherTest.java
src/test/java/io/cryostat/net/web/http/api/v2/graph/EnvironmentNodesFetcherTest.java
src/test/java/io/cryostat/net/web/http/api/v2/graph/TargetNodesFetcherTest.java
src/test/java/itest/GraphQLIT.java

Fixes: #1433
*This change adds allows filtering of multiple names instead of just one name*
*This change is helpful because one can now filter multiple matching names with just one request instead of filtering one name at time for each request*
2. * mvn clean verify *
3. * mvn clean verify -Dit=tests=GraphQLIT.java*

feat(GraphQL): Add GraphQL filter ability for node name from set

---

smoketest.sh

test(smoketest): set jmxquarkus HTTP port to not conflict with jfr-datasource

---

.github/workflows/ci-build-image.yml
pom.xml
run.sh

Fixes: #1571
- test(itest): never pull Cryostat container from registry, require one present locally
- test(itest): use os/arch-specific image tag for testing
- test(run.sh): include image os/arch in default image to run
1. Check out this PR
2. `run.sh` then `podman ps` and ensure that the image run is like `quay.io/cryostat/cryostat:2.4.0-snapshot-linux-amd64`
3. `bash repeated-integration-tests.bash` and ensure that the image run is the same
4. `mvn clean verify` and ensure that the image run is the same, ie the one that is just built by the same run

test(itest): ensure correct latest built image is tested

---

src/main/extras/app/entrypoint.bash
src/main/java/io/cryostat/net/SslConfiguration.java

Fixes: #1507
This change allows enabling of SSL when CRYOSTAT_DISABLE_SSL is set to "false"
This change is helpful because users may want to sue a Secure Sockect Layer(SSL) where as he can just pass the environment variable to false i.e < CRYOSTAT_DISABLE_SSL=false>
1. Run `CRYOSTAT_IMAGE=quay.io... sh smoketest.sh...`
2. Run `CRYOSTAT_DISABLE_SSL=false sh smoketest.sh and test it by < http --verify=no https://localhost:8181/health`

fix(ssl): fixed env var behaves unexpectedly 

---

compose/compose-cryostat.yaml
compose/compose-vertx-jmx.yaml
smoketest-docker.sh
smoketest.sh
src/main/java/io/cryostat/discovery/DiscoveryStorage.java
src/main/java/io/cryostat/recordings/JvmIdHelper.java
src/test/java/io/cryostat/discovery/DiscoveryStorageTest.java
src/test/java/itest/bases/ExternalTargetsTest.java

fix(discovery): retry failed target connections

---

src/main/java/io/cryostat/net/web/http/api/beta/MatchExpressionsPostHandler.java
src/main/java/io/cryostat/rules/MatchExpressionEvaluator.java
src/test/java/io/cryostat/net/web/http/api/beta/MatchExpressionsPostHandlerTest.java
src/test/java/io/cryostat/rules/MatchExpressionEvaluatorTest.java

Fixes: #1601
This PR changes the content acception from formdata and url-encoded data to only accept a JSON body. For example: 
```json
{
"matchExpression": "asdf"
,"targets": 
[
{
"alias": "org.codehaus.plexus.classworlds.launcher.Launcher",
"annotations": {
"cryostat": {
"HOST": "macao",
"JAVA_MAIN": "org.codehaus.plexus.classworlds.launcher.Launcher",
"PORT": "9091",
"REALM": "JDP"
},
"platform": {}
},
"connectUrl": "service:jmx:rmi:///jndi/rmi://macao:9091/jmxrmi",
"jvmId": "6I8-ZE3qOC5TThRktZi7Y0V6FNNYdwbC2tYHgQVILeM=",
"labels": {}
}
]
}
```
See #1601 
1. Run cryostat with smoketest.sh
2. Try a query like:
```
http …
```

feat(matchExpression): POST matchExpression resource as json

---

src/main/java/io/cryostat/net/AgentClient.java
src/main/java/io/cryostat/net/AgentJFRService.java

Fixes #1581
Based on #1566
Depends on https://github.com/cryostatio/cryostat-agent/pull/176
Adds implementation to talk to the Cryostat Agent over HTTP for stopping and deleting flight recordings.
This continues the effort to bring Cryostat application feature parity between JMX and HTTP connection methods.
1. Same setup as in #1566
2. Use with https://github.com/cryostatio/cryostat-agent/pull/176
3. Test against the `smoketest.sh` `http://localhost:9988/` agent target. Go to the Cryostat Web UI, Recordings, Create, and check that a custom recording can be started, stopped, and deleted. Stop and delete requests should work on …

feat(agent): implement Agent HTTP dynamic JFR stop/delete

---

src/main/java/io/cryostat/net/AgentClient.java
src/main/java/io/cryostat/net/AgentJFRService.java
src/main/java/io/cryostat/net/web/WebServer.java
src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java
src/main/java/io/cryostat/util/URIUtil.java

Based on #1604
Depends on https://github.com/cryostatio/cryostat-agent/pull/179
Fixes #1582
This replaces stubs with real implementations for pulling JFR files from Cryostat Agent instances over HTTP.
Users can deploy their workload applications with the Cryostat Agent and dynamically start/analyze/retrieve/stop/delete recordings all over the Agent HTTP API rather than over JMX.
1. See #1604 and https://github.com/cryostatio/cryostat-agent/pull/179

feat(agent): implement Agent HTTP recording retrieval

---

src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/StartRecordingOnTargetMutator.java
src/main/java/io/cryostat/recordings/RecordingTargetHelper.java
src/main/java/io/cryostat/rules/RuleProcessor.java
src/main/resources/types.graphqls
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandlerTest.java
src/test/java/io/cryostat/recordings/RecordingTargetHelperTest.java
src/test/java/io/cryostat/rules/RuleProcessorTest.java
src/test/java/itest/GraphQLIT.java

Fixes: #1492 
*This change changes the previous behavior: query parameter ?restart=[true|false] but is now deprecated, and a new replacement ?replace=[always,stopped,never] introduced. ?replace=always would behave the same as ?restart=true, ?replace=never would behave the same as ?restart=false, and ?replace=stopped would implement the quoted behavior. If replace is not specified then it should behave like ?replace=never, so that this also maintains consistency and compatibility with the existing ?restart=false default behavior.
This change is helpful because it enhances the behavior of restart recording while keeping the same …

feat(replace-param): Fine-grained replacement parameter for Start Recording Mutator

---

run.sh
smoketest.sh

Related to https://github.com/cryostatio/cryostat/issues/1329
This sets `--cpu` and `--memory` flags on Cryostat component containers that match the defaults the `-operator` sets if the user does not provide overriding configurations.
With this configuration, we can get a better sense of what the resource requirements are for the various containers within one of the shorter development loops.
2. Test general functionality and ensure things still work. They will probably be much slower with this configuration - perhaps we need to raise some defaults.

test(smoketest): apply resource constraints matching operator deployment defaults

---

smoketest.sh

Related to https://github.com/cryostatio/jfr-datasource/pull/204
Depends on https://github.com/cryostatio/jfr-datasource/pull/204
After the above PR is merged, `jfr-datasource` images will be published in JVM mode and supporting JMX connections. This adds configuration matching how `cryostat-reports` is deployed in `smoketest.sh` since both containers are built similarly.
This allows `jfr-datasource` to be a JMX target in the smoketest environment.
2. Select the target with JMX port `11223`, which is the `jfr-datasource`. Test that general Cryostat functionality works on this …

test(smoketest): set jfr-datasource for JDP and Podman discovery

---

.github/workflows/ci-build-image.yml
.github/workflows/ci-code-analysis.yml
.github/workflows/pr-ci.yml

feat(ci): build_test PR command

---

pom.xml
src/main/java/io/cryostat/platform/internal/DockerPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/PodmanPlatformStrategy.java

Fixes: #1547
This adds properties+profiles for including/excluding Netty native transport (epoll), with x86_64/aarch_64 classifiers.
This dependency is used to enable the Vert.x web-client to communicate over Unix domain sockets, which is required for the Podman and Docker built-in discovery mechanisms to work via querying the respective container engines over Unix sockets
1. `$ dnf install qemu-user-static`
2. `$ mvn -Dbuild.arch=amd64 clean package ; podman image prune -f`
3. Run `CRYOSTAT_IMAGE=quay.io/... CRYOSTAT_PLATFORM=io.cryostat.platform.internal.PodmanPlatformStrategy sh smoketest.sh` with the new ARM64 Cryostat image
4. Verify that the `Podman` discovery `Realm` exists and is populated with sample applications
5. Check the server …

chore(pom): add native dependency for netty on arm64

---

.github/release-drafter.yml
.github/workflows/ci-build-image.yml
.github/workflows/ci-code-analysis.yml
.github/workflows/dependent-issues.yml
.github/workflows/image-cleanup.yml
.github/workflows/linked-issue.yml
.github/workflows/pr-ci.yml
.github/workflows/pr-labeled.yml
.github/workflows/push-ci.yml
.github/workflows/release-drafter.yml
.github/workflows/semantic-pr.yml

Related to #1599 
Explicitly specify `package:write` (for push) permission. This would also mean other permissions that are listed for this job are denied.
We should implement strict permission requests in #1634 after taking in consideration of third-party actions. Also, some scope might enclose other scopes.

ci(permissions): set explicit write permission requests with restrictive GITHUB_TOKEN

---

.github/workflows/pr-remove-request-review.yml
.github/workflows/pr-request-review.yml

Fixes: #1585 
This change will add a label `review-requested`  on the PR when `/request-review` command is detected and then remove it if the reviewer requested changed on the PR
Raised by Max in the Cryostat team
2. *...*

feat(ci): implement PR command /request-review

---

src/main/java/io/cryostat/discovery/DiscoveryModule.java
src/main/java/io/cryostat/discovery/DiscoveryStorage.java
src/main/java/io/cryostat/net/AgentClient.java
src/main/java/io/cryostat/net/NetworkModule.java
src/main/java/io/cryostat/platform/internal/DockerPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/PodmanPlatformStrategy.java
src/main/java/io/cryostat/recordings/RecordingsModule.java
src/test/java/io/cryostat/discovery/DiscoveryStorageTest.java

Fixes: #1649
Related to #1629 #1636
This:
- updates calls to `ForkJoinPool.commonPool()` to use specific Executor instances where sensible. This may increase some overhead by allowing more threads to be created than there are CPUs to run them, but also helps to isolate various components from each other so that they do not share worker pools and threading bugs in one component do not starve every other component.
- forces the minimum Vert.x event loop pool size to be the same as the default, plus 4 additional at minimum. This worker pool owns the threads that perform the application startup and initialization of all the various …

fix(startup): platform detection progresses with limited parallelism

---

pom.xml
run.sh

Fixes: #1512 
The current setup has the specified image builder run the save command, but only podman has the `--format` option [[0]](https://docs.podman.io/en/v4.4/markdown/podman-save.1.html) whereas docker does not [[1]](https://docs.docker.com/engine/reference/commandline/save/). It looks like `--format` was used to specify the `docker-archive` format, but this is the default behaviour [[0]](https://docs.podman.io/en/v4.4/markdown/podman-save.1.html) so it can be removed.
[0] https://docs.podman.io/en/v4.4/markdown/podman-save.1.html
[1] https://docs.docker.com/engine/reference/commandline/save/
Lets docker-ce create a local …

fix(build): allow Cryostat to be buildable with docker-ce

---

pom.xml

Unfortunately, we still need these properties to be separate for downstream builds.
Related to: #1589

build(pom): restore dagger compiler property

---

.github/workflows/ci-build-image.yml

CI should use the ref stored in this repo.

ci(submodule): don't use remote branch HEAD

---

smoketest.sh
src/main/java/io/cryostat/discovery/DiscoveryStorage.java
src/main/java/io/cryostat/net/NetworkModule.java
src/main/java/io/cryostat/net/web/http/api/beta/MatchExpressionsPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/CredentialsPostHandler.java

Fixes: https://github.com/cryostatio/cryostat/issues/1633
See also https://github.com/cryostatio/cryostat-agent/pull/193
Based on #1636
Improves error handling and cleanup when plugin registrations fail and are associated with stored credentials.
This along with https://github.com/cryostatio/cryostat-agent/pull/193 increases the resiliency of the server/agent registration system so that temporary networking failures or registration conflicts or other bugs are less likely to leave the server and agent both in a state where neither recognizes the other and yet neither is able to clean up and reset the registration status.
1. *Run …

fix(discovery): plugin registration bugfixes

---

src/main/java/io/cryostat/net/AgentClient.java
src/main/java/io/cryostat/net/AgentJFRService.java

Fixes: #1613 
This change allows users to start snapshot via HTTP
This continues the effort to bring Cryostat application feature parity between JMX and HTTP connection methods.
1. Same setup as in [https://github.com/cryostatio/cryostat/pull/1566](https://github.com/cryostatio/cryostat/pull/1566)
2. Test against the smoketest.sh http://localhost:9988/ agent target. Go to the Cryostat Web UI, Recordings, Create, and check that a recording can be started and a snapshot can be started.

feat(agent): implement HTTP JFR snapshot creation

---

docs/HTTP_API.md

Related to #852 
Update HTTP doc to include `cryostatVersion` in the response for the `/health` endpoint.
See: https://github.com/cryostatio/cryostat-web/blob/ee99ad168f707e4342444589a466f9abb0ca6599/src/app/Shared/Services/Api.service.tsx#L1626

docs(http): update health endpoint to include cryostatVersion

---

docs/HTTP_API.md
src/main/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandler.java
src/main/java/io/cryostat/net/web/http/api/v2/graph/StartRecordingOnTargetMutator.java
src/main/resources/types.graphqls
src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandlerTest.java
src/test/java/itest/GraphQLIT.java

Fixes: #1670 
Added back the `restart` parameter for backwards compatibility. Future major releases can remove it if needed but should highlight this.
See #1670 
> I recall we had some discussion around this change before but I can't remember exactly what we landed on. Since this is changing in a minor release version the API "shouldn't" change in incompatible ways, but I'm okay with changing a query parameter like this. Or we could have the endpoint handler handle both forms and prefer the newer one if both are supplied.
The old legacy graphQL query with `restart` parameter should work fine:
```graphql
query { …
```

fix(recording): backwards compatibility for restart parameter

---

src/main/java/io/cryostat/configuration/CredentialsManager.java
src/main/java/io/cryostat/util/URIUtil.java

Fixes: #1673
When querying for stored credentials by `targetId`, check if the provided `targetId` is JMX. If not, assume it is Agent HTTP, and check if there is an exact match for the given `targetId` as well as if there is a match for that `targetId` without the `userinfo` part of the URI.
This way the credentials querying is lenient on clients not including stored credentials in the Agent HTTP URI, which should not normally be expected - the server has those credentials stored in the encrypted database table, provided to it by the Agent instance, so these credentials are not known to the client and the reference to them in the …

fix(credentials): query for Agent HTTP credentials without specific userinfo

---

pom.xml

Fixes: #1488
Depends on https://github.com/cryostatio/cryostat-web/pull/1116

build(frontend): update node version

---

src/main/java/io/cryostat/discovery/DiscoveryStorage.java
src/test/java/io/cryostat/discovery/DiscoveryStorageTest.java

Fixes: #1698
Modifies the `DiscoveryStorage` plugin ping logic to be tolerant of request failures or network exceptions by remapping the ping task future to one that logs exceptions but does not propagate the `Future` failure to the aggregate `Future` representing the entire task.
When this plugin ping prune task is done periodically failures are already ignored. However, when this task is done initially at startup to check plugin registrations already present in the database from the last run, ping failures would fail the whole task, cascading into failing the server startup. This should not happen - the server is not dependent …

fix(discovery): do not fail startup if plugin ping fails

---

.github/dependabot.yml

Related to #1695
Increases the Dependabot open PR limit from 10 to 20
This project has quite a few dependencies, and we often get stuck waiting for downstream versions of dependencies to be available before merging Dependabot PRs. Meanwhile, other dependencies get updated but we miss the notifications because we already have 10 pending PRs open and waiting. I think it's worth testing increasing the limit so we don't let other things, which may not necessarily require a downstream equivalent (ex. Maven plugins), get too out of date.

chore(dependabot): increase PR limit

---

pom.xml

build(deps): bump org.bouncycastle:bcprov-jdk18on

---

pom.xml

fix(build): use vertx-dependencies and netty-bom for version management

---

CONTRIBUTING.md

Fixes: #1665 
updated CONTRIBUTING.md

docs(contribute): update contributing guides

---

.github/CODEOWNERS
.github/dependabot.yml

Related to #1660 
Update code owner to reference cryostat maintainers. This still asks review from reviewer team tho.
See #1660

ci(dependabot): request review for deps update from maintainers

---

pom.xml

Fixes: #1742
Excludes slf4j artifacts from the vertx-dependencies bom. We define our own version and scopes.
This restores missing log messages since #1720.
2. Check server logs for messages like:
```
INFO: Observing new target: io.cryostat.platform.ServiceRef@1eea678c[alias=io.cryostat.Cryostat,annotations=io.cryostat.platform.ServiceRef$Annotations@55e20de0[cryostat={HOST=cryostat, PORT=9091, JAVA_MAIN=io.cryostat.Cryostat, REALM=JDP},platform={}],jvmId=<null>,labels={},serviceUri=service:jmx:rmi:///jndi/rmi://cryostat:9091/jmxrmi]
...
INFO: Outgoing WS message: …
```

fix(logging): exclude slf4j from vertx bom

---

.github/dependabot.yml

ci(dependabot): remove reviewers config

---

src/main/java/io/cryostat/recordings/RecordingArchiveHelper.java

Fixes: #1738 
Related: #1731 #1692

fix(recordings): fix bug caused by #1692

---

.github/workflows/ci-build-image.yml
.github/workflows/push-ci.yml

ci(build-image): remove ghcr user login

---

src/main/java/io/cryostat/net/web/http/generic/HealthLivenessGetHandler.java

fix(liveness): execute on worker pool

---

.github/workflows/ci-build-image.yml
.github/workflows/ci-code-analysis.yml
.github/workflows/integrated-test.yml
.github/workflows/pr-ci.yml

chore(ci): update ci

---

.github/workflows/pr-ci.yml

chore(ci): /build_test comment includes code-analysis outcome

---

.github/workflows/push-ci.yml
pom.xml

Fixes: #1818 
* Add `--tags` argument to `git describe` when computing the version at build time.
* Add `on.push.tags` event to `push-ci` workflow to re-run the build and push after a release tag is made. 
CI was failing to use the X.Y.Z version number in release builds.
1. Wait for next release?

ci(release): consider lightweight tags, run workflow on tag

---

src/test/java/itest/ClientAssetsIT.java

test(client-assets): update test for relative app bundle location

---

src/main/java/io/cryostat/discovery/BuiltInDiscovery.java
src/main/java/io/cryostat/discovery/DiscoveryStorage.java
src/main/java/io/cryostat/platform/AbstractPlatformClient.java
src/main/java/io/cryostat/platform/PlatformClient.java
src/main/java/io/cryostat/platform/PlatformModule.java
src/main/java/io/cryostat/platform/internal/CustomTargetPlatformClient.java
src/main/java/io/cryostat/platform/internal/DefaultPlatformClient.java
src/main/java/io/cryostat/platform/internal/DefaultPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/DockerPlatformClient.java
src/main/java/io/cryostat/platform/internal/DockerPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/KubeApiPlatformClient.java
src/main/java/io/cryostat/platform/internal/KubeApiPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/OpenShiftPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/PlatformStrategyModule.java
src/main/java/io/cryostat/platform/internal/PodmanPlatformClient.java
src/main/java/io/cryostat/platform/internal/PodmanPlatformStrategy.java
src/test/java/io/cryostat/platform/internal/CustomTargetPlatformClientTest.java
src/test/java/io/cryostat/platform/internal/DefaultPlatformClientTest.java
src/test/java/io/cryostat/platform/internal/KubeApiPlatformClientTest.java

Fixes: #1864
Removes `BUILTIN_DISCOVERY_DISABLED` environment variable from the platform detection selection logic. This is an unfortunate and very old design decision I made that the platform integration is coupled to both the default auth manager as well as platform-specific target discovery mechanism. This made sense when originally implemented because it never made sense for platform-specific discovery mechanisms to overlap, but with the advent of custom targets and later the pluggable discovery API, and then with support for both Podman and Docker API, this is clearly no longer a good assumption and no longer a good …

fix(discovery): BUILTIN_DISCOVERY_DISABLED can be specified even when PLATFORM is set

---

README.md
src/main/java/io/cryostat/configuration/Variables.java
src/main/java/io/cryostat/platform/internal/KubeApiPlatformClient.java
src/main/java/io/cryostat/platform/internal/KubeApiPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/OpenShiftPlatformStrategy.java
src/main/java/io/cryostat/platform/internal/PlatformStrategyModule.java
src/test/java/io/cryostat/platform/internal/KubeApiPlatformClientTest.java

Fixes: #1861
Adds environment variables for customizing the behaviour of the builtin k8s Endpoints discovery mechanism. Rather than always looking for ports named `jfr-jmx` or numbered `9091`, this allows the deploying user to specify a list of acceptable names and a list of acceptable numbers that should be matched, both of them comma-separated. The names list can be set to the empty list by using the value `-`, and the number list can be set to the empty list by using the value `0`. If these variables are not defined or have empty values then they default to the singleton lists of `jfr-jmx` and `9091` respectively, maintaining the …

fix(k8s): Endpoints discovery port names/numbers are configurable

---

pom.xml
src/test/java/io/cryostat/MockVertx.java
src/test/java/io/cryostat/net/web/http/api/v2/RuleDeleteHandlerTest.java
src/test/java/io/cryostat/net/web/http/api/v2/RulePatchHandlerTest.java

chore(pom): upgrade vert-x from 4.4.4 to 4.4.9

---

.github/workflows/push-ci.yml

Related to https://github.com/cryostatio/cryostat3/issues/469
Any CI-built images from this repository should no longer be tagged as `latest`.

ci(tags): do not tag images as 'latest'
